### ISSUE TITLE
PermissionsEx an error occured!

### ISSUE THREAD

**Issue by Soverraz** [PEXPlugins/PermissionsEx#1022]
hi im back and i need help again
i have a server and a pc.
when i run it on my pc it just works but on my server i get this error:

the first link text:
### Description

[Insert description of issue here]
### What PEX Saw

**Reason:** While disabling

**Stacktrace:**

```
java.lang.IllegalStateException: Error loading permissions file
    at ru.tehkode.permissions.backends.FileBackend.reload(FileBackend.java:249)
    at ru.tehkode.permissions.PermissionManager.reset(PermissionManager.java:457)
    at ru.tehkode.permissions.PermissionManager.end(PermissionManager.java:463)
    at ru.tehkode.permissions.bukkit.PermissionsEx.onDisable(PermissionsEx.java:139)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:219)
    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:481)
    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:400)
    at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:393)
    at org.bukkit.craftbukkit.v1_6_R2.CraftServer.disablePlugins(CraftServer.java:277)
    at net.minecraft.server.v1_6_R2.MinecraftServer.stop(MinecraftServer.java:343)
    at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:450)
    at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
Caused by: org.bukkit.configuration.InvalidConfigurationException: unacceptable character '�' (0xFFFD) special characters are not allowed
in "<string>", position 47
    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:138)
    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:105)
    at ru.tehkode.permissions.backends.FileBackend.reload(FileBackend.java:232)
    ... 11 more
Caused by: unacceptable character '�' (0xFFFD) special characters are not allowed
in "<string>", position 47
    at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:70)
    at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:50)
    at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)
    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53)
    ... 14 more
```
### PEX configuration

``` yaml
permissions:
  backend: file
  backends:
    file:
      file: permissions.yml
  superperms: {}
```
### Permissions database

``` yaml
groups:
  Guest:
    default: true
    prefix: �8[Guest] �7
    permissions:
    - multiverse.portal.access.*
    - essentials.spawn
    - essentials.help
    - essentials.bal
    - essentials.balance
    - essentials.balance.others
    - essentials.money
    - essentials.warps.*
    - essentials.warp
    - essentials.pay
    - essentials.tpa
    - essentials.tpahere
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.sethome
    - essentials.home
    - essentials.msg
    - essentials.tell
    - essentials.mail
    - essentials.afk
    - essentials.getpos
    - hub.use
    options:
      build: true
      rank: '1000'
  Member:
    default: false
    prefix: �a[Member] �7
    inheritance:
    - Guest
    permissions:
    - essentials.spawn
    options:
      build: true
      rank: '900'
  Moderator:
    default: false
    prefix: �9[Mod] �a
    inheritance:
    - Member
    permissions:
    - essentials.kick
    - essentials.fly
    - essentials.speed
    options:
      build: true
      rank: '800'
  Sub-Admin:
    default: false
    prefix: �3[S-Admin] �a
    inheritance:
    - Moderator
    permissions:
    - essentials.gamemode
    - essentials.sun
    - essentials.storm
    - essentials.day
    - essentials.night
    - essentials.nick
    options:
      build: true
      rank: '750'
  Admin:
    default: false
    prefix: �b[Admin] �a
    inheritance:
    - Sub-Admin
    permissions:
    - essentials.clearinventory
    - essentials.tempban
    - essentials.give
    options:
      build: true
      rank: '700'
  God:
    default: false
    prefix: �6[God] �a
    inheritance:
    - Admin
    permissions:
    - essentials.ban
    options:
      build: true
      rank: '650'
  Pandagod:
    default: false
    prefix: �8[Panda�fGod] �a
    inheritance:
    - God
    permissions:
    - '*'
    options:
      build: true
      rank: '2'
  Owner:
    default: false
    prefix: �4[Owner] �a
    permissions:
    - '*'
    options:
      build: true
      rank: '1'
users:
  Soverraz:
    group:
    - Owner
```

Â§r

error in terminal:

14:57:32 [SEVERE] Error occurred with PermissionsEx! Please post it to https://github.com/PEXPlugins/PermissionsEx/issues/new?title=&body=%23%23%23+Description+%23%23%23%0A%0A%5BInsert+description+of+issue+here%5D%0A%23%23%23+What+PEX+Saw+%23%23%23%0A%0A**Reason%3A**+While+disabling%0A%0A**Stacktrace%3A**%0A%60%60%60%0Ajava.lang.IllegalStateException%3A+Error+loading+permissions+file%0A%09at+ru.tehkode.permissions.backends.FileBackend.reload%28FileBackend.java%3A249%29%0A%09at+ru.tehkode.permissions.PermissionManager.reset%28PermissionManager.java%3A457%29%0A%09at+ru.tehkode.permissions.PermissionManager.end%28PermissionManager.java%3A463%29%0A%09at+ru.tehkode.permissions.bukkit.PermissionsEx.onDisable%28PermissionsEx.java%3A139%29%0A%09at+org.bukkit.plugin.java.JavaPlugin.setEnabled%28JavaPlugin.java%3A219%29%0A%09at+org.bukkit.plugin.java.JavaPluginLoader.disablePlugin%28JavaPluginLoader.java%3A481%29%0A%09at+org.bukkit.plugin.SimplePluginManager.disablePlugin%28SimplePluginManager.java%3A400%29%0A%09at+org.bukkit.plugin.SimplePluginManager.disablePlugins%28SimplePluginManager.java%3A393%29%0A%09at+org.bukkit.craftbukkit.v1_6_R2.CraftServer.disablePlugins%28CraftServer.java%3A277%29%0A%09at+net.minecraft.server.v1_6_R2.MinecraftServer.stop%28MinecraftServer.java%3A343%29%0A%09at+net.minecraft.server.v1_6_R2.MinecraftServer.run%28MinecraftServer.java%3A450%29%0A%09at+net.minecraft.server.v1_6_R2.ThreadServerApplication.run%28SourceFile%3A582%29%0ACaused+by%3A+org.bukkit.configuration.InvalidConfigurationException%3A+unacceptable+character+%27%EF%BF%BD%27+%280xFFFD%29+special+characters+are+not+allowed%0Ain+%22%3Cstring%3E%22%2C+position+47%0A%09at+org.bukkit.configuration.file.YamlConfiguration.loadFromString%28YamlConfiguration.java%3A55%29%0A%09at+org.bukkit.configuration.file.FileConfiguration.load%28FileConfiguration.java%3A138%29%0A%09at+org.bukkit.configuration.file.FileConfiguration.load%28FileConfiguration.java%3A105%29%0A%09at+ru.tehkode.permissions.backends.FileBackend.reload%28FileBackend.java%3A232%29%0A%09...+11+more%0ACaused+by%3A+unacceptable+character+%27%EF%BF%BD%27+%280xFFFD%29+special+characters+are+not+allowed%0Ain+%22%3Cstring%3E%22%2C+position+47%0A%09at+org.yaml.snakeyaml.reader.StreamReader.checkPrintable%28StreamReader.java%3A70%29%0A%09at+org.yaml.snakeyaml.reader.StreamReader.%3Cinit%3E%28StreamReader.java%3A50%29%0A%09at+org.yaml.snakeyaml.Yaml.load%28Yaml.java%3A399%29%0A%09at+org.bukkit.configuration.file.YamlConfiguration.loadFromString%28YamlConfiguration.java%3A53%29%0A%09...+14+more%0A%60%60%60%0A%23%23%23+PEX+configuration+%23%23%23%0A%60%60%60yaml%0Apermissions%3A%0A++backend%3A+file%0A++backends%3A%0A++++file%3A%0A++++++file%3A+permissions.yml%0A++superperms%3A+%7B%7D%0A%60%60%60%0A%23%23%23+Permissions+database+%23%23%23%0A%60%60%60yaml%0Agroups%3A%0A++Guest%3A%0A++++default%3A+true%0A++++prefix%3A+%EF%BF%BD8%5BGuest%5D+%EF%BF%BD7%0A++++permissions%3A%0A++++-+multiverse.portal.access.*%0A++++-+essentials.spawn%0A++++-+essentials.help%0A++++-+essentials.bal%0A++++-+essentials.balance%0A++++-+essentials.balance.others%0A++++-+essentials.money%0A++++-+essentials.warps.*%0A++++-+essentials.warp%0A++++-+essentials.pay%0A++++-+essentials.tpa%0A++++-+essentials.tpahere%0A++++-+essentials.tpaccept%0A++++-+essentials.tpdeny%0A++++-+essentials.sethome%0A++++-+essentials.home%0A++++-+essentials.msg%0A++++-+essentials.tell%0A++++-+essentials.mail%0A++++-+essentials.afk%0A++++-+essentials.getpos%0A++++-+hub.use%0A++++options%3A%0A++++++build%3A+true%0A++++++rank%3A+%271000%27%0A++Member%3A%0A++++default%3A+false%0A++++prefix%3A+%EF%BF%BDa%5BMember%5D+%EF%BF%BD7%0A++++inheritance%3A%0A++++-+Guest%0A++++permissions%3A%0A++++-+essentials.spawn%0A++++options%3A%0A++++++build%3A+true%0A++++++rank%3A+%27900%27%0A++Moderator%3A%0A++++default%3A+false%0A++++prefix%3A+%EF%BF%BD9%5BMod%5D+%EF%BF%BDa%0A++++inheritance%3A%0A++++-+Member%0A++++permissions%3A%0A++++-+essentials.kick%0A++++-+essentials.fly%0A++++-+essentials.speed%0A++++options%3A%0A++++++build%3A+true%0A++++++rank%3A+%27800%27%0A++Sub-Admin%3A%0A++++default%3A+false%0A++++prefix%3A+%EF%BF%BD3%5BS-Admin%5D+%EF%BF%BDa%0A++++inheritance%3A%0A++++-+Moderator%0A++++permissions%3A%0A++++-+essentials.gamemode%0A++++-+essentials.sun%0A++++-+essentials.storm%0A++++-+essentials.day%0A++++-+essentials.night%0A++++-+essentials.nick%0A++++options%3A%0A++++++build%3A+true%0A++++++rank%3A+%27750%27%0A++Admin%3A%0A++++default%3A+false%0A++++prefix%3A+%EF%BF%BDb%5BAdmin%5D+%EF%BF%BDa%0A++++inheritance%3A%0A++++-+Sub-Admin%0A++++permissions%3A%0A++++-+essentials.clearinventory%0A++++-+essentials.tempban%0A++++-+essentials.give%0A++++options%3A%0A++++++build%3A+true%0A++++++rank%3A+%27700%27%0A++God%3A%0A++++default%3A+false%0A++++prefix%3A+%EF%BF%BD6%5BGod%5D+%EF%BF%BDa%0A++++inheritance%3A%0A++++-+Admin%0A++++permissions%3A%0A++++-+essentials.ban%0A++++options%3A%0A++++++build%3A+true%0A++++++rank%3A+%27650%27%0A++Pandagod%3A%0A++++default%3A+false%0A++++prefix%3A+%EF%BF%BD8%5BPanda%EF%BF%BDfGod%5D+%EF%BF%BDa%0A++++inheritance%3A%0A++++-+God%0A++++permissions%3A%0A++++-+%27*%27%0A++++options%3A%0A++++++build%3A+true%0A++++++rank%3A+%272%27%0A++Owner%3A%0A++++default%3A+false%0A++++prefix%3A+%EF%BF%BD4%5BOwner%5D+%EF%BF%BDa%0A++++permissions%3A%0A++++-+%27*%27%0A++++options%3A%0A++++++build%3A+true%0A++++++rank%3A+%271%27%0Ausers%3A%0A++Soverraz%3A%0A++++group%3A%0A++++-+Owner%0A%60%60%60%0AÂ§r. Full error:
java.lang.IllegalStateException: Error loading permissions file
        at ru.tehkode.permissions.backends.FileBackend.reload(FileBackend.java:249)
        at ru.tehkode.permissions.PermissionManager.reset(PermissionManager.java:457)
        at ru.tehkode.permissions.PermissionManager.end(PermissionManager.java:463)
        at ru.tehkode.permissions.bukkit.PermissionsEx.onDisable(PermissionsEx.java:139)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:219)
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:481)
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:400)
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:393)
        at org.bukkit.craftbukkit.v1_6_R2.CraftServer.disablePlugins(CraftServer.java:277)
        at net.minecraft.server.v1_6_R2.MinecraftServer.stop(MinecraftServer.java:343)
        at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:450)
        at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
Caused by: org.bukkit.configuration.InvalidConfigurationException: unacceptable character 'ï¿½' (0xFFFD) special characters are not allowed
in "<string>", position 47
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:138)
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:105)
        at ru.tehkode.permissions.backends.FileBackend.reload(FileBackend.java:232)
        ... 11 more
Caused by: unacceptable character 'ï¿½' (0xFFFD) special characters are not allowed
in "<string>", position 47
        at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:70)
        at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:50)
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53)
        ... 14 more

Please help me i dont know what 2 do D;

I also ran it trough an online yalm parser
And i am not the best java fixer
