### ISSUE TITLE
Negative Nodes

### ISSUE THREAD

**Issue by GeorgeGee** [PEXPlugins/PermissionsEx#106]
I want to exempt, for example, essentials.sleepingignored from a group (Admin) - I have given Admin:

```
Admin:
    permissions:
    - '*'
    - -essentials.sleepingignored
    prefix: '&3Admin&f>'
```

Because they have '*' they have all the nodes, is there any way to have a negative node? I tried adding a -

Thanks.
