### ISSUE TITLE
Permission denied while it is given in permissions.yml

### ISSUE THREAD

**Issue by menelmir** [PEXPlugins/PermissionsEx#1080]
Hello,
I think there is a bug in PEX, because with the following configuration (which worked until a recent update of craftbukkit), I get permission denied for the group "common-admin", when members try to use a command even so granted by herited groups.

For example, (for worlds minelec & soovis) the group common-admin, inherit from common-moderator, which inherit from common-user. The group common-user enables the command "gamemode", so common-admin should have access to the command to. But it is not !
However, if I demote a common-admin member et promote him again, he gets access to the command. In the same way, it works again if the member goes to another world 
and then come back (minelec => soovis => minelec).

Please note there are two group ladders, and users can be on the two both.
There is my permission.yml file (I cleared some permissions from the list to make it easier to read by you, so even if it could seems incoherent, in practice it isn't).

Hope I help you,
## Thanks.

``` yaml
groups:
  common-default:
    default: true
    options:
      rank: '10000'
      rank-ladder: common
    permissions:
    - bukkit.command.help
    - bukkit.command.list
    worlds:
      minelec:
        permissions:
        - bukkit.command.kill
        - bukkit.command.me
      soovis:
        permissions:
        - bukkit.command.kill
        - bukkit.command.me
  common-user:
    inheritance:
    - common-default
    options:
      rank: '1000'
      rank-ladder: common
    permissions:
    - bukkit.command.tell
    worlds:
      minelec:
        permissions:
        - bukkit.command.gamemode
        - bukkit.command.give
        - bukkit.command.teleport
      minelec2:
        permissions:
        - modifyworld.*
      soovis:
        permissions:
        - bukkit.command.gamemode
        - bukkit.command.give
        - bukkit.command.teleport
  common-premium:
    inheritance:
    - common-user
    options:
      rank: '100'
      rank-ladder: common
    worlds:
      minelec:
        permissions:
        - -worldedit.biome.set
        - -worldedit.fast
        - -worldedit.limit
        - -worldedit.reload
        - worldedit.*
  common-moderator:
    inheritance:
    - common-premium
    options:
      rank: '10'
      rank-ladder: common
    permissions:
    - bukkit.command.ban.*
    - bukkit.command.kick
    - bukkit.command.say
    - bukkit.command.unban.*
    - permissions.manage
    - permissions.user.demote.*
  common-admin:
    inheritance:
    - common-moderator
    options:
      rank: '1'
      rank-ladder: common
    permissions:
    - bukkit.command.save.perform
    - bukkit.command.stop
    - permissions.user.promote.common
    worlds:
      minelec:
        permissions:
        - chunkload.usage
  soovis-user:
    inheritance:
    - common-user
    options:
      rank: '1000'
      rank-ladder: soovis
    worlds:
      soovis:
        permissions:
        - modifyworld.*
        - weatherchange.changeweather
  soovis-premium:
    inheritance:
    - common-premium
    - soovis-user
    options:
      rank: '100'
      rank-ladder: soovis
    worlds:
      soovis:
        permissions:
        - -worldedit.biome.set
        - -worldedit.fast
        - -worldedit.limit
        - -worldedit.reload
        - worldedit.*
  soovis-moderator:
    inheritance:
    - common-moderator
    - soovis-premium
    options:
      rank: '10'
      rank-ladder: soovis
  soovis-admin:
    inheritance:
    - common-admin
    - soovis-moderator
    options:
      rank: '1'
      rank-ladder: soovis
    permissions:
    - permissions.manage.membership.soovis-user
    - permissions.user.promote.soovis
    worlds:
      soovis:
        permissions:
        - chunkload.usage
        - multiverse.core.spawn.set
worlds:
  minelec2_nether:
    inheritance:
    - minelec2
  minelec2_the_end:
    inheritance:
    - minelec2
  minelec_nether:
    inheritance:
    - minelec
  minelec_the_end:
    inheritance:
    - minelec
  soovis_nether:
    inheritance:
    - soovis
users:
  user1:
    group:
    - common-admin
    - soovis-admin
  user2:
    group:
    - common-admin
  user3:
    group:
    - common-moderator
    - soovis-user
  TestPlayer0: {}
```
