### ISSUE TITLE
Order is reversed when deploying SQL, destroying all negations.

### ISSUE THREAD

**Issue by jomo** [PEXPlugins/PermissionsEx#1153]
I tried to switch from file to SQL and all negations are now broken.
- using a file backend

``` yaml
#permissions.yml
groups:
  test:
    default: true
    permissions:
    - -test.foobar
    - test.*
```

> pex group test
> > 1) -test.foobar
> > 2) test.*
> 
> pex user testuser check test.foobar
> > ...false
> 
> pex dump sql deploy.sql
- stop server
- switch to sql backend
- restart server

> > Deploying default database scheme
> > Database scheme deploying complete
> 
> pex group test
> > 1) test.*
> > 2) -test.foobar
> 
> pex user testuser check test.foobar
> > ...true

---

As you can see above, the order reversed and caused `test.foobar` to be allowed. This is very annoying + can cause serious issues when it's not noticed.
