### ISSUE TITLE
Inherited permissions not being negated when using sql backend

### ISSUE THREAD

**Issue by Wh1rledPeas** [PEXPlugins/PermissionsEx#1175]
I am finding an issue with inherited permissions not being negated when using sql backend, as opposed to file backend.  I suspect that this may be due to a difference in the ordering of inherited permissions coming before the group permissions.

One such group is illustrated below:

```
ClassB:
    prefix: '&0[&eGroup B&0]&7 '
    permissions:
        - -myplugin.commands.groupbcommand
        - -myplugin.grouptype.member
        - myplugin.grouptype.memberclass
        - essentials.kits.groupbkit
    inheritance:
        - GroupA
```

In Java, when I check to see if group "ClassB" has the permission of "myplugin.grouptype.member", it returns false (as it should) when using the file based permissions.  When using sql based permissions, it comes back true.

As you can see in the definition above, that permission SHOULD be negated for this group.

Is this due to the fact that I have the Inherited items listed after the permissions in my file?  Perhaps the sql backend treats them in reverse?  Is there a way to specify which order to use?  I have always put my inherited items at the bottom of my User and/or Group definitions.  If at all possible, I'd simply like to specify that when using the sql backend, that I want inherited permissions to be evaluated AFTER local permissions.
