### ISSUE TITLE
Crash On Bootup

### ISSUE THREAD

**Issue by namurt28** [PEXPlugins/PermissionsEx#1193]
For some reason, whenever i bootup my server it crashes. Heres my yml

The Spacing Is All Correct. Github puts it all back.

``` yaml
groups:
  chicken:
    default: true
    permissions:
    - essentials.balance
    - essentials.suicide
    - modifyworld.*
    - rankup.rankup
    - essentials.spawn
    - essentials.signs.use.warp
    - essentials.signs.use.heal
    - essentials.signs.use.disposal
    - essentials.signs.use.sell
    - essentials.signs.use.buy
    prefix: '&f[&6Chicken&f]'
  sheep:
    prefix: '&d[&fSheep&d]&f'
    inheritance:
    - chicken
  pig:
    prefix: '&d[&5Pig&d]&f'
    inheritance:
    - sheep
  cow:
    prefix: '&0[&fCow&0]&f'
    inheritance:
    - pig
  squid:
    prefix: '&3[&1Squid&3]&f'
    inheritance:
    - cow
  horse:
    prefix: '&f[&7Horse&f]'
    inheritance:
    - squid
  ocelot:
    prefix: '&e[&6Ocelot&e]&f'
    inheritance:
    - horse
  wolf:
    prefix: '&7[&fWolf&7]&f'
    inheritance:
    - ocelot
  snowman:
    prefix: '&6[&fSnowman&6]&f'
    inheritance:
    - wolf
  irongolem:
    prefix: '&8[&7IronGolem&8]&f'
    inheritance:
    - snowman
  silverfish:
    prefix: '&0[&8Silverfish&0]&f'
    inheritance:
    - irongolem
  zombie:
    prefix: '&2[&aZombie&2]&f'
    inheritance:
    - silverfish
  skeleton:
    prefix: '&8[&7Skeleton&8]&f'
    inheritance:
    - zombie
  creeper:
    prefix: '&a[&2Creeper&a]&f'
    inheritance:
    - skeleton
  slime:
    prefix: '&0[&aSlime&0]&f'
    inheritance:
    - creeper
  enderman:
    prefix: '&0[&5&mSl&r&5enderman&0]&f'
    inheritance:
    - slime
  zimbiepogman:
    prefix: '&a[&dZimbiePogman&a]&f'
    inheritance:
    - enderman
  magmacube:
    prefix: '&0[&4MagmaCube&0]&f'
    inheritance:
    - zimbiepogman
  ghast:
    prefix: '&4[&fGhast&4]&f'
    inheritance:
    - magmacube
  blaze:
    prefix: '&e[&6Blaze&e]&f'
    inheritance:
    - ghast
  wither:
    prefix: '&8[&0Wither&8]&f'
    inheritance:
    - blaze
  enderdragon:
    prefix: '&5[&0Enderdragon&5]&f'
    inheritance:
    - wither
  herobrine:
    prefix: '&0[&4Herobrine&0]&f'
    inheritance:
    - enderdragon
  notch:
    prefix: '&c[&3Notch&c]&f'
    inheritance:
    - herobrine
  immortal:
    prefix: '&4[&bImmortal&4]&f'
    inheritance:
    - notch
  guard:
    prefix: '&6[&2Guard&6]&f'
    inheritance:
    - immortal
    permissions:
    - essentials.jail
  headguard:
    prefix: '&9[&dHeadGuard&9]&f'
    inheritance:
    - guard
  warden:
    prefix: '&5[&3Warden&5]&f'
    inheritance:
    - headguard
  owner:
    permissions:
    - '*'
    prefix: '&9[&4&k...&r&bOwner&4&k...&r&9]&b'
    inheritance:
    - admin
  admin:
    permissions:
    - '*'
    prefix: '&5[&dAdmin&5]&f'
    inheritance:
    - srwarden
  srwarden:
    prefix: '&3[&4Sr&cWarden&3]&f'
    inheritance:
    - warden
  thor:
    suffix: '&7&l[&6&lThor&7&l]&r&f'
    permissions:
    - kits.spawn.Thor
    - kits.spawn.ThorPick
    - modifyworld.*
  flash:
    suffix: '&e&l[&c&lFlash&e&l]&r&f'
    permissions:
    - kits.spawn.Flash
    - kits.spawn.FlashPick
    inheritance:
    - thor
  captainamerica:
    suffix: '&c&l[&3&lCaptainAmerica&c&l]&r&f'
    permissions:
    - kits.spawn.CAmerica
    - kits.spawn.CAmericaPick
    - kits.spawn.CAmericaGun
    inheritance:
    - flash
  wonderwoman:
    suffix: '&c&l[&e&lWonderWoman&c&l]&r&f'
    permissions:
    - kits.spawn.WonderWoman
    - kits.spawn.WonderWomanPick
    inheritance:
    - captainamerica
  hulk:
    suffix: '&1&l[&2&lHulk&1&l]&r&f'
    permissions:
    - kits.spawn.Hulk
    - kits.spawn.HulkPick
    inheritance:
    - wonderwoman
  superman:
    suffix: '&3&l[&c&lSuperman&3&l]&r&f'
    permissions:
    - kits.spawn.Superman
    - kits.spawn.SupermanPick
    inheritance:
    - hulk
  ironman:
    suffix: '&6&l[&4&lIronMan&6&l]&r&f'
    permissions:
    - kits.spawn.IronMan
    - kits.spawn.IronManPick
    inheritance:
    - superman
  batman:
    suffix: '&6&l[&0&lBatman&6&l]&r&f'
    permissions:
    - kits.spawn.Batman
    - kits.spawn.BatmanPick
    - kits.spawn.BatmanGun
    inheritance:
    - ironman
users:
  namurt28:
    group:
    - owner
    - batman
    suffix: '&0&l[&4&lDeadpool&0&l]&r&f'
    options:
      message-format: '%suffix &bNam %prefix: %message'
  BerkoBlack:
    group:
    - hulk
    - admin
  Reaper72_:
    group:
    - batman
    - srwarden
  MrPurple57:
    group:
    - batman
    - admin
    suffix: '&c[&5&lTrick&a&lShot&c]'
  dricoequist:
    group:
    - sheep
    - hulk
    - chicken
  bludragan1232:
    group:
    - pig
    - chicken
    - ironman
    - wonderwoman
    - srwarden
  GalaXyRoVer:
    suffix: '&6[&c<3&4&lImagine&a&lDragons&6]'
    group:
    - admin
  00Firemaster00:
    group:
    - superman
    - owner
```
