### ISSUE TITLE
player.isPermissionSet(...) returns false - always

### ISSUE THREAD

**Issue by Evenprime** [PEXPlugins/PermissionsEx#132]
Just noticed this while trying to help somebody in this thread http://forums.bukkit.org/threads/problem-with-permissions.46084/.

Testcase:

Call "player.isPermissionSet(...)" for an arbitrary permission node.

Expected Result:

If the permission is set to true or false (because it is written in the permissions.yml of PermissionsEx), the answer should be true or false respectively.

Actual result:

false, almost all the time.

Additional info:

These are actually two problems, one is a bug, the other a related request. For one, the "isPermissionSet(...)" method normally returns for SuperPerms permission nodes "true" if the node is set to true by "default" for that player (in the plugin.yml), and it returns "true" if the node or one of its parents were explicitely assigned ("true" or "false") to the player (simplified).

The second one is that PermissionsEx returns false for this whenever the permission node is NOT a SuperPerms node. E.g. giving a player the node "a.random.nonexisting.node" and then asking player.isPermissionSet("a.random.nonexisting.node") the answer will be false, despite player.hasPermission("a.random.nonexisting.node") returning "true". So this second part is a request to change that and return true if the node is somehow set in PermissionsEx to a specific value.

Used configuration file:

``` yaml
permissions:
    backends:
        file:
            file: permissions.yml
    backend: file
    superperms:
        parent-nodes: true
        enable: true
        strict-mode: false
    createUserRecords: false
    allowOps: false
    debug: false
    basedir: plugins/PermissionsEx
```
