### ISSUE TITLE
asdasd

### ISSUE THREAD

**Issue by IIEndermanII** [PEXPlugins/PermissionsEx#1342]
```
groups:
  Nuevo:
    default: true
    prefix: '&9'
    permissions:
    - essentials.sethome.multiple
    - factions.kit.fullplayer
    - factions.kit.halfplayer
    - factions.admin
    - factions.autoclaim
    - factions.chat
    - factions.claim
    - factions.deinvite
    - factions.description
    - factions.disband
    - factions.help
    - factions.home
    - factions.invite
    - factions.join
    - factions.kick
    - factions.leave
    - factions.list
    - factions.map
    - factions.mod
    - factions.money.kit.standard
    - factions.noboom
    - factions.open
    - factions.owner
    - factions.ownerlist
    - factions.power
    - factions.power.any
    - factions.relation
    - factions.sethome
    - factions.show
    - factions.tag
    - factions.title
    - factions.version
    - factions.unclaim
    - factions.unclaimall
    - factions.money.balance
    - factions.money.balance.any
    - factions.money.deposit
    - factions.money.withdraw
    - factions.money.f2f
    - factions.money.f2p
    - factions.money.p2f
    - essentials.helpop
    - -bukkit.command.plugins
    - -bukkit.command.pl
    - essentials.ignore
    - essentials.delhome
    - essentials.kit
    - essentials.kits.survival
    - essentials.kits.cuero
    - essentials.kits.hierro
    - pvphealth.attack
    - essentials.signs.use.____
    - essentials.signs.use.*
    - essentials.signs.use
    - creativegates.use
    - essentials.warp.list
    - essentials.protect
    - essentials.build
    - plotme.use.home
    - plotme.use.auto
    - plotme.limit.1
    - plotme.use
    - essentials.motd
    - essentials.pay
    - plotme.use.add
    - plotme.use.remove
    - essentials.warp
    - essentials.pay
    - plotme.use.claim
    - essentials.home
    - essentials.sethome
    - essentials.help
    - essentials.list
    - essentials.rules
    - essentials.spawn
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.tpa
    - essentials.mail
    - essentials.mail.send
    - essentials.balance
    - essentials.msg
    - WarpSigns.use
  Vip:
    permissions:
    - essentials.chat.color
    - essentials.chat.format
    - essentials.chat.shout
    - essentials.chat.question
    - essentials.kit
    - essentials.kits.hierro
    - essentials.kits.survival
    - essentials.kits.cuero
    - essentials.kits.vip
    - essentials.joinfullserver
    - essentials.sethome.multiple
    - factions.kit.fullplayer
    - factions.kit.halfplayer
    - factions.admin
    - factions.autoclaim
    - factions.chat
    - factions.claim
    - factions.deinvite
    - factions.description
    - factions.disband
    - factions.help
    - factions.home
    - factions.invite
    - factions.join
    - factions.kick
    - factions.leave
    - factions.list
    - factions.map
    - factions.mod
    - factions.money.kit.standard
    - factions.noboom
    - factions.open
    - factions.owner
    - factions.ownerlist
    - factions.power
    - factions.power.any
    - factions.relation
    - factions.sethome
    - factions.show
    - factions.tag
    - factions.title
    - factions.version
    - factions.unclaim
    - factions.unclaimall
    - factions.money.balance
    - factions.money.balance.any
    - factions.money.deposit
    - factions.money.withdraw
    - factions.money.f2f
    - factions.money.f2p
    - factions.money.p2f
    - essentials.helpop
    - -bukkit.command.plugins
    - -bukkit.command.pl
    - essentials.workbench
    - essentials.ignore
    - essentials.back
    - essentials.hat
    - essentials.repair
    - essentials.fly
    - pvphealth.attack
    - essentials.signs.use.____
    - essentials.signs.use.*
    - essentials.signs.use
    - creativegates.use
    - essentials.warp.list
    - essentials.protect
    - essentials.build
    - plotme.use.home
    - plotme.use.auto
    - plotme.limit.1
    - plotme.use
    - essentials.delhome
    - essentials.motd
    - essentials.pay
    - plotme.use.add
    - plotme.use.remove
    - essentials.warp
    - essentials.pay
    - plotme.use.claim
    - essentials.home
    - essentials.sethome
    - essentials.help
    - essentials.list
    - essentials.rules
    - essentials.spawn
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.tpa
    - essentials.mail
    - essentials.mail.send
    - essentials.balance
    - essentials.msg
    - WarpSigns.use
    prefix: '&b[&bVip]&9 '
  Vip+:
    permissions:
    - essentials.chat.color
    - essentials.chat.format
    - essentials.chat.shout
    - essentials.chat.question
    - essentials.nick.format
    - essentials.nick
    - essentials.clearinventory
    - essentials.joinfullserver
    - essentials.sethome.multiple.vip
    - essentials.sethome.multiple
    - factions.kit.fullplayer
    - factions.kit.halfplayer
    - factions.admin
    - factions.autoclaim
    - factions.chat
    - factions.claim
    - factions.deinvite
    - factions.description
    - factions.disband
    - factions.help
    - factions.home
    - factions.invite
    - factions.join
    - factions.kick
    - factions.leave
    - factions.list
    - factions.map
    - factions.mod
    - factions.money.kit.standard
    - factions.noboom
    - factions.open
    - factions.owner
    - factions.ownerlist
    - factions.power
    - factions.power.any
    - factions.relation
    - factions.sethome
    - factions.show
    - factions.tag
    - factions.title
    - factions.version
    - factions.unclaim
    - factions.unclaimall
    - factions.money.balance
    - factions.money.balance.any
    - factions.money.deposit
    - factions.money.withdraw
    - factions.money.f2f
    - factions.money.f2p
    - factions.money.p2f
    - essentials.kit
    - essentials.helpop
    - -bukkit.command.plugins
    - -bukkit.command.pl
    - essentials.nick
    - essentials.kits.survival
    - essentials.kits.cuero
    - essentials.kits.hierro
    - essentials.kits.Vipmas
    - essentials.kits.color
    - essentials.clear
    - essentials.repair.all
    - essentials.repair
    - essentials.heal
    - essentials.feed
    - essentials.delhome
    - essentials.workbench
    - essentials.ignore
    - essentials.back
    - essentials.hat
    - essentials.fly
    - pvphealth.attack
    - essentials.signs.use.____
    - essentials.signs.use.*
    - essentials.signs.use
    - creativegates.use
    - essentials.warp.list
    - essentials.protect
    - essentials.build
    - plotme.use.home
    - plotme.use.auto
    - plotme.limit.1
    - plotme.use
    - essentials.motd
    - essentials.pay
    - plotme.use.add
    - plotme.use.remove
    - essentials.warp
    - essentials.pay
    - plotme.use.claim
    - essentials.home
    - essentials.sethome
    - essentials.help
    - essentials.list
    - essentials.rules
    - essentials.spawn
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.tpa
    - essentials.mail
    - essentials.mail.send
    - essentials.balance
    - essentials.msg
    - WarpSigns.use
    prefix: '&b[&bVip&c+&b]&9'
  Premium:
    permissions:
    - essentials.nick.format
    - essentials.nick
    - essentials.nick.color
    - essentials.chat
    - essentials.chat.color
    - essentials.chat.format
    - essentials.chat.shout
    - essentials.chat.question
    - essentials.delhome
    - essentials.clearinventory
    - essentials.joinfullserver
    - essentials.sethome.multiple.staff
    - essentials.sethome.multiple
    - factions.kit.fullplayer
    - factions.kit.halfplayer
    - factions.admin
    - factions.autoclaim
    - factions.chat
    - factions.claim
    - factions.deinvite
    - factions.description
    - factions.disband
    - factions.help
    - factions.home
    - factions.invite
    - factions.join
    - factions.kick
    - factions.leave
    - factions.list
    - factions.map
    - factions.mod
    - factions.money.kit.standard
    - factions.noboom
    - factions.open
    - factions.owner
    - factions.ownerlist
    - factions.power
    - factions.power.any
    - factions.relation
    - factions.sethome
    - factions.show
    - factions.tag
    - factions.title
    - factions.version
    - factions.unclaim
    - factions.unclaimall
    - factions.money.balance
    - factions.money.balance.any
    - factions.money.deposit
    - factions.money.withdraw
    - factions.money.f2f
    - factions.money.f2p
    - factions.money.p2f
    - essentials.helpop
    - -bukkit.command.plugins
    - -bukkit.command.pl
    - essentials.repair.armor
    - essentials.nick
    - essentials.kit
    - essentials.kits.hierro
    - essentials.kits.survival
    - essentials.kits.cuero
    - essentials.kits.PremiumVipmasmas
    - essentials.kits.color
    - essentials.clear
    - essentials.repair.all
    - essentials.repair
    - essentials.heal
    - essentials.feed
    - essentials.workbench
    - essentials.ignore
    - essentials.back
    - essentials.hat
    - essentials.fly
    - pvphealth.attack
    - essentials.signs.use.____
    - essentials.signs.use.*
    - essentials.signs.use
    - creativegates.use
    - essentials.warp.list
    - essentials.protect
    - essentials.build
    - plotme.use.home
    - plotme.use.auto
    - plotme.limit.1
    - plotme.use
    - essentials.motd
    - essentials.pay
    - plotme.use.add
    - plotme.use.remove
    - essentials.warp
    - essentials.pay
    - plotme.use.claim
    - essentials.home
    - essentials.sethome
    - essentials.help
    - essentials.list
    - essentials.rules
    - essentials.spawn
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.tpa
    - essentials.mail
    - essentials.mail.send
    - essentials.balance
    - essentials.msg
    - WarpSigns.use
    prefix: '&c&k&l[&e&l[&e&lPremium&b&lVip&c&l++&e&l]&9'
    worlds:
      essentials.protect:
        options:
          pex: group
  Elite:
    permissions:
    - essentials.delhome
    - essentials.nick.format
    - essentials.nick
    - essentials.nick.color
    - essentials.chat.color
    - essentials.chat.format
    - essentials.chat.shout
    - essentials.chat.question
    - essentials.chat
    - essentials.clearinventory
    - essentials.kits.color
    - essentials.kit
    - essentials.delhome
    - essentials.kits.survival
    - essentials.kits.cuero
    - essentials.kits.ultraelitemas
    - essentials.joinfullserver
    - essentials.sethome.multiple.staff
    - essentials.sethome.multiple
    - factions.kit.fullplayer
    - factions.kit.halfplayer
    - factions.admin
    - factions.autoclaim
    - factions.chat
    - factions.claim
    - factions.deinvite
    - factions.description
    - factions.disband
    - factions.help
    - factions.home
    - factions.invite
    - factions.join
    - factions.kick
    - factions.leave
    - factions.list
    - factions.map
    - factions.mod
    - factions.money.kit.standard
    - factions.noboom
    - factions.open
    - factions.owner
    - factions.ownerlist
    - factions.power
    - factions.power.any
    - factions.relation
    - factions.sethome
    - factions.show
    - factions.tag
    - factions.title
    - factions.version
    - factions.unclaim
    - factions.unclaimall
    - factions.money.balance
    - factions.money.balance.any
    - factions.money.deposit
    - factions.money.withdraw
    - factions.money.f2f
    - factions.money.f2p
    - factions.money.p2f
    - essentials.helpop
    - -bukkit.command.plugins
    - -bukkit.command.pl
    - essentials.repair.armor
    - essentials.god
    - essentials.nick
    - essentials.kits.color
    - essentials.kits.hierro
    - essentials.clear
    - essentials.repair.all
    - essentials.repair
    - essentials.heal
    - essentials.feed
    - essentials.workbench
    - essentials.ignore
    - essentials.back
    - essentials.hat
    - essentials.fly
    - pvphealth.attack
    - essentials.signs.use.____
    - essentials.signs.use.*
    - essentials.signs.use
    - creativegates.use
    - essentials.warp.list
    - essentials.protect
    - essentials.build
    - plotme.use.home
    - plotme.use.auto
    - plotme.limit.1
    - plotme.use
    - essentials.motd
    - plotme.use.add
    - plotme.use.remove
    - essentials.warp
    - essentials.pay
    - plotme.use.claim
    - essentials.home
    - essentials.sethome
    - essentials.help
    - essentials.list
    - essentials.rules
    - essentials.spawn
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.tpa
    - essentials.mail
    - essentials.mail.send
    - essentials.balance
    - essentials.msg
    - WarpSigns.use
    prefix: '&c&l&k[&a&l&kii&c&l[&d&lUltra&a&lElite&c&l+]&a&l&kii&c&l&9'
  Moderador:
    permissions:
    - essentials.chat.color
    - essentials.chat.format
    - essentials.chat.shout
    - essentials.chat.question
    - essentials.joinfullserver
    - essentials.sethome.multiple.staff
    - essentials.kick.notify
    - essentials.kick
    - factions.kit.fullplayer
    - factions.kit.halfplayer
    - factions.admin
    - factions.autoclaim
    - factions.chat
    - factions.claim
    - factions.deinvite
    - factions.description
    - factions.disband
    - factions.help
    - factions.home
    - factions.invite
    - factions.join
    - factions.kick
    - factions.leave
    - factions.list
    - factions.map
    - factions.mod
    - factions.money.kit.standard
    - factions.noboom
    - factions.open
    - factions.owner
    - factions.ownerlist
    - factions.power
    - factions.power.any
    - factions.relation
    - factions.sethome
    - factions.show
    - factions.tag
    - factions.title
    - factions.version
    - factions.unclaim
    - factions.unclaimall
    - factions.money.balance
    - factions.money.balance.any
    - factions.money.deposit
    - factions.money.withdraw
    - factions.money.f2f
    - factions.money.f2p
    - factions.money.p2f
    - essetials.delhome
    - essentials.signs.use.____
    - essentials.signs.use.*
    - essentials.signs.usehe
    - essentials.nick.color
    - essentials.tp.1segundo
    - essentials.tp
    - Quickshop.create.sell
    - creativegates.use
    - WarpSigns.use
    - essentials.sethome.multiple.staff
    - essentials.protect
    - essentials.nick.color
    - essentials.nick
    - essentials.repair.all
    - essentials.build
    - essentials.enderchest
    - essentials.afk.auto
    - essentials.feed
    - essentials.qs
    - essentials.setwarp
    - essentials.chat
    - essentials.chat.color
    - essentials.warp
    - essentials.warp.list
    - essentials.hat
    - essentials.repair
    - plotme.use.home
    - plotme.use.auto
    - essentials.motd
    - essentials.pay
    - plotme.use.add
    - plotme.use.remove
    - essentials.pay
    - plotme.use.claim
    - essentials.afk
    - essentials.home
    - essentials.sethome
    - essentials.help
    - essentials.list
    - essentials.rules
    - essentials.spawn
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.tpa
    - essentials.mail
    - essentials.mail.send
    - essentials.balance
    - essentials.msg
    - essentials.back
    - essentials.sethome.multiple
    - essentials.delhome
    - essentials.fly
    - essentials.heal
    - Quickshop.use
    - essentials.gamemode
    prefix: '&f[&cModerador&f]&9'
  Admin:
    prefix: '&b[&cAdmin&b]&9'
    permissions:
    - essentials.chat.color
    - essentials.chat.format
    - essentials.chat.shout
    - essentials.chat.question
    - essentials.joinfullserver
    - essentials.sethome.multiple.staff
    - essentials.kick.notify
    - essentials.kick
    - factions.kit.fullplayer
    - factions.kit.halfplayer
    - factions.admin
    - factions.autoclaim
    - factions.chat
    - factions.claim
    - factions.deinvite
    - factions.description
    - factions.disband
    - factions.help
    - factions.home
    - factions.invite
    - factions.join
    - factions.kick
    - factions.leave
    - factions.list
    - factions.map
    - factions.mod
    - factions.money.kit.standard
    - factions.noboom
    - factions.open
    - factions.owner
    - factions.ownerlist
    - factions.power
    - factions.power.any
    - factions.relation
    - factions.sethome
    - factions.show
    - factions.tag
    - factions.title
    - factions.version
    - factions.unclaim
    - factions.unclaimall
    - factions.money.balance
    - factions.money.balance.any
    - factions.money.deposit
    - factions.money.withdraw
    - factions.money.f2f
    - factions.money.f2p
    - factions.money.p2f
    - essetials.delhome
    - essentials.signs.use.____
    - essentials.signs.use.*
    - essentials.signs.usehe
    - essentials.nick.color
    - essentials.tp.1segundo
    - essentials.tp
    - Quickshop.create.sell
    - creativegates.use
    - WarpSigns.use
    - essentials.sethome.multiple.staff
    - essentials.protect
    - essentials.nick.color
    - essentials.nick
    - essentials.repair.all
    - essentials.build
    - essentials.enderchest
    - essentials.afk.auto
    - essentials.feed
    - essentials.qs
    - essentials.setwarp
    - essentials.chat
    - essentials.chat.color
    - essentials.warp
    - essentials.warp.list
    - essentials.hat
    - essentials.repair
    - plotme.use.home
    - plotme.use.auto
    - essentials.motd
    - essentials.pay
    - plotme.use.add
    - plotme.use.remove
    - essentials.pay
    - plotme.use.claim
    - essentials.afk
    - essentials.home
    - essentials.sethome
    - essentials.help
    - essentials.list
    - essentials.rules
    - essentials.spawn
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.tpa
    - essentials.mail
    - essentials.mail.send
    - essentials.balance
    - essentials.msg
    - essentials.back
    - essentials.sethome.multiple
    - essentials.delhome
    - essentials.fly
    - essentials.heal
    - Quickshop.use
    - essentials.gamemode
    - essentials.god
    - essentials.invsee
    - essentials.time
    - essentials.time.set
    - essentials.balancetop
    - essentials.ban
    - essentials.ban.exempt
    - essentials.ban.notify
    - essentials.kick
    - essentials.kick.notify
    - essentials.unban
    - essentials.vanish
    - essentials.jump
  Ayudante:
    prefix: '&b[&6Ayudante&b]&9'
    permissions:
    - essentials.chat.color
    - essentials.chat.format
    - essentials.chat.shout
    - essentials.chat.question
    - essentials.joinfullserver
    - essentials.sethome.multiple.staff
    - factions.kit.fullplayer
    - factions.kit.halfplayer
    - factions.admin
    - factions.autoclaim
    - factions.chat
    - factions.claim
    - factions.deinvite
    - factions.description
    - factions.disband
    - factions.help
    - factions.home
    - factions.invite
    - factions.join
    - factions.kick
    - factions.leave
    - factions.list
    - factions.map
    - factions.mod
    - factions.money.kit.standard
    - factions.noboom
    - factions.open
    - factions.owner
    - factions.ownerlist
    - factions.power
    - factions.power.any
    - factions.relation
    - factions.sethome
    - factions.show
    - factions.tag
    - factions.title
    - factions.version
    - factions.unclaim
    - factions.unclaimall
    - factions.money.balance
    - factions.money.balance.any
    - factions.money.deposit
    - factions.money.withdraw
    - factions.money.f2f
    - factions.money.f2p
    - factions.money.p2f
    - essetials.delhome
    - essentials.tp.1seg
    - essentials.tp
    - essentials.signs.use.____
    - essentials.signs.use.*
    - essentials.signs.use
    - Quickshop.create.sell
    - creativegates.use
    - WarpSigns.use
    - essentials.sethome.multiple.staff
    - essentials.protect
    - essentials.nick
    - essentials.repair.all
    - essentials.build
    - essentials.enderchest
    - essentials.afk.auto
    - essentials.feed
    - essentials.qs
    - essentials.chat
    - essentials.chat.color
    - essentials.warp
    - essentials.warp.list
    - essentials.hat
    - essentials.repair
    - plotme.use.home
    - plotme.limit.1
    - plotme.use
    - plotme.use.auto
    - essentials.motd
    - essentials.pay
    - plotme.use.add
    - plotme.use.remove
    - essentials.pay
    - plotme.use.claim
    - essentials.afk
    - essentials.home
    - essentials.sethome
    - essentials.help
    - essentials.list
    - essentials.rules
    - essentials.spawn
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.tpa
    - essentials.mail
    - essentials.mail.send
    - essentials.balance
    - essentials.msg
    - essentials.back
    - essentials.sethome.multiple
    - essentials.delhome
    - essentials.fly
    - essentials.heal
    - essentials.god
    - essentials.tp
    - Quickshop.use
  Owner:
    prefix: '&0[&cOwner&0] &b>>&9'
    permissions:
    - '*'
  Contructor:
    prefix: '&6[&6Contructor&6]&l&9 '
    permissions:
    - essentials.sethome.multiple.staff
    - factions.kit.fullplayer
    - factions.kit.halfplayer
    - factions.admin
    - factions.autoclaim
    - factions.chat
    - factions.claim
    - factions.deinvite
    - factions.description
    - factions.disband
    - factions.help
    - factions.home
    - factions.invite
    - factions.join
    - factions.kick
    - factions.leave
    - factions.list
    - factions.map
    - factions.mod
    - factions.money.kit.standard
    - factions.noboom
    - factions.open
    - factions.owner
    - factions.ownerlist
    - factions.power
    - factions.power.any
    - factions.relation
    - factions.sethome
    - factions.show
    - factions.tag
    - factions.title
    - factions.version
    - factions.unclaim
    - factions.unclaimall
    - factions.money.balance
    - factions.money.balance.any
    - factions.money.deposit
    - factions.money.withdraw
    - factions.money.f2f
    - factions.money.f2p
    - factions.money.p2f
    - tntrun.game
    - essetials.delhome
    - essentials.signs.use.____
    - essentials.signs.use.*
    - essentials.signs.use
    - essentials.feed
    - Quickshop.create.sell
    - creativegates.use
    - WarpSigns.use
    - essentials.sethome.multiple.staff
    - essentials.protect
    - essentials.nick.color
    - essentials.nick
    - essentials.repair.all
    - essentials.build
    - essentials.enderchest
    - essentials.afk.auto
    - essentials.qs
    - essentials.chat
    - essentials.chat.color
    - essentials.warp
    - essentials.warp.list
    - essentials.hat
    - essentials.repair
    - plotme.use.home
    - plotme.use.auto
    - essentials.motd
    - essentials.pay
    - plotme.use.add
    - plotme.use.remove
    - essentials.pay
    - plotme.use.claim
    - essentials.afk
    - essentials.home
    - essentials.sethome
    - essentials.help
    - essentials.list
    - essentials.rules
    - essentials.spawn
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.tpa
    - essentials.mail
    - essentials.mail.send
    - essentials.balance
    - essentials.msg
    - essentials.back
    - essentials.sethome.multiple
    - essentials.delhome
    - essentials.fly
    - essentials.heal
    - essentials.lightning
    - essentials.god
    - Quickshop.use
  YouTuber:
    prefix: '&a&l&kii&f&l[&4&lYou&f&lTuber]&a&l&kii&6 '
    permissions:
    - pvphealth.attack
    - factions.kit.fullplayer
    - factions.kit.halfplayer
    - factions.admin
    - factions.autoclaim
    - factions.chat
    - factions.claim
    - factions.deinvite
    - factions.description
    - factions.disband
    - factions.help
    - factions.home
    - factions.invite
    - factions.join
    - factions.kick
    - factions.leave
    - factions.list
    - factions.map
    - factions.mod
    - factions.money.kit.standard
    - factions.noboom
    - factions.open
    - factions.owner
    - factions.ownerlist
    - factions.power
    - factions.power.any
    - factions.relation
    - factions.sethome
    - factions.show
    - factions.tag
    - factions.title
    - factions.version
    - factions.unclaim
    - factions.unclaimall
    - factions.money.balance
    - factions.money.balance.any
    - factions.money.deposit
    - factions.money.withdraw
    - factions.money.f2f
    - factions.money.f2p
    - factions.money.p2f
    - -bukkit.command.plugins
    - -bukkit.command.pl
    - essetials.delhome
    - essentials.god
    - essentials.signs.use.____
    - essentials.signs.use.*
    - essentials.signs.use
    - essentials.fly
    - essentials.signs.use
    - creativegates.use
    - essentials.warp.list
    - essentials.protect
    - essentials.build
    - plotme.use.home
    - plotme.use.auto
    - essentials.motd
    - essentials.pay
    - plotme.use.add
    - plotme.use.remove
    - essentials.warp
    - essentials.pay
    - plotme.use.claim
    - essentials.afk
    - essentials.home
    - essentials.sethome
    - essentials.help
    - essentials.list
    - essentials.rules
    - essentials.spawn
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.tpa
    - essentials.mail
    - essentials.mail.send
    - essentials.balance
    - essentials.msg
    - WarpSigns.use
  Precidente:
    prefix: '&f[&bPreci&4dente&f]&9'
    permissions:
    - factions.kit.fullplayer
    - factions.kit.halfplayer
    - factions.admin
    - factions.autoclaim
    - factions.chat
    - factions.claim
    - factions.deinvite
    - factions.description
    - factions.disband
    - factions.help
    - factions.home
    - factions.invite
    - factions.join
    - factions.kick
    - factions.leave
    - factions.list
    - factions.map
    - factions.mod
    - factions.money.kit.standard
    - factions.noboom
    - factions.open
    - factions.owner
    - factions.ownerlist
    - factions.power
    - factions.power.any
    - factions.relation
    - factions.sethome
    - factions.show
    - factions.tag
    - factions.title
    - factions.version
    - factions.unclaim
    - factions.unclaimall
    - factions.money.balance
    - factions.money.balance.any
    - factions.money.deposit
    - factions.money.withdraw
    - factions.money.f2f
    - factions.money.f2p
    - factions.money.p2f
    - tntrun.game
    - essentials.back
    - essentials.fly
    - essentials.enderchest
    - essentials.repair
    - -bukkit.command.plugins
    - -bukkit.command.pl
    - essentials.ignore
    - essentials.kits.GameFack
    - essentials.kit
    - essentials.delhome
    - essentials.kits.survival
    - essentials.kits.cuero
    - pvphealth.attack
    - essentials.signs.use.____
    - essentials.signs.use.*
    - essentials.signs.use
    - creativegates.use
    - essentials.warp.list
    - essentials.protect
    - essentials.build
    - plotme.use.home
    - plotme.use.auto
    - plotme.limit.1
    - plotme.use
    - essentials.motd
    - essentials.pay
    - plotme.use.add
    - plotme.use.remove
    - essentials.warp
    - essentials.pay
    - plotme.use.claim
    - essentials.home
    - essentials.sethome
    - essentials.help
    - essentials.list
    - essentials.rules
    - essentials.spawn
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.tpa
    - essentials.mail
    - essentials.mail.send
    - essentials.balance
    - essentials.msg
    - WarpSigns.use
  UltraVip:
    prefix: '&a&l&kii&c[&dUltra&bVip&b]&9&a&l&kii&'
    permissions:
    - essentials.chat.color
    - essentials.chat.format
    - essentials.chat.shout
    - essentials.chat.question
    - essentials.nick.format
    - essentials.nick
    - essentials.joinfullserver
    - essentials.sethome.multiple.vip
    - essentials.sethome.multiple
    - sg.arena.join.*
    - sg.arena.vote
    - sg.arena.spectate
    - factions.kit.fullplayer
    - factions.kit.halfplayer
    - factions.admin
    - factions.autoclaim
    - factions.chat
    - factions.claim
    - factions.deinvite
    - factions.description
    - factions.disband
    - factions.help
    - factions.home
    - factions.invite
    - factions.join
    - factions.kick
    - factions.leave
    - factions.list
    - factions.map
    - factions.mod
    - factions.money.kit.standard
    - factions.noboom
    - factions.open
    - factions.owner
    - factions.ownerlist
    - factions.power
    - factions.power.any
    - factions.relation
    - factions.sethome
    - factions.show
    - factions.tag
    - factions.title
    - factions.version
    - factions.unclaim
    - factions.unclaimall
    - factions.money.balance
    - factions.money.balance.any
    - factions.money.deposit
    - factions.money.withdraw
    - factions.money.f2f
    - factions.money.f2p
    - factions.money.p2f
    - tntrun.game
    - essentials.kit
    - essentials.helpop
    - -bukkit.command.plugins
    - -bukkit.command.pl
    - essentials.nick
    - essentials.kits.survival
    - essentials.kits.cuero
    - essentials.kits.hierro
    - essentials.clear
    - essentials.repair.all
    - essentials.repair
    - essentials.heal
    - essentials.feed
    - essentials.delhome
    - essentials.workbench
    - essentials.ignore
    - essentials.back
    - essentials.hat
    - essentials.fly
    - pvphealth.attack
    - essentials.signs.use.____
    - essentials.signs.use.*
    - essentials.signs.use
    - creativegates.use
    - essentials.warp.list
    - essentials.protect
    - essentials.build
    - plotme.use.home
    - plotme.use.auto
    - plotme.limit.1
    - plotme.use
    - essentials.motd
    - essentials.pay
    - plotme.use.add
    - plotme.use.remove
    - essentials.warp
    - essentials.pay
    - plotme.use.claim
    - essentials.home
    - essentials.sethome
    - essentials.help
    - essentials.list
    - essentials.rules
    - essentials.spawn
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.tpa
    - essentials.mail
    - essentials.mail.send
    - essentials.balance
    - essentials.msg
    - WarpSigns.use
    - essentials.god
users:
  wuiliamb2:
    worlds:
      Creador:
        permissions:
        - group
    permissions:
    - Creador
    group:
    - Creador
  IIEndermanII:
    group:
    - Owner
  ZenkichiCraft:
    group:
    - Owner
    worlds:
      YouTuber:
        group:
        - remove
  joako432:
    group: []
  martinlol9:
    group:
    - Elite
  zagor:
    group:
    - YouTuber
  LuchoGamerZ:
    group:
    - Vip
  Chettos3:
    group:
    - Elite
  Juancarloskiller:
    group:
    - Elite
  nombre:
    group:
    - Vip+
  XwakYz:
    group:
    - Vip
  The_Agal:
    group:
    - Elite
  hector30:
    group: []
  STORM_XL:
    group:
    - Vip
  Maximilian1243:
    group:
    - Vip
  Verapaxo:
    group:
    - Vip+
  tigernight9:
    group: []
  ws141:
    group:
    - Vip
  FelipeGaymerPro:
    group:
    - Vip
    worlds:
      roblas:
        group:
        - remove
  ClaraBethGaming:
    group: []
  Shaaix:
    group:
    - Elite
  SamasMcGee:
    group: []
  CrafteroPVP:
    group:
    - Elite
  sede:
    group:
    - Contructor
  Itachi437:
    group:
    - Contructor
  jphgolf4321:
    group:
    - YouTuber
  softkitty44:
    group:
    - Vip+
  Expert_10:
    group:
    - Vip
  znabela:
    group:
    - Vip+
  Cotil:
    group:
    - Elite
  diegho12:
    group:
    - Vip
  PoOhGaMeR:
    group:
    - Elite
  Cr0peX:
    group:
    - Vip
  gustavo100x:
    group:
    - Admin
  Maverax:
    group:
    - Elite
  manmon:
    group:
    - Elite
  Zemos52:
    group:
    - Ayudante
  Mrsweigtastic1:
    group:
    - Elite
  osk4r99:
    group:
    - Admin
  Robink10:
    group:
    - Vip
  jose251:
    group:
    - Contructor
  Scorpions:
    group:
    - Vip
  Whiteace301:
    group:
    - Vip
  ValenGamerXD:
    group:
    - Vip
  Fvpm:
    group:
    - Elite
  RedReynard:
    group:
    - Vip+
  Cokiie_Monster:
    group:
    - Vip+
  TDRAGamer:
    group:
    - Vip+
  master1103:
    group:
    - YouTuber
  roblas:
    group:
    - Elite
  mvv190:
    group:
    - Vip
  Tamara100:
    group:
    - Elite
  DeadKiiller:
    group:
    - Elite
  carnahan1999:
    group:
    - Elite
  agustin777:
    group:
    - Vip
  Diegocrafterr:
    group:
    - Vip
  EverFullPls:
    group:
    - Vip
  onedesk:
    group:
    - Elite
  Multi_PVP:
    group:
    - Vip
  MasterChafa:
    group:
    - Vip+
  crafterminer:
    group:
    - Vip
  gabriel100201:
    group:
    - Vip
  craftenminer:
    group:
    - Vip
  MCZombie2185:
    group:
    - Elite
  rusiomc:
    group:
    - Vip+
  DJDevon11:
    group:
    - Vip+
  FTPNicko:
    group:
    - Vip
  Yasminyos:
    group:
    - Vip
  Giivox:
    group:
    - Premium
  xxteylorxx:
    group:
    - Elite
  Jeancito02:
    group:
    - Vip
  Cazugames:
    group:
    - Vip+
  TheKillerRamdon:
    group:
    - Vip
  DumbaseBR:
    group:
    - Vip
  hero0127:
    group:
    - Vip+
  gamer122:
    group:
    - Vip
  mumrik02:
    group:
    - Vip+
  Anti_Frogbot:
    group:
    - Vip
  matimerengue:
    group:
    - Vip
  unitedwind1:
    group:
    - Vip+
  calumgiff1997:
    group:
    - Vip
  JGWJ:
    group:
    - Vip+
  BL1TZ:
    group:
    - Elite
  oswaldo132:
    group:
    - Elite
  redfool:
    group:
    - Vip
  DDNN368:
    group:
    - Vip
  martinixpro777:
    group:
    - Vip
  Fergamerpro:
    group:
    - Vip
  killer0507:
    group:
    - Vip
  SungMatt:
    group:
    - Vip
  EverFull:
    group:
    - Vip
  BAR3D:
    group:
    - Vip
  Gobb:
    group:
    - Vip
  IonMouse:
    group:
    - Elite
  Mrsweohyastic1:
    group: []
  shadowedplay:
    group:
    - Elite
  EverStack:
    group:
    - Vip
  funk2killa:
    group:
    - Vip+
  Facugamerpro123:
    group:
    - Vip
  GamerKid609:
    group:
    - Vip+
  MisaToonPush:
    group:
    - Vip
  Elevennn:
    group:
    - Vip
  Shabata:
    group:
    - Vip+
  MsElectroMine:
    group:
    - Elite
  Nabusax:
    group:
    - Vip
  elpapi:
    group:
    - Elite
  festero03:
    group:
    - Elite
  Ilary:
    group:
    - Vip
  SugiMori:
    group:
    - Vip
  Section99:
    group:
    - Vip+
  seba32:
    group:
    - Vip
  augustoarvia21:
    group:
    - Vip
  diamantaxe1:
    group:
    - Elite
  sonbi100:
    group:
    - Vip+
  Motherfucker:
    group:
    - Vip
  Roronoazorozz:
    group:
    - Elite
  neo1990:
    group:
    - YouTuber
  Rabstep:
    group:
    - Elite
  pinhead:
    group:
    - Vip+
  Franxter00:
    group:
    - Vip
  Agus141:
    group:
    - Vip
  AdminFalso:
    group:
    - Vip
  eKitty:
    group:
    - Vip
  Android3002:
    group:
    - YouTuber
  toti:
    group:
    - Vip
  XLuchoGamre:
    group:
    - Vip+
  Aksu:
    group:
    - Vip+
  Tronator:
    group:
    - Vip
  wolfeplayer:
    group:
    - Vip
  BryanMC:
    group:
    - Vip+
  Kamal:
    group:
    - Vip+
```
