### ISSUE TITLE
User grouping issues as of commit 'Move most hierarchy handling into PermissionEntity'.

### ISSUE THREAD

**Issue by mibby** [PEXPlugins/PermissionsEx#1357]
Compiled source as of this commit. https://github.com/PEXPlugins/PermissionsEx/commit/e24e442e8cc0f8862aad585de5a82e4aab40dce6

Newly joined users grouped are not automatically being added to the permissions config. 

Example:
- mibby joins server for the first time.
- mibby is automatically assigned to the default group of 'Guest'. (Does not group user in config.)
- mibby passes a membership quiz. From console, it automatically parses the command '/pex user [user] group set Member', whereas [user] is the username of the player passing the quiz.

Issue:
- mibby is still a 'Guest' and doesn't exist in the permissions file. 

How the groups are configured. Member does not inherit Guest, as Guest contains negative permission nodes. Member rank is the promotable standalone 'new default' after new users pass a membership quiz, where newer ranks inherit off of 'Member'. 

```
  Guest:
    default: true
    options:
      rank-ladder: Member
      rank: '6'
    permissions:
    - (permissions snipped to prevent long output.)
    prefix: '&7'
  Member:
    options:
      rank-ladder: Member
      rank: '5'
    permissions:
    - (permissions snipped to prevent long output.)
    prefix: '&b'
```

It also seems when changing someone's rank via command (those who already exist in the permissions file), they are not automatically updated / refreshed, how it was functioning a few days ago. It doesn't refresh their group. You have to type /pex reload to fresh it.

Example (typing commands from console):
- /pex user mibby group list
- Outputs mibby in the Member group.

```
[18:18:17] [Server thread/INFO]: User mibby @null currently in:
[18:18:17] [Server thread/INFO]:   Member
```
- /pex user mibby group set Admin
- /pex user mibby group list
- Outputs mibby in the Member group.

```
[18:18:49] [Server thread/INFO]: User mibby @null currently in:
[18:18:49] [Server thread/INFO]:   Member
```
- /pex reload
- /pex user mibby group list
- Outputs mibby in the Admin group.

```
[18:19:22] [Server thread/INFO]: User mibby @null currently in:
[18:19:22] [Server thread/INFO]:   Admin
```

Once again, none of these issues were occurring as of this commit a few days ago. https://github.com/PEXPlugins/PermissionsEx/commit/414226c84f664db036d6ce400004e3b9b52a7f47 It is only the newer commits which breaks functionality of how PEX was working.
