### ISSUE TITLE
Simply not working - new install

### ISSUE THREAD

**Issue by snyper82** [PEXPlugins/PermissionsEx#1361]
I've just switched from Privileges to PEX, PEx doesn't seem to be working for me, though I can change settings and such from the console, in-game I have less permissions than a guest.

```
users:
  Snyper82:
    permissions:
    - owner
  Qowface:
    permissions:
    - admin
groups:
  guest:
    default: true
    permissions:
    - globalmarket.create
    - globalmarket.history
    - craftconomy.bank.balance
    - craftconomy.bank.deposit
    - craftconomy.bank.list
    - craftconomy.bank.perm
    - craftconomy.bank.withdraw
    - craftconomy.money.balance
    - craftconomy.money.log
    - craftconomy.money.pay
    - group.guest
    - hsp.command.spawn
    options:
      rank: '1000'
    prefix: '&7Guest-'
  trusted:
    inheritance:
    - guest
    permissions:
    - craftconomy.bank.create
    - griefprevention.basicclaimcommands
    - hsp.command.home
    - hsp.command.home.otherworld
    - hsp.command.sethome
    - hsp.command.homedelete
    - hsp.home.bedsethome
    - hsp.command.homelist
    - griefprevention.loginspam
    - group.trusted
    options:
      rank: '900'
    prefix: '&2:Trusted:'
  vip:
    inheritance:
    - trusted
    permissions:
    - globalmarket.nolimit.*
    - globalmarket.noqueue
    - globalmarket.quicklist
    - globalmarket.pricecheck
    - globalmarket.quickmail
    - globalmarket.send
    - hsp.command.home.named
    - hsp.command.sethome.named
    - hsp.command.setdefaulthome
    - hsp.command.spawn.named
    - group.vip
    options:
      rank: '800'
    prefix: '&1V.I.P-'
  mod:
    inheritance:
    - vip
    permissions:
    - bukkit.command.gamemode
    - bukkit.command.give
    - bukkit.command.teleport
    - bukkit.command.ban.player
    - bukkit.command.unban.player
    - group.vipplus
    - prism.drain
    - prism.extinguish
    - prism.help
    - prism.lookup
    - prism.preview
    - prism.report
    - prism.view
    - prism.tp
    - prism.alerts
    - craftconomy.money.balance.others
    - craftconomy.money.log.others
    - griefprevention.spam
    - group.mod
    options:
      rank: '600'
    prefix: '&6Mod-'
  admin:
    inheritance:
    - mod
    permissions:
    - prism.wand.*
    - prism.drain
    - prism.rollback
    - prism.restore
    - prism.reload
    - prism.delete
    - prism.alerts
    - prism.override-max-lookup-radius
    - prism.override-max-applier-radius
    - globalmarket.infinitelistings
    - globalmarket.util
    - bukkit.command.ban.ip
    - bukkit.command.time.add
    - bukkit.command.time.set
    - bukkit.command.unban.ip
    - bukkit.command.weather
    - prism.restore
    - prism.rollback
    - chatsuite.*
    - craftconomy.currency.*
    - craftconomy.account.create
    - craftconomy.account.delete
    - craftconomy.bank.balance.others
    - craftconomy.bank.delete
    - craftconomy.bank.give
    - craftconomy.bank.perm.others
    - craftconomy.bank.set
    - craftconomy.bank.take
    - craftconomy.money.give
    - craftconomy.money.set
    - craftconomy.money.take
    - craftconomy.money.*
    - griefprevention.admin.*
    - griefprevention.commands.adminclaims
    - group.admin
    - prism.override-max-applier-radius
    - prism.override-max-lookup-radius
    - prism.reload
    options:
      rank: '400'
    prefix: '&4Admin-'
  owner:
    inheritance:
    - admin
    options:
      rank: '200'
    prefix: '&5Owner-'
  operator:
    inheritance: admin
    permissions:
    - globalmarket.admin
    - group.owner
    - prism.*
    options:
      rank: '0'
    prefix: '&N&4OPER-'
```
