### ISSUE TITLE
Permissions not working

### ISSUE THREAD

**Issue by TalkingSquirrelz** [PEXPlugins/PermissionsEx#1447]
So I went to save my permissions and it won't work I'm pretty sure I did it correctly :/

Here are my permissions:

``` yaml
groups:
  Member default: true
    permissions:
    - essentials.msg
    - essentials.balance
    - essentials.balancetop
    - essentials.pay
    - essentials.help
    - essentials.ignore
    - essentials.list
    - essentials.realname
    - essentials.rules
    - essentials.kit
    - essentials.kits.Starter
    - essentials.kits.PvP
    - essentials.warp
    - essentials.warp.list
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.sethome
    - essentials.spawn
    - essentials.signs.use.buy
    - essentials.signs.use.sell
    - essentials.signs.use.disposal
    - essentials.signs.use.heal
    - essentials.signs.use.warp
    - essentials.signs.use.kit
    - essentials.home
    - essentials.sethome.multiple.[3]
    - essentials.delhome
    - essentials.build.interact.*
    prefix: '&7[Member]&f'
    options:
    ranks: '1200'
  VIP
    permissions:
    - essentials.nick
    - essentials.sethome.multiple.[5]
    - essentials.kits.VIP
    inheritance:
    - default
    - Member
    prefix: '&9[VIP]&f'
    options:
    ranks: '1100'
  Elite:
    permissions:
    - essentials.wbench
    - essentials.back
    - essentials.sethome.multiple.[10]
    - essentials.kits.Elite
    inheritance:
    - VIP
    prefix: '&e[Elite]&f'
    options:
    ranks: '1000'
  Titan:
    permissions:
    - essentials.enderchest
    - essentials.sethome.multiple.[18]
    - essentials.nick.color
    - essentials.kits.Titan
    inheritance:
    - Elite
    prefix: '&5[Titan]&f'
    options:
    rank '900'
  Legend:
    permissions:
    - essentials.sethome.multiple.[35]
    - essentials.nick.format
    - essentials.heal
    - essentials.kits.Legend
    inheritance:
    - Titan
    prefix: '&b[Legend]&f'
    options:
    rank: '800'
  Nova:
    permissions:
    - essentials.sethome.multiple.[70]
    - essentials.nick.magic
    - essentials.near
    - essentials.kits.Nova
    inheritance:
    -Legend
    prefix: '&0[Nova]&f'
    options:
    rank: '700'
  Galaxy:
    permissions:
    - essentials.sethome.multiple.[110]
    - essentials.back
    - essentials.fly
    - essentials.kits.Galaxy
    - essentials.invsee
    - essentials.invsee.preventmodify
    inheritance:
    - Nova
    prefix: '&0&kk&4[Gal&2axy]&f'
    options:
    rank: '600'
  Helper:
    permissions:
    - essentials.mute
    - essentials.chat.ignoreexempt
    inheritance:
    - default
    - Member
    prefix: '&c[Helper]&8'
    options:
    rank: '500'
  Trial-Mod
    permissions:
    - essentials.kick
    inheritance:
    - Helper
    prefix: '&6[Trial-Mod]&8'
    options:
    rank: '400'
  Moderator:
    permissions:
    - essentials.tjail
    - essentials.jail
    - essentials.tempban
    inheritance:
    - Trial-Mod
    prefix: '&3[Moderator]&8'
    options:
    rank: '300'
  Admin:
    permissions:
    - essentials.vanish
    - essentials.broadcast
    - essentials.afk
    - essentials.ban
    inheritance:
    - Moderator
    prefix: '&4[&6Admin&4]&e'
    options:
    rank: '200'
  Head-Admin:
    permissions:
    - essentials.banip
    inheritance:
    - Moderator
    prefix: '&0[&4Head&0-&6Admin&0]'
    options:
    rank: '100'
  Co-Owner:
    permissions:
    - '*'
    inheritance:
    - Head-Admin
    prefix: '&0[&n&0&kk&bCo-&2Owner&0]&1'
    options:
    rank: '99'
  Owner:
    permissions:
    inheritance:
    - Co-Owner
    prefix: '&4[&0&k4&4Owner&0&kd&4]'
    options:
    rank: '1'
```
