### ISSUE TITLE
PEX add a option ^^

### ISSUE THREAD

**Issue by ghost** [PEXPlugins/PermissionsEx#1496]
Hello !
You can add a option for PEX ? 
Exemple : 

``` yaml
groups:
   group:
     prefix: '&8MEMBER &f'
     permissions:
     - multiworld.creativemode
     worlds:
        WORLD: 
            permissions:
           - multiworld.creativemode
           No-permissions:
           - kit
```

No-permissions allows the player to not have a permission in a world

PS: I'm french therefore my english come of https://translate.google.com :3
      But please add this option please ^^
