### ISSUE TITLE
World Specific Permissions for Groups Aren't Applied

### ISSUE THREAD

**Issue by MrSqueak** [PEXPlugins/PermissionsEx#1512]
In my server.properties I have my worlds saved as such
/worlds/Main/OverWorld

In the main worlds folder I have a folder for my extra worlds such as games and buildchallenges and trade posts.  In the previous versions of this plugin my perms worked perfectly fine. Upon upgrading they no longer work.  Below you will find the copy/paste of the main group that is being affected.

  Member:
    permissions:
    - bombercraft.play.*
    - -bukkit.command.(kill|plugins|version)
    - chesscraft.commands.(create.game|invite|join|move|offer.(draw|swap)|resign|archive|tp|win)
    - essentials.afk
    - essentials.chat.(color|format|magic|question)
    - essentials.enderchest
    - essentials.help
    - essentials.helpop
    - essentials.home
    - essentials.kit
    - essentials.kits.(color|creed|tome|Tradepost)
    - essentials.list
    - essentials.mail(|.send)
    - essentials.me
    - essentials.motd
    - essentials.msg(|.(color|format|magic))
    - essentials.recipe
    - essentials.rules
    - essentials.seen
    - essentials.sethome(|.bed)
    - essentials.warp(|.list)
    - essentials.warps.Tradepost
    - modifyworld.*
    - multiverse.access.(/worlds/extra/warp|/worlds/Main/OverWorld|/worlds/main/overworld_nether|/worlds/main/overworld_the_end)
    - multiverse.portal.access.(CanyonOverworld|CanyonWarp|ForestOverworld|ForestWarp|SnowOverworld|SnowWarp|SandWarp|SandOverworld)

THE PROBLEM STARTS HERE, none of the permissions below this point take effect.  I've tried a multitude of things to try to make it work and i have not made any progress over the last six hours.  I post this to you in the hopes that this is a fixable bug.  I look forward to your response.

```
worlds:
  Extra:
    buildChallenge:
      permissions:
      - worldedit.clipboard.(clear|load|rotate|flip|cut|paste)
      - worldedit.(green|help|history.*|navigation.*|selection.*|wand)
      - worldedit.region.(hollow|naturalize|walls|faces|smooth|replace|set|move)
      - worldedit.tool.(farwand|replacer|daga-cycler|smooth)
      - worldedit.(snow|thaw)
      - worldedit.(drain|fill)
      - worldedit.(fixwater|fixlava)
      - plotme.(limit.1|use.(add|auto|biome|clear|home|list|remove))
    Warp:
      permissions:
      - contest.user
      - -modifyworld.blocks.(destroy|place).*
      - modifyworld.damage.(deal|take).*
      - modifyworld.items.(drop|have|hold|pickup).*
      - modifyworld.items.hold.*
      - modifyworld.items.use.*
      - modifyworld.sneak
    Tradepost:
      permissions:
      - essentials.itemdb
      - essentials.kits.Tradepost
      - essentials.signs.(use|break|create).trade
      - itemcase.create.showcase
      - modifyworld.*
      - plotme.(limit.1|use.(auto|biome|clear|home|list))
options:
  rank: '900'
  rank-ladder: '990'
  prefix: '&0(&4D&7ragoknight&0)&7'
inheritance: []
```
