### ISSUE TITLE
modifyworld.blocks.interact.lever doesn't work [V. 1.22.3]

### ISSUE THREAD

**Issue by turbolego** [PEXPlugins/PermissionsEx#1633]
I also have Modifyworld V. 1.19.7 installed.

This is my permissions.yml file:

```
groups:
    default:
        default: true
        options:
        rank: '1000'
        permissions:
        - modifyworld.chat
        - modifyworld.blocks.interact.lever
```

This is the error i get if i try to interact with a lever as "Default" user:

```
You are not permitted to interact with LEVER.
```

Did i do something wrong?
