### ISSUE TITLE
[PermissionsEx 1.22.3] Possible to disable player logging for non-grouped users?

### ISSUE THREAD

**Issue by mibby** [PEXPlugins/PermissionsEx#1639]
@zml2008 

With this set in the config;

```
  log-players: true
```

I noticed my permissions file is being cluttered with users who aren't even grouped. Would it be possible to not log players last login/logout time if they are not grouped by default? This would help tremendously for my large server to prevent an extremely long permissions file, as I only care about users who need to be specifically grouped to something. :(

Example.

```
  a93b4ea4-2a1b-****-9ca6-cb97d2111274:
    options:
      last-login-time: '1408434688'
      last-logout-time: '1408435338'
      name: mibby2
```

Example of someone who is grouped.

```
  5254d1a8-af2f-****-910a-ffacfad8b5ad:
    options:
      last-login-time: '1408414899'
      last-logout-time: '1408415499'
      name: mibby
    group:
    - Member
```
