### ISSUE TITLE
Corrupting it's perms file + failing negative perm

### ISSUE THREAD

**Issue by Per-Thulin** [PEXPlugins/PermissionsEx#1649]
Two major issues for us with v1.22.4. Both issues are good in 1.22.3. Offline mode.

1) it's corrupting permissions.yml. Repeatedly, and pretty fast. Excerpt below. Syntax is ok, it loads, but it's logically wrong. It's putting players inside a player block, and making huge lists of duplicates. My file is 170k when healthy, and dupes data up to 600k in a few hours.

2) A negative perm "-herochat.speak.global" or "-herochat.speak.*" is not respected for our guest group. Debug mode says the perm is true, and so they can speak. It's possible this is caused by the perm file corruption

-- Excerpt --------
 ```
  cfc45270-87ad-3a50-867e-f561c716a34b: &id4298
    group:
    - guest
    options:
      name: VEgettaGaymer
  101590a8-afdb-3d35-9bea-cc61553be6de:
    silvercatz: *id1709
    invot: *id1710
    Light_BRing3R: *id1718
    abec9cd9-257b-353d-8d3a-c101f92f3ec5: *id1719
    PowerMiner: *id1722
    PinkSnapper: *id1723
    Profesionalskit: *id1724
    Ulerx: *id1725
    Tofuman89: *id1726
    Lumine1: *id2027
    russ_al: *id2028
    Lgoddgreat: *id2029
    tobythegreat: *id2030
    profjimbob: *id2031
    TobeyPorK: *id2032
    e2f9ff26-d463-3c41-b3f5-195125f2053f: *id2033
    36b65b90-4fa5-3184-81a7-30974d36d277: *id2044
    c8eac922-8ffc-3602-9da6-da62485720cb: *id2045
    aa17bf97-2259-32d4-a9ab-e022d5a535ff: *id2046
    58ffd0b4-b900-3a07-90b0-192dd0fb66ed: *id2050
    6497b296-06d9-3df5-8ba2-bebe49ec826a: *id2051
    9ea08e78-6a3b-3459-b905-937e8b05d0d7: *id2052
    acf15a73-7423-34d2-9baa-6df386b7145f: *id2053
    9e255bcf-479a-3eb9-99c3-90e4fcbd35fe: *id2054
    2259e385-f5be-3768-adfe-d30ae7b3e142: *id2055
    49ca95de-cc6d-3e26-a724-66920be14eac: *id2056
... snip...
    barixs:
      group:
      - guest
      options:
        name: barixs
    CREEPER1:
      group:
      - guest
      options:
        name: CREEPER1
  02aa1302-ced5-310d-a47f-a89d74d16553:
    options:
      name: pianoaaakkk
 ```
