### ISSUE TITLE
PermissionsEx seems to be ignoring superperms parent nodes

### ISSUE THREAD

**Issue by desht** [PEXPlugins/PermissionsEx#179]
This is my PermissionsEx config.yml:

```
permissions:
    backends:
        file:
            file: permissions.yml
    backend: file
    basedir: plugins/PermissionsEx
    createUserRecords: false
    debug: false
    allowOps: false
    superperms:
        disable-unmatched: false
        enable: true
        matched-permissions: true
        debug: true
        raw-permissions: true
        strict-mode: false
        parent-nodes: true
```

This is a relevant extract from my permissions.yml:

```
users:
    desht:
        group:
        - Default
        worlds:
            world: {}
groups:
    Default:
        default: true
        prefix: '&d'
        permissions:
        - scrollingmenusign.user
```

This is a relevant extract from my plugin's plugin.yml:

```
permissions:
  scrollingmenusign.guest:
    description: Gives access to very basic SMS functionality (no permission elevation)
    children:
      scrollingmenusign.scroll: true
      scrollingmenusign.execute: true
      scrollingmenusign.execute.elevated: false
      scrollingmenusign.use.sign: true
      scrollingmenusign.use.redstone: true
  scrollingmenusign.user:
    description: Gives access to basic SMS functionality
    children:
      scrollingmenusign.guest: true
      scrollingmenusign.execute.elevated: true
  scrollingmenusign.scroll:
    description: Allows menus to be scrolled
    default: true
  scrollingmenusign.execute:
    description: Allows menu items to be executed
    default: true
  scrollingmenusign.execute.elevated:
    description: Allow execution of menu items which bypass permissions checks
    default: true
```

In this case, giving **scrollingmenusign.user** to a player should give them all the child nodes.  But when I call something like player.hasPermission("scrollingmenusign,use.sign"), it's returning false.

Tested with both 1.17 and the latest #309 build.
