### ISSUE TITLE
World specific group prefix not showing / default member group set to "[]"

### ISSUE THREAD

**Issue by WASasquatch** [PEXPlugins/PermissionsEx#1892]
First of all, when users login, they are put into the "[]" group (null array) is that normal? Their permissions seem to work, but it cause a lot of confusion, especially with the next part.

I have added a prefix for a "zombie" world, however, it does not seem to show at all! Any ideas? Hopefully a minor YAML error and not PEX.

Using latest build on Spigot 1.8

````YAML
# Pay CAREFUL attention when editing this file. 
groups:
  default:
    options:
      default: true
      prefix: ''
    permissions:
    - modifyworld.*
    - essentials.ban.notify
    - multiworld.command.spawn
    - worldguard.region.info.own
    - essentials.build.*
    - essentials.balance
    - essentials.pay
    - essentials.pay.multiple
    - essentials.sell
    - essentials.worth
    - essentials.afk
    - essentials.afk.auto
    - essentials.getpos
    - essentials.help
    - essentials.helpop
    - essentials.ignore
    - essentials.itemdb
    - essentials.list
    - essentials.mail
    - essentials.mail.send
    - essentials.me
    - essentials.motd
    - essentials.msg
    - essentials.rules
    - essentials.seen
    - essentials.seen.banreason
    - essentials.spawn
    - essentials.back
    - essentials.delhome
    - essentials.sethome
    - essentials.home
    - essentials.tpa
    - essentials.tpaccept
    - essentials.protect
    - essentials.protect.contact
    - essentials.protect.ownerinfo
    - essentials.signs.color
    - essentials.signs.format
    - essentials.signs.create.disposal
    - essentials.signs.create.time
    - essentials.signs.create.trade
    - essentials.signs.use.disposal
    - essentials.signs.use.sell
    - essentials.signs.use.trade
    - essentials.signs.use.time
    - essentials.signs.use.buy
    - essentials.warp
    - essentials.warps.creative
    - multiworld.creativemode
    - options.blockEnderChestInCrea
    - lwc.protect
    worlds:
      ZombieWorld:
        prefix: '[&2&lZ&r] '
        permissions:
        - zombieondeath.zombiespawn
        - -essentials.back
        - -essentials.back.ondeath
        - crackshot.craft.all
        - crackshot.buy.all
        - crackshot.list
  admin:
    options:
      default: false
      prefix: '[&cAdmin&r] '
    permissions:
    - modifyworld.*
    - worldguard.*
    - worldedit.*
    - essentials.*
    - multiworld.command.list
    - multiworld.command.info
    - multiworld.command.goto
    - multiworld.command.move
    - multiworld.command.spawn
    - multiworld.command.help
    - multiworld.creativemode
    - multiworld.basic
    - options.blockEnderChestInCrea
    - lwc.mod
schema-version: 1
````
