### ISSUE TITLE
PLEASE HELP im using pex before but this one is wierd im using craftbukkit 1.7.10 and pex ver 1.23.1

### ISSUE THREAD

**Issue by hamsterfat** [PEXPlugins/PermissionsEx#1933]
help me its really wierd pex doesnt create config and permissions file help me and i tried to make new one of permssions.yml but doesnt work this is the perm and also im using mutli craft control panel which i cant choose what version shall i use
```yml
groups:
    default:
        options:
            default: true
            rank: '1000'
        permissions:
        - essentials.kits.[Tools]
        - essentials.kits.[Color]
        - essentials.balance
        - essentials.balancetop
        - essentials.balance.others
        - essentials.pay
        - essentials.sell
        - essentials.worth
        - essentials.afk
        - essentials.help
        - essentials.ignore
        - essentials.mail
        - essentials.msg.color
        - essentials.msg
        - essentials.realname
        - essentials.suicide
        - essentials.spawn
        - essentials.delhome
        - essentials.home
        - essentials.sethome
        - essentials.tpa
        - essentials.tpaccept
        - essentials.tpdeny
        - essentials.warp
        - ssentials.afk.auto
        - ssentials.afk
        - essentials.kick.notify
        - essentials.mute.notify
        - essentials.ban.notify
        - auction.bid 
        - auction.start
    Member:
        prefix: '&0(&8M&7ember&0)&7 '
        permissions:
        - essentials.afk.kickexempt
        - essentials.workbench
        - essentials.nick
        - essentials.nick.format
        - essentials.nick.magic
        options:
            rank: '900'
    VIP:
        prefix: '&0(&eVIP&0)&7 '
        inheritance:
        - Member
        permissions:
        - essentials.recipe
        - essentials.enderchest
        - essentials.keepxp
        options:
            rank: '800'
    Cop:
        prefix: '&0(&1Cop&0)&7 '
        inheritance:
        - VIP
        permissions:
        - essentials.sethome.multiple.unlimited
        - essentials.chat.color
        - essentials.kits.[Dtools]
        options:
            rank: '100'
    Admins:
        prefix: '&0(&4Admins&0)&7 '
        inheritance:
        - Cop
        permissions:
        - essentials.kits.*
        - essentials.fly
        - essentials.gamemode
        - essentials.jails
        - essentials.kick
        - essentials.mute
        - essentials.tempban
        - essentials.unban
        - essentials.tp
        - essentials.clearinventory.all
        options:
            rank: '10'   
    Coowner:
        prefix: '&0(&4Co-Owner&0)&7 '
        inheritance:
        - Admin
        permissions:
        - essentials.weather
        - essentials.banip
        - essentials.broadcast
        options:
            rank: '5'
    Owner:
        prefix: '&0(&4Owner&0)&7 '
        permissions:
        - '*'
        options:
            rank: '1'
users:
    hamsterfat:
        group:
        - Owner
```
