### ISSUE TITLE
Pex, SQL Database Setup

### ISSUE THREAD

**Issue by WabMiran** [PEXPlugins/PermissionsEx#1988]
Hello, Im Trying To Setup SQL But The Servers Dont Sync with each other,
CONFIG:
---------------
```yaml
multiserver:
  use-netevents: true
permissions:
  debug: false
  allowOps: false
  user-add-groups-last: false
  log-players: false
  createUserRecords: false
  backend: sql
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
  backends:
    file:
      type: file
      file: permissions.yml
    sql:
      type: sql
      uri: mysql://66.81.144.162/mcph396590
      user: mcph196590
      password: (im leaving this blank For Security )
      aliases:
        permissions: pex_permissions
        permissions_inheritance: pex_inheritance
        permissions_entity: pex_entity
updater: true
alwaysUpdate: false
```
-----------
Please Help!
