### ISSUE TITLE
PEx Error

### ISSUE THREAD

**Issue by Intar21** [PEXPlugins/PermissionsEx#2097]
### Description ###

"java.lang.RuntimeException:	Default user group is not defined. Please select one using the "default: true" property"

### Detailed Information ###

[Is available here](https://gist.github.com/cb5bc15dc343f71f05ab)
.

**Comment by Stormbow** [comment]
Correct your config.yml file to look like [this example](http://pastebin.com/fScNAXfx).

Does the error remaine?

**Comment by Intar21** [comment]
Yes... Still the same

**Comment by Stormbow** [comment]
You made the permissions.yml correction too?

**Comment by Intar21** [comment]
Which correction ? Here is my actual permissions.yml : http://pastebin.com/rg8Zf96B

**Comment by Stormbow** [comment]
Line 7: replace quotation marks with apostrophes.

**Comment by Intar21** [comment]
Oh sorry I didn't read this part of the message, but it still doesn't work.

**Comment by Stormbow** [comment]
Notice you don't have a schema-version: 1 line.

**Comment by Intar21** [comment]
Still that : https://gist.github.com/3f9f1284b5ace2844aff

**Comment by Stormbow** [comment]
```
groups:
  Visiteur:
    options:
      rank: '1000'
      default: true
    permissions:
    - '*'
schema-version: 1
users:
  Intar21:
    group:
    - Visiteur
```
