### ISSUE TITLE
Deploying default database scheme even if it already exists

### ISSUE THREAD

**Issue by TechieCrow** [PEXPlugins/PermissionsEx#2226]
Hey I'm using the latest released version of PEX and Spigot 1.8.8 but for some reason PEX always deploys the default scheme even though it exists overwriting the default group every time the server restarts, everything works fine before restarting the server and it works if I don't use aliases.

23:50:31 PermissionsEx-SQL: Connecting to database "mysql://<host>/<database>"
23:50:32 PermissionsEx-SQL: Successfully connected to database
23:50:32 CONSOLE: [INFO] Deploying default database scheme
23:50:32 CONSOLE: [INFO] Database scheme deploying complete.

Config:

``` yaml
multiserver:
  use-netevents: true
permissions:
  debug: false
  allowOps: false
  user-add-groups-last: false
  log-players: false
  createUserRecords: false
  backend: sql
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
  backends:
    file:
      type: file
      file: permissions.yml
    sql:
      uri: mysql://IP/DBNAME
      user: USERNAME
      password: PASSWORD
      type: sql
      aliases:
        permissions: 1.8survival_permissions
        permissions_inheritance: pex_inheritance
        permissions_entity: pex_entity
updater: false
alwaysUpdate: false
```

I read this was suppose to be fixed in version 1.21 so my guess is I messed something up in the config but I can't figured out what.
