### ISSUE TITLE
What i did wrong here?

### ISSUE THREAD

**Issue by AndrewUH** [PEXPlugins/PermissionsEx#2338]
```yaml
groups:
  Member:
    prefix: '&e[Member]'
    options:
      default: true
    permissions:
    - bukkit.command.help
    - bukkit.command.tell
    - bukkit.broadcast
    - ultracosmetics.gadgets.*
    - ultracosmetics.pets.*
    - ultracosmetics.mounts.*
    - ultracosmetics.hats.*
    - ultracosmetics.particleeffects.*
    - ultracosmetics.suits.*
    - multicurrency.info
    - multicurrency.exchange
  Owner:
    prefix: '&1&l[Owner]&6&f'
    permissions:
    - '*'
    inheritance: []
schema-version: 1
```
