### ISSUE TITLE
modifyworld.chat.private doesn't work

### ISSUE THREAD

**Issue by Shamaoke** [PEXPlugins/PermissionsEx#235]
Hi.

The `modifyworld.chat.private` rule doesn't allow me to post private messages using `tell`. What can be the reason of the problem? Thanks.

**PermissionEX/permissions.yml**

```
groups:
    visitors:
        options:
            rank: '1000'
        default: true
        permissions:
        - modifyworld.login
    users:
        inheritance:
        - visitors
        options:
            rank: '900'
        permissions:
        - modifyworld.chat # works
        - modifyworld.chat.private # doesn't work
users:
    me:
        group:
        - users
```
