### ISSUE TITLE
Feature: more specific settings for pex notifications

### ISSUE THREAD

**Issue by leasoncre** [PEXPlugins/PermissionsEx#2354]
IE:
config options of pex notifications are quite broad and all-encompassing (if used, who wants this?)
change up the config settings a little bit for some more specific allowances of notifications:

```
  informplayers:
    ##WithPermissionOnly: only notifies the player if "permissions.notify.[configoption]", this would ignore the config options that follow this one.
    withpermissionsonly: true

    ##notify only x user when x user's group has changed "permissions.notify.groups.self"
    groupsself: true
    ##notify all OP players and those with "permissions.notify.group.all" when any user's groups have changed
    groupall: false
     ##notify only x user when x user's permissions has changed "permissions.notify.perms.self"
    permsself: true
    ##notify only x user when x user's group has changed "permissions.notify.perms.all"
    permsall: false
```

permissions-specific example: you'd have to add the permission node to the user/group(inheritance) to receive notifiacations
