### ISSUE TITLE
Default Ranks (per world) not applying

### ISSUE THREAD

**Issue by philip-ulrich** [PEXPlugins/PermissionsEx#2387]
Howdy Y'all,

I'm using the latest spigot (1.9.2) build and pex 1.23.4. 

I have the following groups set up:
http://d.l33t.tech/uPUv/5rYZALBL

and when I join the worlds listed there... pex lists them.. but they do not apply to any users:
http://d.l33t.tech/13cCI/2KZPBA7v

Please assist! :)

**Comment by zml2008** [comment]
Based on previous reports, there are some issues with per-world permissions on spigot 1.9. The spigot folks say the issue isn't on their side though, so we're still trying to pin down the exact cause of these issues.

**Comment by philip-ulrich** [comment]
Bugger. Alright. Hope we can get this fixed soon. 👍

**Comment by SkydeFR** [comment]
I'm using PermissionsEx v1.22.10 with KCauldron 1.7.10 and I'm the same problem : default rank not applying to new players

simplified version of my permissions.yml :
```
groups:
  Ombre:
    default: true
    permissions:
    - essentials.help
    inheritance: []
    options:
      rank: '1000'
      rank-ladder: global
  Arrivant:
    permissions:
    - essentials.home
    inheritance:
    - Ombre
    options:
      rank: '990'
      rank-ladder: global
schema-version: 1
users:
  21d68a0d-15c8-432a-8e30-aa77d2e0bb4c:
    options:
      name: SkydeFR
```

**Comment by zml2008** [comment]
@SkydeFR you have a different problem: the `default` line is an option, not at the top level.

**Comment by SkydeFR** [comment]
@zml2008 Sorry I didn't know, should I open a new ticket?

**Comment by philip-ulrich** [comment]
@SkydeFR No, you just need to move it down:

```
groups:
  Ombre:
    permissions:
    - permissions.ombre
    inheritance: []
    options:
      rank: '1000'
      rank-ladder: global
      default: true
```
