### ISSUE TITLE
I can't add more then 1 group, because then the plugin won't work..

### ISSUE THREAD

**Issue by CelestialSatyr** [PEXPlugins/PermissionsEx#2399]
Hello.
I've encountered an issue.
I tried to configure PEX, (i have done this before, and it worked back then)
I tried to add multiple groups, but i can't add more then 1 group, (the default one) or else it wouldn't work..

Can someone please help?!

This is the permissions.yml i'm using:
```yaml
groups:
    Default:
        options:
            default: true
            prefix: '&e[&6Default&e] '
        permissions:
        - modifyworld.*
```

and this will work, it will show to prefix and PEX won't crash..

But when i try to add another group.. it crashes and it won't work?
This is my permissions.yml then:

```yaml
groups:
    Default:
        options:
            default: true
            prefix: '&e[&6Default&e] '
        permissions:
        - modifyworld.*
    Admin:
        options:
            default: false
            prefix: '&e[&6Admin&e] '
        permissions:
        - modifyworld.*
```

Can someone please help me?
