### ISSUE TITLE
SQL Backend Error returns

### ISSUE THREAD

**Issue by tricky538** [PEXPlugins/PermissionsEx#2423]
One my last issue. i got this. I changed it in de config but when restarting the node it adds the file at the bottom of the backend under the sql backend and doesnt follow the sql backend

**Comment by zml2008** [comment]
You have to have the `type: sql` line in the SQL backend section for it to be read as an sql backend.

**Comment by zml2008** [comment]
Don't make new issues, just respond to the existing one...

You entirely ignored what I said. Your SQL section should look like:

```yaml
backends:
    sql:
      type: sql
      uri: mysql://{DATABASE_IP}/{DATABASE}
      user: {USERNAME}
      password: {PASSWORD}
      aliases:
        permissions: pex_permissions
        permissions_inheritance: pex_inheritance
        permissions_entity: pex_entity
```

and later in your config file you should have:

```yaml
backend: sql
```
