### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by tricky538** [PEXPlugins/PermissionsEx#2425]
This is the config before restart
```yaml
  backends:
    sql:
      uri: mysql://{DATABASE_IP}/{DATABASE}
      user: {USERNAME}
      password: {PASSWORD}
      aliases:
        permissions: pex_permissions
        permissions_inheritance: pex_inheritance
        permissions_entity: pex_entity
```

AFTER:
```yaml
  backends:
    sql:
      uri: mysql://{DATABASE_IP}/{DATABASE}
      user: {USERNAME}
      password: {PASSWORD}
      aliases:
        permissions: pex_permissions
        permissions_inheritance: pex_inheritance
        permissions_entity: pex_entity
    file:
      type: file
      file: permissions.yml
```

It doenst go onto the database when changing rank of player
