### ISSUE TITLE
createUserRecords not saving default groups to user?

### ISSUE THREAD

**Issue by Tyloonie** [PEXPlugins/PermissionsEx#2464]
Hi PEX,

I have in all ways tried to make PEX save users, who are still in the default group - but without having to manually add them to a group my self.

I tried using the createUserRecords, but after relogging this is what it turned out as.

```yaml
0ce4e7f1-87bd-42d8-82cf-d0a05fd0fbb5:
    group: []
    options:
      name: Tyloonie
```

As you can see, it does not save the default group to the player. Only UUID and Name. 
I do not know if this is a bug, but I think the feature to save default groups should really be added to PEX.

Maybe I've just missed a setting somewhere in the config?
```yaml
multiserver:
  use-netevents: true
permissions:
  debug: false
  allowOps: false
  user-add-groups-last: false
  log-players: false
  createUserRecords: true
  backend: file
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
  backends:
    file:
      type: file
      file: permissions.yml
updater: true
alwaysUpdate: false
```

Your guide on how to set up the config.yml (https://github.com/PEXPlugins/PermissionsEx/wiki/Plugin-Configuration) also seems a bit outdated. The "log-players" function is not even in there yet and it does not explain what createUserRecords does.

So, how is it possible to save players, who are only in the default group in the permissions.yml - WITH THE GROUP? 

Thank you very much, Gentlemen.
