### ISSUE TITLE
Pex dump to SQL doesnt dump per-world prefixes

### ISSUE THREAD

**Issue by G-m-K** [PEXPlugins/PermissionsEx#247]
Excerpt of perm file:

```
Controller:
    inheritance:
    - VetOp
    options:
        rank: '500'
    permissions:
    - all sorts of permissions
    worlds:
        spawn:
            permissions: []
            prefix: '&f[&bAB&f]&b '
        main:
            permissions: []
            prefix: '&f[&bXY&f]&b '
        creative:
            permissions: []
            prefix: '&f[&bFG&f]&b '
        hc:
            permissions: []
            prefix: '&f'
```

^ Those per world prefixes arent converted when doing a pex dump to sql.

Thanks!
