### ISSUE TITLE
Pex 2.0 not starting up

### ISSUE THREAD

**Issue by Ironic8b498** [PEXPlugins/PermissionsEx#2492]
pex 2.0 not loading on my spigot 1.10.2 server got error in logs:
http://pastebin.com/zdFGMKy1

Got other errors with Essentials-2.x-SNAPSHOT-#13 and EssentialsChat-2.x-SNAPSHOT-#13;
http://pastebin.com/My6gZkg6

**Comment by Stormbow** [comment]
PEX 2.x is not for Spigot.  It's for Forge/Sponge.

**Comment by zml2008** [comment]
There actually is a build of PEX2.0 for spigot, but it's not really ready for general use yet. It seems like you have an issue with the backend setup in your PEX config as well. To use Essentials, you need to use a recent build of EssentialsX that has been updated to also handle PEX 2.x.

**Comment by Ironic8b498** [comment]
I was using permissionsex-bukkit-2.0-SNAPSHOT-shaded-#136 even without essential installed it still wouldn't load

**Comment by zml2008** [comment]
Pastebin your config.yml for PEX, there is an error there.

**Comment by Ironic8b498** [comment]
since its a fresh install I would not think there was.
http://pastebin.com/vhWrv0EV

**Comment by zml2008** [comment]
Nope, you have made changes to the backends section and it is very wrong. Here's a corrected configuration file:
```yaml
multiserver:
  use-netevents: true
permissions:
  debug: ture
  allowOps: false
  user-add-groups-last: false
  log-players: false
  createUserRecords: false
  backend: flat
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
  backends:
    sql:
      type: sql
      url: mysql://mcaaron:MissPiggy69@localhost/pex_minecraft
    flat:
      type: file
      file: permissions.yml
updater: true
alwaysUpdate: false
```

This configuration file is still in a 1.x format, but it is more correct (note the backends section), so updates can actually happen now.
