### ISSUE TITLE
Pex auto sets 2nd Group to player

### ISSUE THREAD

**Issue by Tabonosh** [PEXPlugins/PermissionsEx#2549]
I just made a new Permissions group and it auto sets it to the 2nd group
so if you joined your rank would be whatever rank is in the second spot.
Help?
My pex file:
```yaml
groups:
  default:
    options:
      default: true
    permissions:
    - modifyworld.*
  beam:
    options:
      default: true
      prefix: '&3&lBEAM '
    permissions:
    - modifyworld.*
  youtube:
    options:
      default: true
      prefix: '&c&lYOU&f&lTUBE '
    permissions:
    - modifyworld.*
  owner:
    options:
      default: false
      prefix: '&9&lOWNER '
      suffix: '&7[&d&oaesthetic&7]'
    permissions:
    - '*'
```
