### ISSUE TITLE
not recognizing child node for openwarp

### ISSUE THREAD

**Issue by aaronmallen** [PEXPlugins/PermissionsEx#255]
I am trying to figure out how to write this out correctly.  The node is: 

openwarp.warp.delete

but it has 3 options:
openwarp.warp.delete.private
openwarp.warp.delete.public.self
openwarp.warp.delete.public.other

PermEX recognizes if I set a user to warp delete but it won't recognize any of the option modes... here is how I have it set-up:

```
Member:
    inheritance:
    - default
    options:
        rank: '900'
    permissions:
    - openwarp.warp.set
    - openwarp.warp.delete.private
```

can you help me trouble shoot this? I know it's probably something stupid simple like improper parent vs. child node syntax but I have been on this for 3 days and can't figure it out.  Thanks guys love your plugin!
