### ISSUE TITLE
Config Help?

### ISSUE THREAD

**Issue by Loonyy** [PEXPlugins/PermissionsEx#2592]
Hey, I'm recently trying to convert from Group Manager to PEX but I'm having some issues. 
What I have set up is my ranks with Squire as the default rank. Squire has overall permissions under 'permissions' which means they should get those permissions in every world correct? 
Then, they have added permissions for other worlds and then every group inherits Squire. 

The issue I'm having is that some permissions will work and some won't. For example, Squire can do /seen but not /mail. They can do /warp arena but not /warps, even though they have permission to do everything?

Here's my config:
```
groups:
  Squire:
    options:
      default: true
      prefix: '&a⊰Squire⊱ &f'
    permissions:
    - enjin.points.getself
    - essentials.ban.notify
    - essentials.chat.url
    - essentials.delhome
    - essentials.home
    - essentials.warp
    - essentials.msgtoggle
    - essentials.mute.notify
    - essentials.seen
    - essentials.seen.banreason
    - essentials.warps.arena
    - essentials.warps.Change
    - essentials.warp
    - essentials.warps.Choose
    - essentials.warps.jail
    - essentials.warps.plotme
    - essentials.warps.shop
    - essentials.warps.spawn
    - essentials.warps.Tournament
    - essentials.warps.tutorial
    - essentials.warps.wild
    - essentials.warps.list
    - essentials.warps.jail
    - jobs.autojoin.miner
    - serversigns.use.*
    - essentials.signs.use.buy
    - essentials.signs.use.disposal
    - essentials.signs.use.warp
    worlds:
      world:
        permissions:
        - bending.ability.airjump
        - chatreaction.top
        - chatreaction.wins
        - chatreaction.wins.other
        - echopet.pet
        - echopet.pet.call
        - echopet.pet.hat.*
        - echopet.pet.hide
        - echopet.pet.info
        - echopet.pet.list
        - echopet.pet.menu
        - echopet.pet.name
        - echopet.pet.remove
        - essentials.warp
        - echopet.pet.ride.*
        - echopet.pet.show
        - echopet.pet.type.pig
        - essentials.kit
        - essentials.kits.Squire
        - essentials.signs.break.disposal
        - essentials.signs.color
        - essentials.signs.create.disposal
        - essentials.signs.format
        - essentials.signs.magic
        - essentials.signs.use.balance
        - essentials.signs.use.kit
        - essentials.signs.use.mail
        - present.claim
        - virtualshops.commands.additem
        - virtualshops.commands.addstock
        - virtualshops.commands.buy
        - virtualshops.commands.create
        - virtualshops.commands.delete
        - virtualshops.commands.deleter
        - virtualshops.commands.disable
        - virtualshops.commands.list
        - virtualshops.commands.removeitem
        - virtualshops.commands.rename
        - virtualshops.commands.sell
        - virtualshops.commands.sellall
        - virtualshops.commands.show
        - virtualshops.commands.stats
        - virtualshops.commands.top
        - virtualshops.creation
        - virtualshops.interact
        - virtualshops.interaction
        - virtualshops.interaction.*
      spawn:
        permissions:
        - multiverse.portal.access.*
        - multiverse.portal.access.A
        - multiverse.portal.access.AC
        - multiverse.portal.access.AS
        - multiverse.portal.access.ba
        - multiverse.portal.access.bc
        - multiverse.portal.access.be
        - multiverse.portal.access.bf
        - multiverse.portal.access.bw
        - multiverse.portal.access.C
        - multiverse.portal.access.c
        - multiverse.portal.access.CC
        - multiverse.portal.access.CS
        - multiverse.portal.access.E
        - multiverse.portal.access.e
        - multiverse.portal.access.EC
        - multiverse.portal.access.ES
        - multiverse.portal.access.F
        - multiverse.portal.access.FC
        - multiverse.portal.access.FS
        - multiverse.portal.access.W
        - multiverse.portal.access.w
        - multiverse.portal.access.WC
        - multiverse.portal.access.WS
        - essentials.warps.air
        - essentials.warps.water
        - essentials.warps.chi
        - essentials.warps.earth
        - essentials.warps.fire
      arena:
        permissions:
        - -mcmmo.defaults
      herobend:
        permissions:
        - -mcmmo.defaults
      plotworld:
        permissions:
        - plotme.limit.1
        - plotme.use
        - plotme.use.add
        - plotme.use.remove
        - -mcmmo.defaults
        - essentials.skull
        - essentials.skull.others
        - essentials.skull.spawn
  Jester:
    options:
      default: false
      prefix: '&7⊰Jester⊱ &f'
    worlds:
      world:
        permissions:
        - disguisecraft.mob.pig
        - disguisecraft.mob.villager
        - disguisecraft.seer
        - echopet.pet.type.chicken
        - essentials.back
        - essentials.back.ondeath
        - essentials.kits.Jester
        - essentials.nick
        - essentials.recipe
        - libsdisguises.disguise.pig
        - libsdisguises.disguise.villager
        - libsdisguises.undisguise
    inheritance:
    - Squire
  Knight:
    options:
      default: false
      prefix: '&d⊰Knight⊱ &f'
    worlds:
      world:
        permissions:
        - echopet.pet.type.cavespider
        - essentials.back.ondeath
        - essentials.feed
        - essentials.hat
        - essentials.kits.Knight
        - essentials.sethome.multiple.hero
        - essentials.workbench
        - libsdisguises.disguise.blaze
        - libsdisguises.disguise.chicken
        - libsdisguises.disguise.creeper
        - libsdisguises.disguise.sheep
      plotworld:
        permissions:
        - plotme.limit.2
    inheritance:
    - Squire
    - Jester
  Priest:
    options:
      default: false
      prefix: '&5&o⊰Priest⊱ &f'
    worlds:
      world:
        permissions:
        - echopet.pet.type.cow
        - essentials.chat.color
        - essentials.kits.Priest
        - essentials.sethome.multiple.royalty
        - essentials.workbench
        - libsdisguises.disguise.pigzombie
        - libsdisguises.disguise.skeleton
        - libsdisguises.disguise.wolf
        - libsdisguises.disguise.zombie
      plotworld:
        permissions:
        - plotme.limit.4
    inheritance:
    - Squire
    - Jester
    - Knight
  Regent:
    options:
      default: false
      prefix: '&3&o⊰Regent⊱ &f'
    worlds:
      world:
        permissions:
        - echopet.pet.type.creeper
        - essentials.chat.color
        - essentials.enderchest
        - essentials.kits.Regent
        - essentials.sethome.multiple.avatar
        - essentials.workbench
        - libsdisguises.disguise.cavespider
        - libsdisguises.disguise.enderman
        - libsdisguises.disguise.rabbit
        - libsdisguises.disguise.squid
        - libsdisguises.disguise.wither
      plotworld:
        permissions:
        - plotme.limit.6
    inheritance:
    - Squire
    - Jester
    - Knight
    - Priest
  Prince:
    options:
      default: false
      prefix: '&c&o⊰Prince⊱ &f'
    worlds:
      world:
        permissions:
        - creativegates.create
        - echopet.pet.type.enderman
        - essentials.kits.Prince
        - essentials.nick.color
        - essentials.sethome.multiple.emperor
        - libsdisguises.disguise.blaze
        - libsdisguises.disguise.ender_dragon
        - libsdisguises.disguise.horse
        - libsdisguises.disguise.slime
        - libsdisguises.disguise.witch
        - libsdisguises.disguise.wolf
        - libsdisguises.disguiseblaze
      plotworld:
        permissions:
        - plotme.limit.12
        - worldedit.brush.smooth
        - worldedit.brush.sphere
        - worldedit.clipboard.clear
        - worldedit.clipboard.copy
        - worldedit.clipboard.flip
        - worldedit.clipboard.paste
        - worldedit.clipboard.rotate
        - worldedit.generation.cylinder
        - worldedit.generation.pyramid
        - worldedit.generation.sphere
        - worldedit.help
        - worldedit.history.redo
        - worldedit.history.undo
        - worldedit.navigation.thru.command
        - worldedit.region.center
        - worldedit.region.overlay
        - worldedit.region.replace
        - worldedit.region.set
        - worldedit.region.smooth
        - worldedit.region.walls
        - worldedit.replacenear
        - worldedit.selection.pos
        - worldedit.tool.replacer
        - worledit.clipboard.cut
    inheritance:
    - Squire
    - Jester
    - Knight
    - Priest
    - Regent
  King:
    options:
      default: false
      prefix: '&f&l&o⊰&9&l&oKing&f&l&o⊱ &f'
      permissions:
      - bending.ability.LoonyBlast
      - ElementumCore.JoinMessage.Emperor
    worlds:
      world:
        permissions:
        - echopet.pet.type.bat
        - essentials.kits.Emperor
        - essentials.near
        - essentials.near.others
        - essentials.sethome.multiple.emp
      plotworld:
        permissions:
        - plotme.limit.15
    inheritance:
    - Squire
    - Jester
    - Knight
    - Priest
    - Regent
    - Prince
schema-version: 1
users:
  332479b8-4578-4554-a6c9-a3218fd7001c:
    options:
      name: jaylo_o
  623df34e-9cd4-438d-b07c-1905e1fc46b6:
    options:
      name: Loonyy
    group:
    - Squire
```
