### ISSUE TITLE
Pex Is not working 

### ISSUE THREAD

**Issue by Wubzel** [PEXPlugins/PermissionsEx#2672]
I have no idea whats wrong and its driving me crazy please help

permissions.yml:
```yaml
groups:
  Member:
    options:
      default: true
      prefix: '&2[Member]   '
    permissions:
    - modifyworld.*
    - essentials.home*
    - essentials.msg
    - essentials.warp
    - essentials.kit
    - essentials.afk
    - essentials.tpa*
    - essentials.buy*
    - essentials.sell*
  Moderator:
    options:
      prefix: '&2[&5Moderator&2]   '
    permissions:
    - essentials.kick
    - essentials.fly
    - essentials.feed
    - essentials.heal
    - essentials.mute
    - essentials.tempban
    - modifyworld.*
    - essentials.home*
    - essentials.msg
    - essentials.warp
    - essentials.kit
    - essentials.afk
    - essentials.tpa*
    - essentials.buy*
    - essentials.sell*
  Op:
    options:
      prefix: '&l&n&c{&bOp&c}   '
    permissions:
    - essentials.gamemode*
    - essentials.item
    - essentials.give
    - essentials.god
    - essentials.vanish
    - essentials.teleport
    - essentials.tp
    - essentials.recipe
    - essentials.kick
    - essentials.fly
    - essentials.feed
    - essentials.heal
    - essentials.mute
    - essentials.tempban
    - modifyworld.*
    - essentials.home*
    - essentials.msg
    - essentials.warp
    - essentials.kit
    - essentials.afk
    - essentials.tpa*
    - essentials.buy*
    - essentials.sell*
  Owner:
    options:
      prefix: '&l&m&n&3{&2Owner&3}   '
    permissions:
    - '*'
schema-version: 1
users:
  f485bddf-bb0a-4fe9-896d-9163fba872d8:
    group:
    - Owner
    options:
      name: Wubzel
  0c14a097-5154-4ebf-91a3-c5853a5250da:
    group:
    - Op
    options:
      name: Hero_of_Blocks04
  afb6d14c-7951-466a-a1f9-495fda9934f3:
    group:
    - Owner
    options:
      name: hawx8
  37699fbb-ec60-4ee8-b569-75e7d21662ae:
    group:
    - Owner
    options:
      name: RIHLEYGOD
  53c5f481-05e9-4d94-9bd3-46c10b2f666e:
    group:
    - Op
    options:
      name: LightningPlayzMC
  99ac14a5-9bc5-4c3b-91fd-b602e2c601bd:
    group:
    - Op
    options:
      name: NuclearPlayzGame
  c7b469da-911f-4063-a8f6-accbc324028a:
    group:
    - Owner
    options:
      name: skittlemaniacpro
      group:
    - Owner
```
