### ISSUE TITLE
PEX removes the default group every 24h using MySQL

### ISSUE THREAD

**Issue by HaNiTLG** [PEXPlugins/PermissionsEx#2685]
Hey guys!
I have a problem. I do not know why but the plugin PermissionsEx removes every 24H the default group. :(
I am using the MySQL backend and I have multiple server.

Here is my config.yml file:
```yaml
permissions:
  backend: sql
  backends:
    sql:
      uri: mysql://127.0.0.1/PermissionsEx
      user: admin
      password: *******************************************
      type: sql
  debug: false
  allowOps: false
  user-add-groups-last: false
  log-players: false
  createUserRecords: false
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
multiserver:
  use-netevents: true
updater: true
alwaysUpdate: false
```

All other groups are fine. They do not get removed. 

Spigot version:

git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

PermissionsEx version: 1.23.4

 

I hope that you can help me! :)

Best greets,
HaNiTLG :)
