### ISSUE TITLE
[PEX 1.x] [Bungeecord] Player is kicked immediately after joining the server

### ISSUE THREAD

**Issue by TheRealGuru** [PEXPlugins/PermissionsEx#2692]
Hi,

I am seemingly getting the following error and have debuged and fully worked out the cause for it.
`Internal Exception: java.io.IOException: Error while write(...): Connection reset by peer`

Anytime some one connects to the server that has the '*' permission they are kicked with this message. I believe the bit that connects them is when a call to hasPermission is used, but I cannot confirm that. Regardless, it is a lot of work to find every single permission I node I need to give.

As seen in the config however, it appears that node.* still works. 

Minecraft Version 1.11.2
Pex version: 1.23.4
Spigot - Latest build 1.11.2 11th February. 

Pex config that failed:

```
groups:
  default:
    options:
      default: true
    permissions:
    - modifyworld.*
  LeadDeveloper:
    options:
      prefix: '&1[&3Hi&1]'
    permissions:
    - '*'
schema-version: 1
users:
  edcd76de-32ed-446f-ada9-42f1ea9c7d25:
    group:
    - LeadDeveloper
    options:
      name: passy999
```

Hopefully this helps.
