### ISSUE TITLE
PEX not adding new players to the default group.

### ISSUE THREAD

**Issue by AncientTom** [PEXPlugins/PermissionsEx#2733]
I am trying to set up a uSkyblock server and having many problems to get things working right.

The first one I am trying to fix is an issue with PEX which created a new permissions.yml file but will not add the default group to new users that are joining the game.  I am told that this is normal behavior for PEX because PEX automatically gives the default group permissions to users that are not assigned to a group. New players come into the game and cannot do anything because they have no permissions.

config.yml:
```
multiserver:
  use-netevents: true
permissions:
  debug: false
  allowOps: true
  user-add-groups-last: false
  log-players: false
  createUserRecords: true
  backend: file
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
  backends:
    file:
      type: file
      file: permissions.yml
updater: true
alwaysUpdate: false

```
My permissions.yml:
```
groups:
  default:
    options:
      default: true
    permissions:
    - modifyworld.*
schema-version: 1
users:
  b0d44a49-5355-4ee4-afcd-9254713506b3:
    group: []
    options:
      name: AncientTom
  6e0596e2-6344-4fb4-abf8-52358edfe246:
    group: []
    options:
      name: THX138

```
The first and most obvious thing that I checked was to make sure that default: was set to true. Also, I went as far as to remove the permissions file and let PEX rewrite a default file and PEX automatically created the default group with "options: default: true" (without quotes) which still didn't work. I removed the "default: true" line from the file. Then, inside the game, I set the default group as default. PEX put the "default: 'true'" back into the file (this time PEX used single quotes). This didn't work either. It seems that the argument over whether PEX needs a string or a boolean value here is not an issue since PEX itself uses both in this case.

Below is some Info that may be pertinent.
    Server jar: spigot-1.11.2.jar
    PEX version: PermissionsEx-1.23.4.jar
    Plugins used:
	    EssentialsX-2.0.1
	    EssentialsXAntiBuild-2.0.1
	    EssentialsXChat-2.0.1
	    EssentialsXGeoIP-2.0.1
	    EssentialsXProtect-2.0.1
	    EssentialsXSpawn-2.0.1
	    Modifyworld
	    Multiverse-Core-2.5-b717
	    Multiverse-NetherPortals-2.5
	    Multiverse-Portals-2.5
	    PermissionsEx-1.23.4
	    uSkyBlock
	    Vault
	    worldedit-bukkit-6.1.5
	    worldguard-6.2​

I have been a PEX user since 2012 and this is the first time I have had this problem.

Thanks for any and all help.
