### ISSUE TITLE
Get All Perms

### ISSUE THREAD

**Issue by Techno3600** [PEXPlugins/PermissionsEx#2770]
Hello,

Is it possible that I can get every permission in-game and do /effects and /give without being opped?
Don't you have to do something like '-Permissions.*'?

**Comment by EmanYm** [comment]
What version of PEX are you using?  2.0 or 1.23.4?

**Comment by Stormbow** [comment]
> Hello,

> Is it possible that I can get every permission in-game and do /effects and /give without being opped?
Don't you have to do something like '-Permissions.*'?

Yes.  In PEX 1.23.4, this is done with a negation above a "global wildcard":

```
groups:
  Guest:
    options:
      build: true
      prefix: '[Guest] '
      suffix: ''
    inheritance: []
    permissions:
    - -permissions.*
    - '*'
schema-version: 1
users:
````

For a full list of PEX-related `options:`, see [this example](https://pastebin.com/8ZSHxauG).
