### ISSUE TITLE
pex crashing...

### ISSUE THREAD

**Issue by MilPlayz** [PEXPlugins/PermissionsEx#2781]
### Description ###

Pex crahses all the time when i do any command...

my perms.yml file : 
```
groups:
  Rookie:
    prefix: '&7[Rookie] '
    options:
      weight: '1'
  Knight:
    prefix: '&f[&6Knight&f] '
    options:
      weight: '2'
    inheritance:
    - Rookie
  Champion:
    prefix: '&f[&5Champion&f] '
    options:
      weight: '3'
    inheritance:
    - Knight
  Gamer:
    prefix: '&0[&aGamer&0] &f'
    options:
      weight: '4'
    inheritance:
    - Champion
  Recruit:
    options:
      weight: '10'
    inheritance:
    - MasterBlack
  Mod:
    options:
      weight: '100'
    inheritance:      
    - Recruit
  Builder:
    options:
      weight: '150'
    inheritance:      
    - MasterBlack
  MiniYT:
    options:
      weight: '50'
    inheritance:      
    - MasterBlack
  YT:
    options:
      weight: '100'
    inheritance:      
    - MiniYT
  YTPlus:
    options:
      weight: '100'
    inheritance:      
    - YT
  Admin:
    options:
      weight: '500'
    inheritance:      
    - YTPlus
    - Mod
  Owner:
    options:
      weight: '1000'
    inheritance:      
    - Admin
  Nerd:
    options:
      weight: '100000'
    inheritance:      
    - Owner
  MasterWhite:
    prefix: '&f&l[&b&lMaster&f&l] &f'
    options:
      weight: '5'
    inheritance:
    - Gamer
  MasterBlack:
    prefix: '&0&l[&b&lMaster&0&l] &f'
    options:
      weight: '5'
    inheritance:
    - Gamer
users:
  MilPlayz:
    permissions:
    - '*'
    group:
    - Nerd
```

### Detailed Information ###

[Is available here](https://gist.github.com/6c59ed22ff2ba4f1f3ea69374437735b)

**] Edit by Stormbow: corrected markdown code. [**
