### ISSUE TITLE
Worlds inheritance

### ISSUE THREAD

**Issue by bbruno5** [PEXPlugins/PermissionsEx#2808]
I have a problem with some permission plugins. When set worlds, if I try inheritance in indent of world, some perms, don't work on that world, like essentials perms and legendchat.

The inheritance works for some perms like marry, but not for others like essentials or legendchat. The problem is solved if I add the perms that don't work, to that world (creative), but I don't want to repeat the perms on all worlds :/ .
Here is a link from pastebin with my permissions.yml:

https://pastebin.com/tzp3ysrs

**Comment by Stormbow** [comment]
What are all of the names of the worlds on your server?

**Comment by bbruno5** [comment]
criativo, lobby, loja, mine, world, world_nether, world_the_end.
All selected on print.

![image](https://cloud.githubusercontent.com/assets/23748196/26715672/fbad3a22-474c-11e7-8584-d784e70a7cc9.png)

**Comment by Stormbow** [comment]
Ok.  Give me a few minutes and I'll make you a template to work from.

**Comment by Stormbow** [comment]
Take a look at [this example](https://pastebin.com/RBwaMGNf).

In the first group, "Guest", the `permissions:` after line 10 are "global" permissions that apply to all worlds for that group.

The `permissions:` on lines 18, 21, 24, 27, 30, 33, and 36 are for permissions that are specific to only that world.

If you want 6 of your worlds to have a node called `permission.node.seven` and do not want the 7th world (criativo) to have that node, you would give that permission node to the group under "global" permissions, and _negate_ the node on criativo.  Like this:

```
    permissions:
    - permission.node.seven
    worlds:
      criativo:
        permissions:
        - -permission.node.seven
      lobby:
        permissions:
        - permission.node.six
      loja:
        permissions:
        - permission.node.five
      mine:
        permissions:
        - permission.node.four
      world:
        permissions:
        - permission.node.three
      world_nether:
        permissions:
        - permission.node.two
      world_the_end:
        permissions:
        - permission.node.one
```

(I included some example permissions that will be specific to all the other worlds too.  This way, you can see that "world_the_end" gets `permission.node.seven`— from its global permissions —and `permission.node.one` from its world-specific permissions.)
