### ISSUE TITLE
Group inheritance - Prefixes and suffixes

### ISSUE THREAD

**Issue by AfkF24** [PEXPlugins/PermissionsEx#2834]
Is there a way to only inherit group permissions and not group prefixes/suffixes as well? 

Here's an example:

```
  Group1:
    options:
      prefix: '[Group1] '
    permissions:
    - perm.permission
  Group2:
    inheritance:
    - Group1
    options:
      suffix: ' [Group2]'
```

If I now assign the group "Group2" to a user, the chat would end up looking like "[Group1] User [Group2]: Message" instead of "User [Group2]: Message" which i initially wanted.
