### ISSUE TITLE
pex not work

### ISSUE THREAD

**Issue by BGamerXD** [PEXPlugins/PermissionsEx#2857]
```
groups:
  default:
     options:
      default: true
    permissions:
    - modifyworld.*
 User:
   options:
    default: false
  premissions:
    - modifyworld.*
    - fe.member
    - bukkit.command.who
    - bukkit.command.motd
    - bukkit.command.rules
    - bukkit.command.spawn
    - bukkit.command.lobby
    - bukkit.command.warp.teleport
    - bukkit.command.warp.list
    - bukkit.command.msg
    - bukkit.command.away
    - bukkit.command.whereami
    - bukkit.command.whereami.compass
    - bukkit.command.tpa
    - bukkit.command.tpaccept
    - bukkit.command.tpyes
    - bukkit.command.tpdeny
  admin:
   options:
    default: false
   premissions:
 - modifyworld.*
    - fe.admin
    - bukkit.command.who
    - bukkit.command.motd
    - bukkit.command.rules
    - bukkit.command.spawn
    - bukkit.command.lobby
    - bukkit.command.warp.teleport
    - bukkit.command.warp.list
    - bukkit.command.msg
    - bukkit.command.away
    - bukkit.command.whereami
    - bukkit.command.whereami.compass
    - bukkit.command.tpa
    - bukkit.command.tpaccept
    - bukkit.command.tpyes
    - bukkit.command.tpdeny
    - bukkit.command.kick
    - bukkit.command.tempban
    - bukkit.command.pardon
    - bukkit.command.kick
    - bukkit.command.mute
```
