### ISSUE TITLE
PEX Back-end Errors

### ISSUE THREAD

**Issue by JilkOwez** [PEXPlugins/PermissionsEx#2862]
Hi, This is my first post on GitHub so bare with me.

I am making a spigot server on Minecraft 1.12. I am encountering some issues with PEX. It is something to do with permissions on the back-end of Java. At first, I thought it was essentials as it said version mismatch but I fixed that and it did nothing. This is the errors that i am getting (picture):

![ws](https://user-images.githubusercontent.com/30081702/28076793-a3b44c82-6657-11e7-8b61-5d01eb77c0a9.PNG)
![dg](https://user-images.githubusercontent.com/30081702/28076794-a3b69e9c-6657-11e7-913b-471563149548.PNG)
![ht](https://user-images.githubusercontent.com/30081702/28076795-a4078848-6657-11e7-8fa3-e0a0897787a2.PNG)

------

When I start my server up, PEX just does not work and does not show prefixes. It just crashes and does not reload or retry. I have cheaked all of my code and I am pretty sure its fine. Code:
```
groups:
  Newcomer:
    options:
     default: true
     rank: 1
     prefix: '[Newcomer] '
    permissions:
     - modifyworld.*
     - essentials.kit
     - essentials.balance
     - essentials.eco
     - essentials.pay
     - essentials.sell
     - essentials.afk
     - essentials.rules
     - essentials.clearinventory
     - essentials.tpa
     - essentials.warp
     - essentials.warp.list
    
   Dotator:
    options:
     default: false
     rank: 2
     prefix: '[&cMember&f] '
    inheritance:
     - Newcomer
    permissions:
     - essentials.keepxp
     - essentials.back.ondeath
     - essentials.home
     - essentials.delhome
     - essentials.fly
     - essentials.home.bed
     - essentials.tpaall
     - essentials.enderchest
     - essentials.heal
      
   Youtuber:
    options:
     default: false
     rank: 3
     prefix: '[&cYoutuber&f] '
    inheritance:
     - Newcomer
     - Dotator
      
   Moderator:
    options:
     default: false
     rank: 10
     prefix: '&d[&1Moderator&d] '
    inheritance:
     - Newcomer
     - Dotator
    permissions:
     - essentials.mute.offline
     - essentials.mute
     - essentials.broadcast
     - essentials.clearinventory.others
     - essentials.kick
     - essentials.kill
     - essentials.kill.force
     - essentials.jails
     - essentials.togglejail
     - holograms.help.*
     - holograms.list.*
     - holograms.near.*
     - holograms.info
     - holograms.readtext
     - holograms.reload
     - essentials.invsee
     - essentials.vanis
     - essentials.home.others
     - essentials.tp.*
     - essentials.warp.*
     
    Admin:
    options:
     default: false
     rank: 11
     prefix: '&d[&aAdmin&d]&f '
    inheritance:
      - Newcomer
      - Dotator
      - Moderator
    permissions:
     - holograms.create
     - holograms.delete
     - holograms.teleport
     - holograms.copy
     - essentials.invsee
     - essentials.invsee.*
     - essentials.enderchest.*
     - essentials.kill
     - essentials.socialspy.*
     - essentials.tempban
     - essentials.jail.allow
     - essentials.vanish.*
     - essentials.chat.*
     - essentials.protect.*
      
   Co-Owner:
    options:
     default: false
     rank: 998
     prefix: '&d[&eCo-CEO&d]&f '
    permissions:
     - '*'
   
  Owner:
    options:
     default: false
     rank: 999
     prefix: '&d[&bCEO&d]&f '
    permissions:
     - '*'
    
schema-version: 1

users:
  3a26d534-f664-4245-99d2-943d43ee5378:
    permissions:
    - '*'
    group:
    - Owner
    options:
      name: raffeey
  slayer_joe:
    group:
    - Co-Owner
```
Thanks in advanced, Jilk Owez

EDIT: Getting code right

**] Edit by Stormbow: added code tags around the permissions.yml file contents. [**
