### ISSUE TITLE
Double prefixes

### ISSUE THREAD

**Issue by Buster801** [PEXPlugins/PermissionsEx#2867]
Somehow the pex prefixes are being added twice and one of the prefixes is being shown in tab, essentials /list, etc. It is like the prefix has become a part of players' name. Any idea on what is causing this? We have tried removing plugins and changing configs and nothing is working.

**Comment by zml2008** [comment]
It's one of your chat plugins, not PEX. You probably have multiple set up.

**Comment by Stormbow** [comment]
@Buster801 The default config for Essentials contains "group name" + "prefix + username + suffix" + "message", so when you give the group a prefix in PEX's permissions.yml file, you end up with exactly what you're experiencing— GroupName GroupName PlayerName Message.

To fix that, follow [these instructions](https://pastebin.com/eHCCcNuY).

**Comment by Buster801** [comment]
I don't use essentials chat and I have never had this problem until updating the server until 1.12. Even when I downgraded to 1.11.2 it is still showing up twice.

**Comment by Stormbow** [comment]
So which chat management plugin are you using?

**Comment by Buster801** [comment]
Herochat but I tried with VentureChat aswell and it still did it

**Comment by Stormbow** [comment]
Show me the config file.

**Comment by Buster801** [comment]
Here it is but a chat plugin should effect how the prefix is shown in /list and in tab
```
moderator-permissions:
  can-kick: true
  can-ban: true
  can-mute: true
  can-remove-channel: true
  can-modify-nick: true
  can-modify-color: true
  can-modify-distance: true
  can-modify-password: true
  can-modify-format: false
  can-modify-shortcut: false
  can-modify-verbose: true
  can-modify-focusable: false
  can-modify-crossworld: false
  can-color-messages: false
  can-view-info: true
  can-focus: true
default-channel: Global
censors: []
format:
  default: '{color}[{nick}] &f{sender}{suffix}{color}: {msg}'
  announce: '{color}[{nick}] {msg}'
  emote: '{color}[{nick}] * {msg}'
  private-message: '&d{convoaddress} {convopartner}&d: {msg}'
use-channel-emotes: true
locale: en_US
log-chat: true
log-to-bukkit: true
twitter-style-private-messages: false
msg-sound-alert: true
msg-sound-alert-sound: ENTITY_PLAYER_LEVELUP
use-emote-alias: false
use-cross-server: false
conversation-cost: 0.0
servername: My Minecraft Server
serveralias: '[M]'
servers: ''
use-economy: false
```
