### ISSUE TITLE
? this

### ISSUE THREAD

**Issue by tamedkek** [PEXPlugins/PermissionsEx#2887]
https://pastebin.com/AyCa1c7M

**Comment by Stormbow** [comment]
There are errors in your permissions.yml file.

**Comment by tamedkek** [comment]
ok where

**Comment by tamedkek** [comment]
groups: 
  ninja:
    options:
      prefix:'&0[ninja&0] &r '
       permissions:
    - essentals.kit.ninja
   PvP:
    options:
      prefix:' [pvp]  
       permissions:
    - essentals.kit.PvP
   tank:
   options:
      prefix: ' &1[TANK&1] &r '
       permissions:
    - essentals.kit.TANK
   phoenix:
    options:
      prefix:'&6[phoenix&6] &r '
       permissions:
    - essentals.kit.phoenix
    schema-version: 1
users:
  0be58318-b94a-4530-a35e-a1639af3f954:
    group:
    - owner
    options:
      name: Tamed_taco_pap
      group: tank

**Comment by Stormbow** [comment]
As I told you in one of your (too many) other tickets, you need to count the spaces at the beginning of each line in [this example](https://pastebin.com/8ZSHxauG), and make your file have the same number of spaces at the beginning of each of its lines.

**Comment by tamedkek** [comment]
they all have the same space amount

**Comment by Stormbow** [comment]
Compare [your post](https://github.com/PEXPlugins/PermissionsEx/issues/2887#issuecomment-317788506) to this post:
```
groups: 
  ninja:
    options:
      prefix:'&0[ninja&0] &r '
    permissions:
    - essentals.kit.ninja
  PvP:
    options:
      prefix:' [pvp] '
    permissions:
    - essentals.kit.PvP
  tank:
    options:
      prefix: ' &1[TANK&1] &r '
    permissions:
    - essentals.kit.TANK
  phoenix:
    options:
      prefix:'&6[phoenix&6] &r '
    permissions:
    - essentals.kit.phoenix
schema-version: 1
users:
  0be58318-b94a-4530-a35e-a1639af3f954:
    group:
    - owner
    options:
      name: Tamed_taco_pap
      group: tank
```
