### ISSUE TITLE
PermissionEX or EssentialsXChat problem with ranks

### ISSUE THREAD

**Issue by Lerii** [PEXPlugins/PermissionsEx#2917]
like in title i have a problem, i do read your topic's with all that explaining things, but i really dont know what i'm doing wrong, can you help me?, let me explain my problem

I do set some groups in permissionEX like
```
groups:
  Gracz:
    options:
      default: true
      prefix: '&8[&eGracz&8]&7'
      permissions:
      - modifyworld.*
      - essentials.msg
      - essentials.tpa
      - essentials.tpaccept
      - essentials.tpdeny
      - essentials.afk
      - essentials.auto.afk
      - essentials.helpop
      - essentials.kit
      - essentials.kits.tools
      - essentials.warp
      - essentials.spawn
      - essentials.warp.list
      - essentials.help
      - essentials.sethome
      - essentials.home
```
this is example of my 1 group, i added my friend by command /pex group Gracz user add MyFreindName and what is displaying on my screen when he writes

[default] MyFriendName : dwadawd12d
