### ISSUE TITLE
World specific group settings not working

### ISSUE THREAD

**Issue by bacon-avenger** [PEXPlugins/PermissionsEx#292]
This is in regards to http://forums.bukkit.org/threads/admn-dev-permissionsex-pex-v1-19-tomorrow-is-today-1-1-r6.18140/page-189#post-995050

permissions.yml:

```
groups:
  Crafter:
    default: true
    inheritance:
    - g-basic
    prefix: '&a[Crafter] '
  Owner:
    default: false
    inheritance:
    - Crafter
    prefix: '&7[Owner] '
    worlds:
      Muezli-1:
        permissions:
        - -vanish.silentjoin
        - '*'
users:
  ScottSpittle:
    worlds.`Muezli-111`.group:
    - Owner
```

The command `pex user ScottSpittle group set Owner Muezli-111` was run and resulted in the user section listed.  However, when the player logs into the server, they never get assigned to the owner group, only the crafter group.

I have also reproduced this on my testing server using PEX 1.19 and Bukkit R6 build 1988.  The global group setting works as expected.
