### ISSUE TITLE
New to PEX

### ISSUE THREAD

**Issue by Yodonashi** [PEXPlugins/PermissionsEx#2946]
Hello there,

Recently a website I work for has decided to open a new minecraft server. Back in 2014 and 2015 I had been very well versed in minecraft development, but now however I'm at a loss as most of the plugins that I used back then (Group Manager being a major one) are no longer up to date. So now I'm needing to use PermissionsEX which I have never actually used before. It would seem however that no matter what I try to do, I just can't seem to figure out how to get the permissions.yml configured correctly for my server.

Bit of background here, I am using the EssentialsX fork of essentials, Vault, MassiveCore, Factions, and Multiverse. Those are the only plugins I can think of right away that directly interact with PEX other than listing permissions. But here is a picture of all the plugins currently installed to my server.
![2017-08-31_02 51 58](https://user-images.githubusercontent.com/31502630/29912465-64f6f748-8df7-11e7-946b-924e5a35153f.png)

It would seem that my groups aren't loading correctly. I have a group made that consists of the following ranks in ascending order: default -> Web Mod -> Moderator -> Administrator -> Developer
The following is what my permissions.yml file looks like:
```
groups:
  default:
    options:
      default: 'true'
      rank: '1000'
      rank-ladder: main
    permissions:
    - essentials.buy
    - essentials.sell
    - essentials.balance
    - essentials.balancetop
    - essentials.delhome
    - essentials.help
    - essentials.ignore
    - essentials.kit
    - essentials.kit.starter
    - essentials.mail
    - essentials.mail.send
    - essentials.motd
    - essentials.msg
    - essentials.build
    - essentials.signs.use
    - essentials.signs.use.buy
    - essentials.signs.use.sell
    - essentials.signs.use.enchant
    - essentials.signs.use.repair
    - essentials.signs.use.warp
    - essentials.signs.use.weather
    - essentials.signs.use.*
    - essentials.ping
    - essentials.realname
    - essentials.rules
    - essentials.sethome
    - essentials.spawner
    - essentials.spawner.*
    - essentials.suicide
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.tpdeny
    - essentials.warp
    - essentials.warp.list
    - essentials.home
    schema-version: 1
  Web Mod:
    permissions:
    - essentials.afk
    - essentials.afk.kickexempt
    - essentials.back
    - essentials.balance.others
    - essentials.broadcast
    - essentials.ban
    - essentials.ban.notify
    - essentials.ban.offline
    - essentials.clearinventory
    - essentials.clearinventory.others
    - essentials.compass
    - essentials.enchant
    - essentials.essentials
    - essentials.feed
    - essentials.getpos
    - essentials.getpos.others
    - essentials.hat
    - essentials.home.others
    - essentials.invsee
    - essentials.jails
    - essentials.kick
    - essentials.kick.exempt
    - essentials.kick.notify
    - essentials.kit.*
    - essentials.mute
    - essentials.mute.exempt
    - essentials.nick
    - essentials.nick.color
    - essentials.nick.format
    - essentials.nick.magic
    - essentials.nick.others
    - essentials.chat.spy
    - essentials.chat.color
    - essentials.chat.format
    - essentials.chat.magic
    - essentials.chat.shout
    - essentials.chat.url
    - essentials.joinfullserver
    - essentials.msg.color
    - essentials.msg.format
    - essentials.msg.magic
    - essentials.msg.url
    - essentials.repair
    - essentials.repair.armor
    - essentials.repair.enchanted
    - essentials.sethome.multiple
    - essentials.sethome.multiple.unlimited
    - essentials.socialspy
    - essentials.spwaner.*
    - essentials.tempban
    - essentials.tempban.exempt
    - essentials.tempban.offline
    - essentials.jail
    - essentials.jail.others
    - essentials.jail.exempt
    - essentials.unban
    - essentials.workbench
    inheritance:
    - default
    schema-version: 1
    options:
      rank: '900'
      rank-ladder: main
    prefix: '&3[Web Mod]'
  Moderator:
    options:
      rank: '800'
      rank-ladder: main
    prefix: '&a[Moderator]'
    inheritance:
    - default
    - Web Mod
    schema-version: 1
  Administrator:
    options:
      rank: '700'
      rank-ladder: main
      op: true
    prefix: '&9[Admin]'
    permissions:
    - essentials.*
    - multiverse-core.*
    - worldedit.*
    - mcore.*
    - multiverse-portals.*
    - factions.*
    - mcmmo.*
    inheritance:
    - default
    - Web Mod
    - Moderator
    schema-version: 1
  Developer:
    options:
      rank: '600'
      rank-ladder: main
    op: true
    prefix: '&1[&4Developer&1]'
    inheritance:
    - default
    - Web Mod
    - Moderator
    - Administrator
schema-version: 1
users:
  30a4377c-a5ae-4546-981e-ee8bc3a06d65:
    options:
      name: Yodonashi
```
 
Now however, when I log on to the server, no one is moved to the default group. The reason I know this is because even though I type /promote Yodonashi, it gives me an error saying "users are not in this ladder" Correct me if I'm wrong, but shouldn't "main" be the default ladder as I have "default" set to the default rank?

Furthermore, none of the Prefixes are showing in game even though I clearly have them in my YML. 

So now that that rant is over, I'll state what my issues are. Prefixes not showing, and no one is being put into the promotion ladder. How do I make the server automatically add new members to the ladder?
