### ISSUE TITLE
Custom Set Homes

### ISSUE THREAD

**Issue by ArhamR** [PEXPlugins/PermissionsEx#2954]
Hi, I am making a server and i have made it so that people with different ranks can set different home but when i go to the second rank(Magician) after the first (Peasent) using auto rank i am unable to set homes the rank does have a custom set homes 
```yaml
sethome-multiple:
  
default: 1
  
# essentials.sethome.multiple.magician
  
magician: 3
  
# essentials.sethome.multiple.scientist
  
scientist: 5
  
# essentials.sethome.multiple.mad_scientist
  
mad_scientist: 7
  
# essentials.sethome.multiple.staff
  
staff: 10
```
 
There are '#' before each permissions but the r making the perms bold but it is correct in the config below

full configs:
Essentialls: https://pastebin.com/wEA7BpCf
PermissionsEX: https://pastebin.com/bG0YcJ3c
