### ISSUE TITLE
PEX incorrectly using permissions with children permissions

### ISSUE THREAD

**Issue by Acrobot** [PEXPlugins/PermissionsEx#300]
In the plugin.yml, the ChestShop.shop.create permission is created with two children permissions, ChestShop.shop.create.buy and ChestShop.shop.create.sell.

``` yaml
  ChestShop.shop.*:
    description: Gives access to all user ChestShop permissions
    children:
        ChestShop.shop.create: true
        ChestShop.shop.buy: true
        ChestShop.shop.sell: true
    default: true
  ChestShop.shop.create:
    description: Allows the user to create a shop that sells and buys any item
    children:
        ChestShop.shop.create.buy: true
        ChestShop.shop.create.sell: true
  ChestShop.shop.create.buy:
    description: Allows the user to create a shop that sells any item
  ChestShop.shop.create.sell:
    description: Allows the user to create a shop that buy any item
```

It works fine, but when I try to remove the ChestShop.shop.create permission in PEX using negative node, it doesn't work:

``` yaml
users:
  AcrobotPL:
    permissions:
    - -ChestShop.shop.create
```

However, doing the same, but with ChestShop.shop.create.buy works fine:

``` yaml
users:
  AcrobotPL:
    permissions:
    - -ChestShop.shop.create.buy
```

Also, PEX gives that information:

``` yaml
[INFO] User AcrobotPL checked for "ChestShop.shop.create.sell", found in superperms
```

(using the -ChestShop.shop.create permission)
