### ISSUE TITLE
MySQL login not defined

### ISSUE THREAD

**Issue by TheSource85** [PEXPlugins/PermissionsEx#3069]
I'm trying to create a new login for MySQL but it's based on previous PEX versions and now it doesn't work.
Previously 'uri' was used, now 'url', but the username/password keys don't appear to work and I can't find out what they should be.. 

Error:
-----------

[Server] ERROR [ca.stellardrift.permissionsex.ext.com.zaxxer.hikari.pool.HikariPool] HikariPool-1 - Exception during pool initialization.
[Server] INFO java.sql.SQLException: Access denied for user ''@'localhost' (using password: NO)

-----------

Config:
-----------
```yaml
version: 0
debug: true
backends:
    default-file:
        file: permissions.json
        auto-reload: true
        alphabetize-entries: false
        type: file
    default:
        prefix: pex
        url: jdbc:h2:permissions
        type: sql
    sql:
        url: mysql://localhost/<DBName>?useSSL=false
        username: <DBUserName>
        password: <DBPass>
        aliases:
            permissions: pex_permissions
            permissions_inheritance: pex_inheritance
            permissions_entity: pex_entity
        type: sql
        prefix: pex
default-backend: sql
platform:
    fallback-op: true
server-tags: []
```

-----------
