### ISSUE TITLE
No prefix or color?

### ISSUE THREAD

**Issue by PeaceDealer** [PEXPlugins/PermissionsEx#31]
Hey

Ive made some prefix's in my permissions file but they dont show up on the world? Using the chat manager that came with PEX

Chat Manager config:

```
chat-range: 100.0
global-message-format: [%world] >> %prefix %player%suffix: &e%message
enable: true
message-format: %prefix %player%suffix: %message
ranged-mode: false
```

Prefix setting in permissions:

```
ServerOwner:
    worlds:
        '&f[&1SO&f]':
            prefix: set
    permissions:
    - '*'
```
