### ISSUE TITLE
Promotion Tracks not? Working

### ISSUE THREAD

**Issue by arjunyg** [PEXPlugins/PermissionsEx#375]
When I try to promote someone either from console or in game I get this (***username*** means the username of the player in question - hidden for privacy reasons):

command: pex promote ***username***
error: [SEVERE] Ranking Error (console > ***username***):  User are not promotable

Here is (most) of my permissions file:

``` yaml
groups:
  Default:
        default: true
    prefix: '&7[&8Default&7] '
    options:
      rank: '100'
      rank_ladder: default
    permissions:
    - essentials.spawn
    ...
    - essentials.warp.list
  Member:
    default: false
    inheritance:
    - Default
    prefix: '&7[&2Member&7] '
    options:
      rank: '200'
      rank_ladder: default
    permissions:
    - essentials.time
    ...
    - essentials.signs.format
  Mod:
    default: false
    inheritance:
    - Member
    prefix: '&7[&9Moderator&7] '
    permissions:
    - Modifyworld.*
   ...
    - essentials.chat.format
  Admin:
    default: false
    inheritance:
    - Mod
    prefix: '&7[&4Admin&7] '
    permissions:
    - essentials.bigtree
    ...
    - essentials.tppos
users:
  arjunyg:
    group:
    - Admin
    permissions:
    - permissions.*
  ***username***:
    group:
      -Default
```

PS:
Additionally the createUserRecords option in the config file is not working -> it was not auto-creating an entry for ***username*** when he logged in. I think thats supposed to be how it works right? I may be wrong.
