### ISSUE TITLE
modifyworld.blocks.destroy.x doesn't work...!

### ISSUE THREAD

**Issue by aciidic** [PEXPlugins/PermissionsEx#407]
Right so here are my permissions:

```
    - modifyworld.blocks.destroy.18
    - modifyworld.items.*
    - modifyworld.damage.*
    - modifyworld.mobtarget.*
    - modifyworld.interact.*
    - modifyworld.tame.*
    - modifyworld.vehicle.*
    - modifyworld.bucket.*
    - modifyworld.chat.private
    - modifyworld.chat
    - modifyworld.sprint
    - modifyworld.sneak
    - modifyworld.digestion
```

Modifyworld config:

```
    enable: true
    itemRestrictions: false
    informPlayers: false
    whitelist: false
    messages:
      whitelistMessage: You are not whitelisted on this server. Goodbye!
      prohibitedItem: You have prohibited item "%s".
      permissionDenied: Sorry, you don't have the correct permissions
    use-material-names: false
    drop-restricted-item: false
    item-use-check: false
```

Someone please explain to me why it wont let me break leaves?
I have tried loads of variants and the only way it'll work is with this permission:
modifyworld.blocks.*

This doesn't even work either:
modifyworld.blocks.destroy.*

Please help me, I am about to flip shit this is so fucking fustrating, I've never had a problem like this before and im 99% sure its not my fault!
