### ISSUE TITLE
server.broadcast(message, permission) calls not handled properly

### ISSUE THREAD

**Issue by szendo** [PEXPlugins/PermissionsEx#452]
**config.yml**:

``` yaml
permissions:
  debug: true
  backend: file
  backends:
    file:
      file: permissions.yml
  superperms:
    debug: true
```

**permissions.yml**:

``` yaml
groups:
  default:
    default: true
    permissions:
    - modifyworld.*
users:
  Sendow:
    permissions:
    - sndw.adminchat
    - bukkit.broadcast.admin
```

Depite having `bukkit.broadcast.admin` I can only see messages broadcast to that channel when I'm listed in the ops.txt file. Same happens with `sndw.adminchat` (own plugin's permission node, defined as `default: op`)

Tested with 1.19.2 (stable) and 1.19.3 (latest dev) versions of PEX.

Tested against:
- CraftBukkit version git-Bukkit-1.2.5-R4.0-b2222jnks (MC: 1.2.5) (Implementing API version 1.2.5-R4.0) (**[startup log](http://pastebin.com/0TMip7Xy)**)
- CraftBukkit version git-Bukkit-1.2.5-R3.0-b2203jnks (MC: 1.2.5) (Implementing API version 1.2.5-R3.0)
- CraftBukkit version git-Bukkit-1.2.5-R1.3-13-g7ab0391-b2190jnks (MC: 1.2.5) (Implementing API version 1.2.5-R2.0)

(bPermissions and PermissionsBukkit handle these calls fine, but I don't want to pass on ChatManager just because of this)
