### ISSUE TITLE
Multiple permission files?

### ISSUE THREAD

**Issue by BenWoodworth** [PEXPlugins/PermissionsEx#496]
Can you add support for multiple permission files? I have one really large file, and it would be nice if i could have several separate files so i don't have to scroll through the entire file to change a single thing.

Here is an example:

I have the file permA.yml with:

```
groups:
    default:
        default: true
        permissions:
        - example.perm
        - another.example.perm
```

I would also have the file permB.yml:

```
    admin:
        permissions:
        - -unwanted.perm
        - '*'
```

The config file could be something like this:

```
permissions:
    backend: file
    backends:
        file:
            file:
            - permA.yml
            - permB.yml
    superperms: {}
```

When PEX reads these files, it will combine them all together into a single file, like this:

```
groups:
    default:
        default: true
        permissions:
        - example.perm
        - another.example.perm[/code]
    admin:
        permissions:
        - -unwanted.perm
        - '*'
```

I hope you like this idea! It seems like it would be a simple thing to do, too :D
