### ISSUE TITLE
giving me errors

### ISSUE THREAD

**Issue by marinov** [PEXPlugins/PermissionsEx#499]
I'm using PermissionsEx-1.19.2, and now that I set the config file, I get errors.

``` yaml
groups:
  Member:
    default
    permissions:
    - modifyworld.world
    - modifyworld.world_nether
    - modifyworld.world_the_end
    - modifyworld.Creative
    - essentials.rules
    - essentials.help
    - essentials.pay
    - essentials.balance
    - essentials.tell
    - essentials.sell
    - essentials.back
    - essentials.back.ondeath
    - essentials.who
    - essentials.afk
    - essentials.list
    - essentials.msg
    - essentials.nick
    - essentials.warp.list
    - essentials.warp
    - essentials.helpop
    - essentials.motd
    - essentials.spawn
    - essentials.home
    - essentials.tpa
    - essentials.tpahere
    - essentials.tpaccept
    - essentials.sethome
    - iConomy.payment
    - iConomy.holdings
    - iConomy.holdings.others
    - iConomy.sell
    - lwc.protect
    - ChestShop.buy
    - ChestShop.sell
    - multiverse.access.*
    - multiverse.portal.access.*
  VIP:
    inheritance:
    - Member
    permissions:
    - modifyworld.Creative_VIP
    - modifyworld.Redstone
  Moderator:
    permissions:
    - essentials.tempban
    - essentials.heal
    - essentials.feed
    - essentials.ban.notify
    - essentials.banip
    - essentials.clearinventory
    - essentials.eco.loan
    - essentials.ext
    - essentials.getpos
    - essentials.helpop.recieve
    - essentials.home.others
    - essentials.invsee
    - essentials.jails
    - essentials.jump
    - essentials.kick
    - essentials.kick.notify
    - essentials.mute
    - essentials.realname
    - essentials.signs.create.*
    - essentials.signs.break.*
    - essentials.time
    - essentials.protect.alerts
    - essentials.protect.admin
    - essentials.protect.ownerinfo
    - essentials.togglejail
    - essentials.top
    - essentials.unban
    - essentials.unbanip
    - essentials.whois
    - essentials.world
    inheritance:
    - Member
  Admin:
    permissions:
    - essentials.gamemode
    - essentials.tp
    - essentials.ban
    - essentials.god
    - essentials.invsee
    - modifyworld.*
    inheritance:
    - Moderator
  Owner:
    permissions:
    - '*'
    inheritance:
    - admin
messages:
  build: '&cYou do not have permission to build here.'
```
