### ISSUE TITLE
Multiworld configuration doesn't work in Bukkit 1.3.1-R0.1#2269

### ISSUE THREAD

**Issue by buschtoens** [PEXPlugins/PermissionsEx#508]
```
/pex group Registered

  Registered are member of:
    @world_end:
     basic (not ranked)
    @world_nether:
     basic (not ranked)
    @world:
     basic (not ranked)
  Group Registered's permissions:

  Grop Registered's options:

```

Although the configuration is loaded and displayed PEX actually doesn't apply it. It ignores the per-world settings and uses the default  group.

```
groups:
  visitor:
    permissions:
    - -modifyworld.login
    - -modifyworld.chat.private
    - -modifyworld.beds
    - -modifyworld.bucket.*
    ...
    - modifyworld.*
  basic:
    permissions:
      - -modifyworld.bucket.empty.lava
      - -modifyworld.damage.deal.animal.wolf.*
      - -modifyworld.damage.deal.animal.ocelot.*
      - -modifyworld.damage.deal.npc.villager
      - -modifyworld.damage.deal.irongolem
      - modifyworld.*

  Gast:
    default: true
    prefix: '&8'
    inheritance:
    - visitor
  Registriert:
    prefix: '%7'
    worlds:
      world:
        inheritance:
        - basic
      world_nether:
        inheritance:
        - basic
      world_end:
        inheritance:
        - basic
```
