### ISSUE TITLE
how to disable permissions for ops

### ISSUE THREAD

**Issue by edtrud** [PEXPlugins/PermissionsEx#523]
How can i disable permissions for ops with permissionsEX. this is my permissions file:

groups:
    default:
        prefix: '&cMember '
        default: true
        permissions:
        - essentials.afk
        - essentials.back
        - essentials.back.onedeath
        - essentials.balance
        - essentials.balance.others
        - essentials.balancetop
        - essentials.color
        - essentials.format
        - essentials.shout
        - essentials.question
        - essentials.clearinventory
        - essentials.compass
        - essentials.depth
        - essentials.delhome
        - essentials.getpos
        - essentials.help
        - essentials.helpop
        - essentials.home
        - essentials.ignore
        - essentials.itemdb
        - essentials.kit
        - essentials.kit.tools
        - essentials.list
        - essentials.mail.send
        - essentials..mail
        - essentials.me
        - essentials.motd
        - essentials.msg
        - essentials.pay
        - essentials.r
        - essentials.rules
        - essentials.sethome
        - essentials..spawn
        - essentials.suicide
        - essentials.time
        - essentials.tpa
        - essentials.tpaccept
        - essentials.tpahere
        - essentials.tpdeny
        - essentials.warp
        - essentials.warp.list
        - ChestShop.shop.create
        - ChestShop.shop.buy
        - ChestShop.shop.sell
        - factions.help
        - factions.list
        - factions.ls
        - factions.show
        - factions.who
        - factions.power
        - factions.pow
        - factions.join
        - factions.leave
        - factions.chat
        - factions.c
        - factions.home
        - factions.create
        - factions.desc
        - factions.tag
        - factions.open
        - factions.invite
        - factions.inv
        - factions.deinvite
        - factions.deinv
        - factions.sethome
        - factions.claim
        - factions.autoclaim
        - factions.declaim
        - factions.unclaimall
        - factions.unclaimall
        - factions.kick
        - factions.mod
        - factions.admin
        - factions.title
        - factions.map
        - factions.noboom
        - factions.owner
        - factions.ownerlist
        - factions.disband
        - factions.all
        - factions.enemy
        - myhome.econ.free.*
        - myhome.econ.free.sethome
        - myhome.econ.free.home
        - hg.*

```
OP:
    prefix: '&4Op '
    inheritance:
    - default
    permissions:
    - ChestShop.admin
    - ChestShop.mod
    - ChestShop.name
    - ChestShop.nofee
    - ChestShop.create.*
    - colorme.*
    - crazylogin.*
    - crazylogin.admin*
    - crazylogin.commands*
    - crazylogin.mode*
    - essentials.*
    - factions.claim.safezone
    - factions.claim.warzone
    - factions.autoclaim
    - factions.*
    - mcmmo.*
    - myhome.bypass.*
    - myhome.admin.*
    - hga.*
    - nocheat.*
    - paintball.admin
    - paintball.start
    - paintball.end
    - worldedit.*
    - worldgaurd.*

OP1:
    prefix: '&4Op '
    inheritance:
    - default
    permissions:


Admin:
    prefix: '&bAdmin '
    inheritance:
    - default
    - OP
    permissions:
    - bukkit.commands.*
    - mobdisguise.*
    - multiverse.core*
    - multiverse.world*
    - mv.*
    - Punish.*
    - vanish.*
    - vault.*
    - worldborder.*
```

users:
    edtrud:
        group:
        - OP
        - default
        - Admin
users:
    YoYo:
        group:
        - OP
        - default
users:
    meta_beta:
        group:
        - OP
        - default
users:
    Ultimate_Slayer:
        group:
        - OP
        - default
        - Admin
users:
    epicness001:
        group:
        - OP
        - default
