### ISSUE TITLE
Permissions not working, throwing errors

### ISSUE THREAD

**Issue by RY4NIIx** [PEXPlugins/PermissionsEx#557]
2012-09-15 14:20:24 [SEVERE] Error occurred while enabling PermissionsEx v1.19.3 (Is it up to date?)
java.lang.IllegalStateException: Error loading permissions file
at ru.tehkode.permissions.backends.FileBackend.reload(FileBackend.java:251)
at ru.tehkode.permissions.backends.FileBackend.initialize(FileBackend.java:79)
at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:425)
at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:487)
at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:54)
at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:74)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:365)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:265)
at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:247)
at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:567)
at org.bukkit.Bukkit.reload(Bukkit.java:183)
at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:21)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:492)
at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:488)
at net.minecraft.server.DedicatedServer.ah(DedicatedServer.java:248)
at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: org.bukkit.configuration.InvalidConfigurationException: unacceptable character '?' (0xFFFD) special characters are not allowed
in "<string>", position 37
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:138)
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:105)
at ru.tehkode.permissions.backends.FileBackend.reload(FileBackend.java:247)
... 21 more
Caused by: unacceptable character '?' (0xFFFD) special characters are not allowed
in "<string>", position 37
at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:70)
at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:50)
at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53)
... 24 more

That is the error i am repeatedly getting Here is my permissions file:

``` yaml
groups:
  Founder:
    prefix: '[&d&k¦&r&dFounder&d&k¦&r]
    permissions:
    - bukkit.command.op
    inheritance:
    - Admin
  HeadAdmin:
    prefix: '[&4HeadAdmin&f]'
    permissions:
    - bukkit.command.op
    inheritance:
    - Admin
  Admin:
    permissions:
    - vanish.toggle.*
    - -bukkit.command.op
    - permissions.*
    - bukkit.command.*
    - modifyworld.*
    - essentials.*
    - worldedit.*
    - worldguard.*
    - vanish.op
    - vanish.toggle.all
    - vanish.standard
    - vanish.hooks.essentials.hide
    - herochat.*
    - backup.*
    - coloredtablist.dark_red
    - coloredtablist.prefix1
    prefix: '[&4Admin&f]'
  Member:
    permissions:
    - modifyworld.*
    - essentials.tpaccept
    - essentials.msg
    - commandsigns.use.*
    - backup.notify
    - herochat.force.join.Local
    - herochat.speak.Global
    - herochat.speak.Local
    - herochat.join.Local
    - herochat.join.Global
    - bukkit.commands.plugins
    - BOSEconomy.common.wallet
    - BOSEconomy.common.income
    - BOSEconomy.common.mastry
    - BOSEconomy.common.pay
    - BOSEconomy.common.stats
    - BOSEconomy.common.top5
    default: true
    prefix: '[&fMember]'
  TempMod:
    permissions:
    - essentials.tpa
    - essentials.msg
    - essentials.msg.color
    - essentials.msg.format
    - simplejail.*
    - essentials.invsee
    - backup.notify
    - coloredtablist.prefix2
    - bukkit.command.ban.player
    prefix: '[&1TempMod&f]'
    inheritance:
    - Member
  Moderator:    
    permissions:
    - essentials.tp
    - vanish.standard
    inheritance:
    - TempMod
  Mage:
    permissions:
    - magicspells.noreagents
    - magicspells.grant.cripple
    - magicspells.cast.cripple
    - magicspells.grant.fireball
    - magicspells.cast.fireball
    - magicspells.grant.firenova
    - magicspells.cast.firenova
    - magicspells.grant.forcepush
    - magicspells.cast.forcepush
    - magicspells.grant.list
    - magicspells.cast.list
    - magicspells.grant.safefall
    - magicspells.cast.safefall
    - magicspells.grant.volley
    - magicspells.cast.volley
    inheritance:
    - Member
    prefix: '[Mage]'
  Wizard:
    permissions:
    - magicspells.grant.blind
    - magicspells.cast.blind
    - magicspells.grant.combust
    - magicspells.cast.combust
    - magicspells.grant.confusion
    - magicspells.cast.confusion
    - magicspells.grant.frostwalk
    - magicspells.cast.frostwalk
    - magicspells.grant.geyser
    - magicspells.cast.geyser
    - magicspells.grant.gills
    - magicspells.cast.gills
    inheritance:
    - Mage
    prefix: '[Wizard]'
  Grandmaster:
    permissions:
    - magicspells.grant.armor
    - magicspells.cast.armor
    - magicspells.grant.bind
    - magicspells.cast.bind
    - magicspells.grant.conjure
    - magicspells.cast.conjure
    - magicspells.grant.reach
    - magicspells.cast.reach
    - magicspells.grant.mark
    - magicspells.cast.mark
    - magicspells.grant.recall
    - magicspells.cast.recall
    - magicspells.grant.minion
    - magicspells.cast.minion
    inheritance:
    - Wizard
    prefix: '[Grandmaster]'
  Legend:
    permissions:
    inheritance:
    - Grandmaster
    - Warrior
    prefix: '[Legend]'
  Warrior:
    permissions:
    - essentials.kit.Warrior
    inheritance:
    - Member
    prefix: '[Warrior]'
  Knight:
    permissions:
    - essentials.kit.Knight
    inheritance:
    - Member
    prefix: '[Knight]'
  Paladin:
    permissions:
    - essentials.kit.Knight
    - magicspells.grant.forcepush
    - magicspells.cast.forcepush
    inheritance:
    - Member
    prefix: '[Paladin]'
  Archer:
    permissions:
    - essentials.kit.Archer
    inheritance:
    - Member
    prefix: '[Archer]'
  Merchant:
    permissions:
    - essentials.kit.Merchant
    inheritance:
    - Member
    prefix: '[&6Merchant&f]'
  Hero:
    permissions:
    inheritance:
    - Mage
    - Wizard
    - Grandmaster
    - Legend
    - Warrior
    - Knight
    - Paladin
    - Archer
    - Merchant
    prefix: '[&a&k¦&r&aHERO&a&k¦&r]'
```

Could you please provide information on this ?
