### ISSUE TITLE
Rank Ladder - User not high enough rank

### ISSUE THREAD

**Issue by sha44864** [PEXPlugins/PermissionsEx#625]
Ok so I have had this problem for a while and cannot figure out why it's doing this.

I have my groups set up, and everything works fine, but when my head moderator and moderators try to promote and demote someone with the command /pex (promote/demote) (name), and also /pex (promote/demote) (name) (ladder) and it doesn't work.  They have all the right permissions needed (I believe) to perform this command, but every time they do it, it says "Promoter don't have high enough rank to change (user's) rank.  I have followed the setup on the permissions git hub page with the rank ladder and still nothing.  Here is a simplified look at what my perms file looks like.  The essentials.\* is just a place holder for where all the permissions are.  Ignore that part.  Look at the ranks.

``` yaml
groups:
  default:
    default: true
    permissions:
    - essentials.*
    worlds:
      creative:
        permissions:
        - essentials.*
      vanilla:
        permissions:
        - essentials.*
      world:
        permissions:
        - -signcolours.*
        - -SurvivalGames.*
    prefix: ' &f[&7Newbie&f] '
    options:
      rank: '8000'
      rank-ladder: main
  Member:
    inheritance:
    - default
    permissions:
    - essentials.*
    prefix: ' &f[&2Member&f] '
    options:
      rank: '7000'
      rank-ladder: main
  Coal:
    inheritance:
    - Member
    permissions:
    - essentials.*
    prefix: ' &e[&8COAL&e]&f '
    options:
      rank: '6000'
      rank-ladder: main
  Iron:
    inheritance:
    - Member
    permissions:
    - essentials.*
    prefix: ' &e[&7IRON&e]&f '
    options:
      rank: '5000'
      rank-ladder: main
  Gold:
    inheritance:
    - Member
    permissions:
    - essentials.*
    prefix: ' &e[&6GOLD&e]&f '
    options:
      rank: '4000'
      rank-ladder: main
  Diamond:
    inheritance:
    - Member
    permissions:
    - essentials.*
    prefix: ' &e[&3DIAMOND&e]&f '
    options:
      rank: '3000'
      rank-ladder: main
  Moderator:
    inheritance:
    - default
    - Member
    - Diamond
    permissions:
    - essentials.*
    prefix: ' &0[&3Mod&0]&f '
    options:
      rank: '2000'
      rank-ladder: main
  headmod:
    inheritance:
    - default
    - Member
    - Moderator
    - DModerator
    permissions:
    - essentials.*
    worlds:
      vanilla:
        permissions:
        - essentials.kick
        - essentials.kick.notify
        - factions.home
    prefix: ' &8[&eHead&3Mod&8]&f '
    options:
      rank: '1'
      rank-ladder: main
  Admin:
    inheritance:
    - Moderator
    permissions:
    - essentials.*
    prefix: ' &0[&bAdmin&0] '
    options:
      rank: '0'
      rank-ladder: main
```

Ok, notice my rank for each group.  I have it ranked as the file should be setup.  Default is the highest number in rank, and it goes down as the rank gets higher.  As far as I know, the numbers do not matter, just as long as the numbers go down in sequential order as the rank gets higher.  The rank-ladder part was something I added just to see if it made it work.  I know thats for multiple ladders.  I really need to know what the problem is here.  I need my moderators to be able to promote and demote players.

PLEASE HELP ASAP!
