### ISSUE TITLE
Chatmanager Message-Format

### ISSUE THREAD

**Issue by jonahferguson** [PEXPlugins/PermissionsEx#630]
This is my config:

``` yaml
enable: true
message-format: <[%world] %prefix%player>%suffix %message
global-message-format: <%prefix%player%suffix> &e%message
ranged-mode: false
chat-range: 100.0
```

I want it to look like this:

``` yaml
enable: true
message-format: [%world] <%prefix%player%suffix> %message
global-message-format: <%prefix%player%suffix> &e%message
ranged-mode: false
chat-range: 100.0
```

But whenever I do that and restart the server, it disables chatmanager and disables it in the config. I think it is because it will not let anything besides "<" be first in the message-format; maybe that or it will not let brackets be first. Any help?
