### ISSUE TITLE
MY PLAYERS CANT DO ANYTHING

### ISSUE THREAD

**Issue by vliamv** [PEXPlugins/PermissionsEx#634]
HERE ARE MY PERMS PLEASE TELL ME IF THERES AN ERRROR
![2013-01-08_17 47 57](https://f.cloud.github.com/assets/3189868/52146/94be6d5e-59ee-11e2-854c-f00dfff2b243.png)

``` yaml
groups:
  Default:
    default: true
    permissions:
    - modifyworld.*
    - lwc.protect
    - afk.auto
    - back
    - back.ondeath
    - balance
    - balance.others
    - balancetop
    - build
    - chat.color
    - chat.format
    - chat.shout
    - chat.question
    - clearinventory
    - compass
    - depth
    - delhome
    - getpos
    - geoip.show
    - help
    - helpop
    - home
    - home.others
    - ignore
    - info
    - itemdb
    - kit
    - kits.tools
    - list
    - mail
    - mail.send
    - me
    - motd
    - msg
    - msg.color
    - nick
    - near
    - pay
    - ping
    - protect
    - r
    - rules
    - realname
    - seen
    - sell
    - sethome
  miembro:
    permissions:
    - lwc.protect
    - afk.auto
    - back
    - back.ondeath
    - balance
    - balance.others
    - balancetop
    - build
    - chat.color
    - chat.format
    - chat.shout
    - chat.question
    - clearinventory
    - compass
    - depth
    - delhome
    - getpos
    - geoip.show
    - help
    - helpop
    - home
    - home.others
    - ignore
    - info
    - itemdb
    - kit
    - kits.tools
    - list
    - mail
    - mail.send
    - me
    - motd
    - msg
    - msg.color
    - nick
    - near
    - pay
    - ping
    - protect
    - r
    - rules
    - realname
    - seen
    - sell
    - sethome

  OWNER:
    permissions:
    - '*'
    prefix: '`&2(&2Owner&2)&1'
  MOD:
    permissions:
    - lwc.protect
  ADMIN:
    permissions:
    - lwc.protect
  Elite:
    permissions:
    - lwc.protect
    - afk.auto
    - back
    - back.ondeath
    - balance
    - balance.others
    - balancetop
    - build
    - chat.color
    - chat.format
    - chat.shout
    - chat.question
    - clearinventory
    - compass
    - depth
    - delhome
    - getpos
    - geoip.show
    - help
    - helpop
    - home
    - home.others
    - ignore
    - info
    - itemdb
    - kit
    - kits.tools
    - list
    - mail
    - mail.send
    - me
    - motd
    - msg
    - msg.color
    - nick
    - near
    - pay
    - ping
    - protect
    - r
    - rules
    - realname
    - seen
    - sell
    - sethome
  regular:
    permissions:
    - lwc.protect
    - afk.auto
    - back
    - back.ondeath
    - balance
    - balance.others
    - balancetop
    - build
    - chat.color
    - chat.format
    - chat.shout
    - chat.question
    - clearinventory
    - compass
    - depth
    - delhome
    - getpos
    - geoip.show
    - help
    - helpop
    - home
    - home.others
    - ignore
    - info
    - itemdb
    - kit
    - kits.tools
    - list
    - mail
    - mail.send
    - me
    - motd
    - msg
    - msg.color
    - nick
    - near
    - pay
    - ping
    - protect
    - r
    - rules
    - realname
    - seen
    - sell
    - sethome
  miembro:
    permissions:
    - lwc.protect
    - afk.auto
    - back
    - back.ondeath
    - balance
    - balance.others
    - balancetop
    - build
    - chat.color
    - chat.format
    - chat.shout
    - chat.question
    - clearinventory
    - compass
    - depth
    - delhome
    - getpos
    - geoip.show
    - help
    - helpop
    - home
    - home.others
    - ignore
    - info
    - itemdb
    - kit
    - kits.tools
    - list
    - mail
    - mail.send
    - me
    - motd
    - msg
    - msg.color
    - nick
    - near
    - pay
    - ping
    - protect
    - r
    - rules
    - realname
    - seen
    - sell
    - sethome
    worlds:
      rodrisan97:
        permissions:
        - user
users:
  vliamv:
    group:
    - OWNER
  withe-bier:
    group:
    - miembro
  rodrisan97:
    group:
    - miembro
  LAMBDA:
    group:
    - miembro
  Daniel:
    group:
    - miembro
```
