### ISSUE TITLE
i do it and the problem stills

### ISSUE THREAD

**Issue by vliamv** [PEXPlugins/PermissionsEx#640]
i delete all the perms and redoit with the console 

``` yaml
groups:
  Default:
    default: true
    permissions:
    - modifyworld.*
  owner:
    permissions:
    - '*'
    prefix: '`&1[&1Owner&1]&2'
  miembro:
    prefix: '`&e[&emiembro&e]&8'
    permissions:
    - afk.auto
    - lwc.protect
  elite: {}
  confiable:
    prefix: '`&a[&aconfiable&a]&b'
    permissions:
    - lwc.protect
  admin: {}
  vip: {}
users:
  vliamv:
    group:
    - owner
```

![2013-01-09_17 41 46](https://f.cloud.github.com/assets/3189868/55159/cc4372d8-5ab6-11e2-9a88-4598be9d4ca9.png)
