### ISSUE TITLE
Adding groups shuts down every other group.

### ISSUE THREAD

**Issue by ThePobst** [PEXPlugins/PermissionsEx#654]
I am setting up donation ranks and whenever i seem to add one rank it shuts down every other ranks so players cant do anything and their prefixes are gone. This is my permissions file.

``` yaml
groups:
 AwesomeDonator:
    default: false
    build: true
    prefix: '&3[AwesomeDonator]&3'
    permissions:
    - essentials.msg
    - essentials.warp
    - essentials.warp.*
    - essentials.spawn
    - essentials.home
    - essentials.sethome
    - essentials.money
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpdeny
    - modifyworld.*
    - essentials.signs.use.free
    - essentials.signs.use.warp
    - essentials.signs.use.buy
    - essentials.balance
    - battleground.join
    - arena.arena.join
    - essentials.signs.use.heal
    - essentials.sell
    - essentials.signs.use.sell
    - essentials.help
    - essentials.signs.use.gamemode
    - factionsplus.createwarp
    - factionsplus.deletewarp
    - factionsplus.warp
    - factionsplus.setjail
    - factionsplus.jail
    - factionsplus.listwarps
    - sg.arena.join
    - sg.arena.vote
    - sg.arena.spectate
    - sg.lobby.join
    - sg.player
    - sg.arena.join*
    - essentials.heal
    - essentials.repair
    - essentials.nick
    - essentials.sethome
  SuperDonator:
    default: false
    build: true
    prefix: '&3[SuperDonator]&3'
    permissions:
    - essentials.msg
    - essentials.warp
    - essentials.warp.*
    - essentials.spawn
    - essentials.home
    - essentials.sethome
    - essentials.money
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpdeny
    - modifyworld.*
    - essentials.signs.use.free
    - essentials.signs.use.warp
    - essentials.signs.use.buy
    - essentials.balance
    - battleground.join
    - arena.arena.join
    - essentials.signs.use.heal
    - essentials.sell
    - essentials.signs.use.sell
    - essentials.help
    - essentials.signs.use.gamemode
    - factionsplus.createwarp
    - factionsplus.deletewarp
    - factionsplus.warp
    - factionsplus.setjail
    - factionsplus.jail
    - factionsplus.listwarps
    - sg.arena.join
    - sg.arena.vote
    - sg.arena.spectate
    - sg.lobby.join
    - sg.player
    - sg.arena.join*
    - essentials.heal
    - essentials.repair
    - essentials.nick
    - essentials.sethome
  MegaDonator:
    default: false
    build: true
    prefix: '&3[MegaDonator]&3'
    permissions:
    - essentials.msg
    - essentials.warp
    - essentials.warp.*
    - essentials.spawn
    - essentials.home
    - essentials.sethome
    - essentials.money
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpdeny
    - modifyworld.*
    - essentials.signs.use.free
    - essentials.signs.use.warp
    - essentials.signs.use.buy
    - essentials.balance
    - battleground.join
    - arena.arena.join
    - essentials.signs.use.heal
    - essentials.sell
    - essentials.signs.use.sell
    - essentials.help
    - essentials.signs.use.gamemode
    - factionsplus.createwarp
    - factionsplus.deletewarp
    - factionsplus.warp
    - factionsplus.setjail
    - factionsplus.jail
    - factionsplus.listwarps
    - sg.arena.join
    - sg.arena.vote
    - sg.arena.spectate
    - sg.lobby.join
    - sg.player
    - sg.arena.join*
    - essentials.heal
    - essentials.repair
    - essentials.nick
    - essentials.sethome
  Donator:
    default: false
    build: true
    prefix: '&3[Donator]&3'
    permissions:
    - essentials.msg
    - essentials.warp
    - essentials.warp.*
    - essentials.spawn
    - essentials.home
    - essentials.sethome
    - essentials.money
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpdeny
    - modifyworld.*
    - essentials.signs.use.free
    - essentials.signs.use.warp
    - essentials.signs.use.buy
    - essentials.balance
    - battleground.join
    - arena.arena.join
    - essentials.signs.use.heal
    - essentials.sell
    - essentials.signs.use.sell
    - essentials.help
    - essentials.signs.use.gamemode
    - factionsplus.createwarp
    - factionsplus.deletewarp
    - factionsplus.warp
    - factionsplus.setjail
    - factionsplus.jail
    - factionsplus.listwarps
    - sg.arena.join
    - sg.arena.vote
    - sg.arena.spectate
    - sg.lobby.join
    - sg.player
    - sg.arena.join*
    - essentials.heal
    - essentials.repair
    - essentials.nick
    - essentials.sethome
  Member:
    default: true
    build: true
    prefix: '&f[Member]&f'
    permissions:
    - essentials.msg
    - essentials.warp
    - essentials.warp.*
    - essentials.spawn
    - essentials.home
    - essentials.sethome
    - essentials.money
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpdeny
    - modifyworld.*
    - essentials.signs.use.free
    - essentials.signs.use.warp
    - essentials.signs.use.buy
    - essentials.balance
    - battleground.join
    - arena.arena.join
    - essentials.signs.use.heal
    - essentials.sell
    - essentials.signs.use.sell
    - essentials.help
    - essentials.signs.use.gamemode
    - factionsplus.createwarp
    - factionsplus.deletewarp
    - factionsplus.warp
    - factionsplus.setjail
    - factionsplus.jail
    - factionsplus.listwarps
    - sg.arena.join
    - sg.arena.vote
    - sg.arena.spectate
    - sg.lobby.join
    - sg.player
    - sg.arena.join*
  Helper:
    default: false
    build: true
    prefix: '&7[&7&lHelper&7]&5'
    permissions:
    - essentials.msg
    - essentials.warp
    - essentials.warp.*
    - essentials.spawn
    - essentials.home
    - essentials.sethome
    - essentials.money
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpdeny
    - modifyworld.*
    - essentials.signs.use.free
    - essentials.signs.use.warp
    - essentials.signs.use.buy
    - essentials.balance
    - battleground.join
    - arena.arena.join
    - essentials.signs.use.heal
    - essentials.sell
    - essentials.signs.use.sell
    - essentials.help
    - essentials.signs.use.gamemode
    - factionsplus.createwarp
    - factionsplus.deletewarp
    - factionsplus.warp
    - factionsplus.setjail
    - factionsplus.jail
    - factionsplus.listwarps
    - essentials.fly
    - essentials.gamemode
    - sg.arena.join
    - sg.arena.vote
    - sg.arena.spectate
    - sg.lobby.join
    - sg.player
    - sg.arena.join*
  Mod:
    default: false
    build: true
    prefix: '&2[Mod]&f'
    permissions:
    - essentials.backup
    - essentials.ban
    - essentials.ban.exempt
    - essentials.ban.notify
    - essentials.ban.offline
    - essentials.banip
    - essentials.broadcast
    - essentials.clearinventory
    - essentials.essentials
    - essentials.ext
    - essentials.fireball
    - essentials.gc
    - essentials.invsee
    - essentials.jail.exempt
    - essentials.jails
    - essentials.kick
    - essentials.kick.exempt
    - essentials.kick.notify
    - essentials.kickall
    - essentials.kill
    - essentials.kill.force
    - essentials.killall
    - essentials.lightning
    - essentials.mute
    - essentials.mute.exempt
    - essentials.ping
    - essentials.remove
    - essentials.setjail
    - essentials.socialspy
    - essentials.spawnmob
    - essentials.spawnmob.*
    - essentials.spawnmob.[mob]
    - essentials.sudo
    - essentials.tempban
    - essentials.tempban.exempt
    - essentials.tempban.offline
    - essentials.thunder
    - essentials.togglejail
    - essentials.togglejail.offline
    - essentials.unban
    - essentials.unbanip
    - essentials.weather
    - essentials.home.others
    - essentials.teleport.hidden
    - essentials.teleport.hidden
    - essentials.time.set
    - essentials.tpaall
    - essentials.tpahere
    - killbox.*
    - essentials.spawn
    - essentials.tp
    - essentials.nick
    - essentials.msg
    - essentials.tphere
    - essentials.home
    - essentials.sethome
    - essentials.money
    - essentials.help
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.fly
    - essentials.warp
    - modifyworld.*
    - essentials.signs.use.free
    - essentials.signs.use.buy
    - essentials.balance
    - battleground.join
    - arena.arena.join
    - essentials.gamemode
    - essentials.fix
    - essentials.enchant.*
    - essentials.enchant
    - sg.arena.join
    - sg.arena.vote
    - sg.arena.spectate
    - sg.lobby.join
    - sg.player
    - sg.arena.join*
  Head-Mod:
    default: false
    build: true
    prefix: '&7[&8Head&7-&3Mod&7]&f'
    permissions:
    - '*'
  Admin:
    default: false
    build: true
    prefix: '&4[Admin]&f'
    inheritance:
    - Mod
    permissions:
    - essentials.unlimited
    - essentials.unlimited.item-[itemid]
    - essentials.unlimited.item-all
    - essentials.unlimited.item-bucket
    - essentials.itemspawn.item-all
    - essentials.warp.list
    - essentials.gamemode
    - essentials.give
    - essentials.give.item-<itemname>
    - essentials.give.item-[itemid]
    - essentials.give.item-all
    - essentials.clearinventory
    - essentials.ext
    - essentials.killall
    - essentials.weather
    - essentials.setwarp
    - essentials.time.set
    - essentials.tpall
    - essentials.tphere
    - essentials.tp
    - worldedit.generation.cylinder
    - worldedit.generation.sphere
    - worldedit.generation.sphere
    - worldedit.generation.forest
    - worldedit.generation.pumpkins
    - worldedit.generation.pyramid
    - worldedit.generation.pyramid
    - worldedit.history.undo
    - worldedit.history.redo
    - worldedit.navigation.unstuck
    - worldedit.navigation.ascend
    - worldedit.navigation.descend
    - worldedit.navigation.ceiling
    - worldedit.navigation.thru
    - worldedit.navigation.up
    - worldedit.region.replace
    - worldedit.region.stack
    - worldedit.region.set
    - worldedit.region.overlay
    - worldedit.region.naturalize
    - worldedit.region.walls
    - essentials.spawn
    - essentials.nick
    - essentials.msg
    - essentials.home
    - essentials.sethome
    - essentials.money
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.warp
    - modifyworld.*
  Legend:
    default: false
    build: true
    prefix: '&c[Legend]&f'
    permissions:
    - essentials.fly
    - essentials.money
    - essentials.jump
    - essentials.spawn
    - essentials.rules
    - essentials.suicide
    - essentials.whois
    - essentials.help
    - modifyworld.*
    - essentials.money
    - essentials.gamemode
    - essentials.sethome.multiple
    - essentials.sethome
    - essentials.home
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.warp
    - modifyworld.*
    - essentials.signs.use.free
    - essentials.signs.use.warp
    - essentials.signs.use.buy
    - essentials.balance
    - battleground.join
    - sg.arena.join
    - sg.arena.vote
    - sg.arena.spectate
    - sg.lobby.join
    - sg.player
    - sg.arena.join*
  Head-Admin:
    default: false
    build: true
    prefix: '&7[&8Head&7-&3Admin&7]&f'
  Co~Owner:
    default: false
    build: true
    prefix: '&1[&4&lCo~Owner&1]'
    permissions:
    - '*'
  Owner:
    default: false
    build: true
    prefix: '&1[&4&lOwner&1]'
    permissions:
    - '*'
```
