### ISSUE TITLE
Inheritance issue

### ISSUE THREAD

**Issue by mksvco** [PEXPlugins/PermissionsEx#685]
```
group1:
worlds:
    world:
    - permission1
group2:
- inheritance:
    group1
worlds:
    world2:
        inheritance:
            - world1
```

using pretty much this config, people in group2 will not have permission1. Is that how it's supposed to work?
