### ISSUE TITLE
Bad perimsions , please help !

### ISSUE THREAD

**Issue by kiranvanek** [PEXPlugins/PermissionsEx#724]
these are my permissions : 

``` yaml
groups:
  Default:
        default: true
        info:
            prefix: '§7[§2Hrac§7]§3'
            suffix: '§f'
            build: true
        inheritance: 
        permissions:
            - 'essentials.help'
            - 'essentials.home'
            - 'essentials.motd'
            - 'essentials.rules'
            - 'essentials.sethome'
   - 'essentials.warp'
   - 'essentials.tpa'
   - 'essentials.tpaccept'
   - 'essentials.tpdeny'
   - 'essentials.warp.list'
   - 'essentials.repair'
   - 'essentials.repair.armor'
   - 'essentials.spawnmob.[pig]'
   - 'essentials.spawn
   - 'essentials.back
   - ' essentials.back.ondeath
   - 'essentials.delhome
  Majitel:
          default: false
        info:
            prefix: '§L§6[Majitel]§n'
            suffix: '§o'
            build: true
        inheritance:
        permissions:
            - '*'
  Moderator:
            default: false
        info:
            prefix: '§9[§1Moderator§9]§a'
            suffix: '§f'
            build: true
        inheritance:
        permissions:
            - '*'
  VIP:
            default: false
        info:
            prefix: '§2[§cV§eI§dP§2]§e'
            suffix: '§f'
            build: true
        inheritance:
        permissions:
            - 'essentials.help'
            - 'essentials.home'
            - 'essentials.motd'
            - 'essentials.rules'
            - 'essentials.sethome'
   - 'essentials.warp'
   - 'essentials.tpa'
   - 'essentials.tpaccept'
   - 'essentials.tpdeny'
   - 'essentials.warp.list'
   - 'essentials.repair'
   - 'essentials.repair.armor'
   - 'essentials.spawnmob.[pig]'
   - 'essentials.spawn
   - 'essentials.back
   - ' essentials.back.ondeath
   - 'essentials.delhome
  Stavitel:
            default: false
        info:
            prefix: '§4[§cStavitel§4]§a'
            suffix: '§f'
            build: true
        inheritance:
        permissions:
            - '*'
  Helper:
            default: false
        info:
            prefix: '§a[§2Helper§a]§b'
            suffix: '§f'
            build: true
        inheritance:
        permissions:
            - '*'
  Adminka:
            default: false
        info:
            prefix: '§c[§dAdminka§c]§5'
            suffix: '§f'
            build: true
        inheritance:
        permissions:
            - '*'
  SpoluMajitel:
            default: false
        info:
            prefix: '§b[§6SpoluMajitel§b]§7'
            suffix: '§f'
            build: true
        inheritance:
        permissions:
            - '*'
  Admin:
            default: false
        info:
            prefix: '§7[§cAdmin§7]§e'
            suffix: '§f'
            build: true
        inheritance:
        permissions:
            - '*'
  Majitelka:
            default: false
        info:
            prefix: '§L§6[Majitel]§n'
            suffix: '§f'
            build: true
        inheritance:
        permissions:
            - '*'
  Moderatorka:
            default: false
        info:
            prefix: '§L§6[Majitel]§n'
            suffix: '§f'
            build: true
        inheritance:
        permissions:
            - '*'
```

but somehow my pex ( version for 1.4.7 ) doesnt want to accept them when i apply these and i reload pex and connect to my server i see in the console some line errors and etc and when i write /pex groups its again at the back with only the default group
