### ISSUE TITLE
I cannot run any /pex commands

### ISSUE THREAD

**Issue by Micahjames65** [PEXPlugins/PermissionsEx#726]
When I try to run commands from my console.. I do /pex and it gives me a bunch of /pex commands.. When I do pex group Administrator user add Micahjames65 it gives me a bunch of /pex commands I try to do /pex groups and it gives me a bunch of commands none of the commands do what they are supposed to.. I cannot get my permissions to work! Here is my permissions file

``` yaml
groups:
  Guest:
    default: true
    prefix: '[Guest]&f '
    options:
      rank: '300'
    permissions:
    - modifyworld.*
    - redprotect.flag.all
    - essentials.hat
    - essentials.kits.[tools]
    - essentials.helpop
    - essentials.ignore
    - essentials.list
    - essentials.motd
    - essentials.msg
    - essentials.msg.url
    - essentials.realname
    - essentials.rules
    - essentials.seen
    - essentials.spawn
    - essentials.home
    - essentials.sethome
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.warp
    - essentials.warp.list
    - essentials.build
    - essentials.signs.create.disposal
    - essentials.signs.break.disposal
    - permissions.user.promote
    - essentials.balance.others
    - essentials.balancetop
    - essentials.ping
    - essentials.delhome
    - essentials.signs.use.balance
    - essentials.signs.use.buy
    - essentials.signs.use.disposal
    - essentials.signs.use.free
    - essentials.signs.use.heal
    - essentials.signs.use.sell
    - essentials.signs.use.warp

  Moderator:
    default: false
    prefix: '&f[&4Mod&f]&5 '
    options:
      rank: '50'
    permissions:
    - modifyworld.*
    - redprotect.flag.all
    - essentials.hat
    - essentials.kits.[tools]
    - essentials.helpop
    - essentials.ignore
    - essentials.list
    - essentials.motd
    - essentials.msg
    - essentials.msg.url
    - essentials.realname
    - essentials.rules
    - essentials.seen
    - essentials.spawn
    - essentials.home
    - essentials.sethome
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.warp
    - essentials.warp.list
    - essentials.build
    - essentials.signs.create.disposal
    - essentials.signs.break.disposal
    - essentials.fly
    - essentials.gamemode
    - essentials.give
    - essentials.oversizedstacks
    - essentials.heal
    - essentials.kits.*
    - essentials.repair
    - essentials.repair.armor
    - essentials.repair.enchanted
    - essentials.balance.others
    - essentials.balancetop
    - essentials.ping
    - essentials.delhome
    - essentials.signs.use.balance
    - essentials.signs.use.buy
    - essentials.signs.use.disposal
    - essentials.signs.use.free
    - essentials.signs.use.heal
    - essentials.signs.use.sell
    - essentials.signs.use.warp
    - essentials.signs.use.weather
    - essentials.signs.use.time
    - essentials.signs.use.spawnmob
    - essentials.signs.use.repair
    - essentials.signs.use.gamemode
    - essentials.signs.use.enchant
    - essentials.signs.use.protection

  Administrator:
    default: false
    prefix: '&2[&3Owner&2]
    options:
      rank: '25'
    permissions:
    - modifyworld.*
    - redprotect.flag.all
    - essentials.hat
    - essentials.kits.[tools]
    - essentials.helpop
    - essentials.ignore
    - essentials.list
    - essentials.motd
    - essentials.msg
    - essentials.msg.url
    - essentials.realname
    - essentials.rules
    - essentials.seen
    - essentials.spawn
    - essentials.home
    - essentials.sethome
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.warp
    - essentials.warp.list
    - essentials.build
    - essentials.signs.create.disposal
    - essentials.signs.break.disposal
    - essentials.bigtree
    - essentials.break
    - essentials.break.bedrock
    - essentials.enchant
    - essentials.exp
    - essentials.exp.give
    - essentials.exp.give.others
    - essentials.exp.others
    - essentials.bigtree
    - essentials.fly
    - essentials.gamemode
    - essentials.give
    - essentials.oversizedstacks
    - essentials.heal
    - essentials.kits.*
    - essentials.repair
    - essentials.repair.armor
    - essentials.repair.enchanted
    - essentials.break
    - essentials.enchant
    - essentials.exp
    - essentials.exp.give
    - essentials.exp.give.others
    - essentials.exp.others
    - essentials.exp.set
    - essentials.exp.set.others
    - essentials.feed
    - essentials.feed.others
    - essentials.firework
    - essentials.firework.fire
    - essentials.god
    - essentials.god.others
    - essentials.god.pvp
    - essentials.heal.cooldown.bypass
    - essentials.heal.others
    - essentials.item
    - essentials.time.set
    - essentials.unlimited
    - essentials.workbench
    - essentials.balance.others
    - essentials.balancetop
    - essentials.eco
    - essentials.afk
    - essentials.book
    - essentials.book.author
    - essentials.book.others
    - essentials.book.title
    - essentials.invsee.modify
    - essentials.invsee.preventmodify
    - essentials.invsee
    - essentials.fireball
    - essentials.enderchest
    - essentials.enderchest.modify
    - essentials.enderchest.others
    - essentials.lightning
    - essentials.kick
    - essentials.kick.exempt
    - essentials.kick.notify
    - essentials.kill
    - essentials.mute
    - essentials.mute.exempt
    - essentials.mute.notify
    - essentials.ping
    - essentials.spawnmob
    - essentials.spawnmob.*
    - essentials.sudo
    - essentials.sudo.exempt
    - essentials.tempban
    - essentials.tempban.exempt
    - essentials.tempban.offline
    - essentials.tempban.unlimited
    - essentials.thunder
    - essentials.jail.exempt
    - essentials.unban
    - essentials.unbanip
    - essentials.vanish
    - essentials.vanish.see
    - essentials.weather
    - essentials.setspawn
    - essentials.back
    - essentials.keepxp
    - essentials.back.ondeath
    - essentials.delwarp
    - essentials.tp
    - essentials.tp.others
    - essentials.top
    - essentials.sethome.others
    - essentials.setwarp
    - essentials.warp.overwrite.*
    - essentials.teleport.cooldown.bypass
    - essentials.warp.otherplayers
    - essentials.warps.*
    - essentials.signs.break.balance
    - essentials.signs.break.buy
    - essentials.signs.break.disposal
    - essentials.signs.break.enchant
    - essentials.signs.break.free
    - essentials.signs.break.gamemode
    - essentials.signs.break.heal
    - essentials.signs.break.info
    - essentials.signs.break.kit
    - essentials.signs.break.protection
    - essentials.signs.break.repair
    - essentials.signs.break.sell
    - essentials.signs.break.spawnmob
    - essentials.signs.break.time
    - essentials.signs.break.trade
    - essentials.signs.break.warp
    - essentials.signs.break.weather
    - essentials.signs.color
    - essentials.signs.create.balance
    - essentials.signs.create.buy
    - essentials.signs.create.disposal
    - essentials.signs.create.enchant
    - essentials.signs.create.free
    - essentials.signs.create.gamemode
    - essentials.signs.create.heal
    - essentials.signs.create.info
    - essentials.signs.create.kit
    - essentials.signs.create.protection
    - essentials.signs.create.repair
    - essentials.signs.create.sell
    - essentials.signs.create.spawnmob
    - essentials.signs.create.time
    - essentials.signs.create.trade
    - essentials.signs.create.warp
    - essentials.signs.create.weather
    - essentials.signs.format
    - essentials.signs.magic
    - essentials.signs.use.balance
    - essentials.signs.use.buy
    - essentials.signs.use.disposal
    - essentials.signs.use.free
    - essentials.signs.use.heal
    - essentials.signs.use.sell
    - essentials.signs.use.warp
    - essentials.signs.use.weather
    - essentials.signs.use.time
    - essentials.signs.use.spawnmob
    - essentials.signs.use.repair
    - essentials.signs.use.gamemode
    - essentials.signs.use.enchant
    - essentials.signs.use.protection

users: 
  micahjames65:
    group:
    - Administrator
```

```
This is what it gives me when I try to add me to the Administrator group
```

30.03 13:25:03 [Multicraft] Skipped 26 lines due to rate limit (40/s)
30.03 13:24:54 [Server] INFO /pex group <group> prefix [newprefix] [world] - Get or set <group> prefix.
30.03 13:24:54 [Server] INFO /pex group <group> toggle debug - Toggle debug mode for group
30.03 13:24:54 [Server] INFO /pex group <group> weight [weight] - Print or set group weight
30.03 13:24:54 [Server] INFO /pex group - List all registered groups (alias)
30.03 13:24:54 [Server] INFO /pex groups - List all registered groups (alias)
30.03 13:24:54 [Server] INFO /pex groups list [world] - List all registered groups
30.03 13:24:54 [Server] INFO /pex group <group> swap <permission> <targetPermission> [world] - Swap <permission> and <targetPermission> in permission list. Could be number or permission itself
30.03 13:24:54 [Server] INFO /pex users cleanup <group> [threshold] - Clean users of specified group, which last login was before threshold (in days). By default threshold is 30 days.
30.03 13:24:54 [Server] INFO /pex user <user> group remove <group> [world] - Remove <user> from <group>
30.03 13:24:54 [Server] INFO /pex user <user> group set <group> [world] - Set <group> for <user>
30.03 13:24:54 [Server] INFO /pex user <user> group add <group> [world] [lifetime] - Add <user> to <group>
30.03 13:24:54 [Server] INFO /pex user <user> group list [world] - List all <user> groups
30.03 13:24:54 [Server] INFO /pex user <user> set <option> <value> [world] - Set <option> to <value> in [world]
30.03 13:24:54 [Server] INFO /pex user <user> timed remove <permission> [world] - Remove timed <permission> from <user> in [world]
30.03 13:24:54 [Server] INFO /pex user <user> timed add <permission> [lifetime] [world] - Add timed <permissions> to <user> for [lifetime] seconds in [world]
30.03 13:24:54 [Server] INFO /pex user <user> swap <permission> <targetPermission> [world] - Swap <permission> and <targetPermission> in permission list. Could be number or permission itself
30.03 13:24:54 [Server] INFO /pex user <user> remove <permission> [world] - Remove permission from <user> in [world]
30.03 13:24:54 [Server] INFO /pex user <user> add <permission> [world] - Add <permission> to <user> in [world]
30.03 13:24:54 [Server] INFO /pex user <user> delete - Remove <user>
30.03 13:24:54 [Server] INFO /pex user <user> get <option> [world] - Toggle debug only for <user>
30.03 13:24:54 [Server] INFO /pex user <user> check <permission> [world] - Checks player for <permission>
30.03 13:24:54 [Server] INFO /pex user <user> toggle debug - Toggle debug only for <user>
30.03 13:24:54 [Server] INFO /pex user <user> suffix [newsuffix] [world] - Get or set <user> suffix
30.03 13:24:54 [Server] INFO /pex user <user> prefix [newprefix] [world] - Get or set <user> prefix
30.03 13:24:54 [Server] INFO /pex user <user> superperms - List user actual superperms
30.03 13:24:54 [Server] INFO /pex user <user> list [world] - List user permissions
30.03 13:24:54 [Server] INFO /pex user <user> - List user permissions (list alias)
30.03 13:24:54 [Server] INFO /pex user - List all registered users (alias)
30.03 13:24:54 [Server] INFO /pex users - List all registered users (alias)
30.03 13:24:54 [Server] INFO /pex users list - List all registered users
30.03 13:24:54 [Server] INFO /pex help [page] [count] - PermissionsEx commands help
30.03 13:24:54 [Server] INFO /pex toggle debug - Enable/disable debug mode
30.03 13:24:54 [Server] INFO /pex dump <backend> <filename> - Dump users/groups to selected <backend> format
30.03 13:24:54 [Server] INFO /pex hierarchy [world] - Print complete user/group hierarchy
30.03 13:24:54 [Server] INFO /pex backend <backend> - Change permission backend on the fly (Use with caution!)
30.03 13:24:54 [Server] INFO /pex backend - Print currently used backend
30.03 13:24:54 [Server] INFO /pex config <node> [value] - Print or set <node> [value]
30.03 13:24:54 [Server] INFO /pex reload - Reload environment
30.03 13:24:54 [Server] INFO /pex - Display help

```

```

Thank you for taking the time to read my problem!
~Micah
