### ISSUE TITLE
Pex Commands only giving command list

### ISSUE THREAD

**Issue by graywolf19** [PEXPlugins/PermissionsEx#765]
I've configured my permissions file. It'll be at the bottom of this ticket. Whenever I try to issue a command with the prefix /pex, the server console and client just replies with the full /help permissionsex parsing. I've tried to run it bare with the newest bukkit beta and pex only to no avail.

permissions.yml file:

``` yaml
groups:
  Newbie:
    default: true
    permissions:
    - modifyworld.*
    - portal.use
    - monsterbox.eggset
    - essentials.kit.tools
    - essentials.kit
    - essentials.hat
    - essentials.balance
    - essentials.balance.others
    - essentials.balancetop
    - essentials.pay
    - essentials.afk
    - essentials.afk.auto
    - essentials.help
    - essentials.ignore
    - essentials.motd
    - essentials.msg.url
    - essentials.msg
    - essentials.kill
    - essentials.suicide
    - essentials.ban.notify
    - essentials.kick.notify
    - essentials.mute.notify
    - essentials.ping
    - essentials.home
    - essentials.tpa
    - essentials.tpdeny
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.chat.url
    - fe.balance
    - fe.balance.other
    - fe.sent
    - fe.top
    - fe.?
    - essentials.spawn
    - commandsigns.use.*
    - pvparena.user
    - whatisit.use
    - factions.kit.fullplayer
    - auction.start
    - auction.bid
    - randomteleporter.use.sign
    prefix: ' &7[Newbie]'
    suffix: ' &f:&f'
  Moderator:
    permissions:
    - essentials.kick
    - essentials.kick.exempt
    - essentials.chat.ignoreexempt
    - essentials.mute
    - essentials.mute.exempt
    - essentials.banip
    - essentials.ban.exempt
    - essentials.ban
    - essentials.ban.offline
    - essentials.tempban
    - essentials.tempban.exempt
    - essentials.tempban.offline
    - essentials.unban
    - essentials.unbanip
    prefix: ' &4[Moderator]'
    suffix: ' &f:&f'
    inheritance:
    - Newbie
  Admin:
    permisisons:
    - '*'
    prefix: ' &1[Admin]'
    suffix: ' ' &f:&f'
  Owner:
    permissions:
    - '*'
    prefix: ' &a[Owner]'
    suffix: ' &f:&f'
```
