### ISSUE TITLE
No Permissions working!? 

### ISSUE THREAD

**Issue by lippoliv** [PEXPlugins/PermissionsEx#772]
Hey there,
I can't do something, after activating PermissionsEx (new Version from today).

Here's the Permissions-File (generated through McMyAdmin)
    #Permissions.yml - Written by McMyAdmin v2.4.3.2

```
users:
    gilmorelady:
        group:
          - 'Regulars'
    goldi2412:
        group:
          - 'Regulars'
    benjamin83:
        group:
          - 'Regulars'
    kevka1993:
        group:
          - 'Regulars'
    lippoliv:
        group:
          - 'Regulars'
groups:
    Admin:
        default: false
        permissions:
          - '*'
          - 'bukkit.command.*'
        inheritance:
          - 'Moderator'
        worlds: []
        prefix: '&4'
        suffix: '&f'
    Spieler:
        default: false
        permissions:
          - 'jobs.*'
          - 'iConomy.holdings'
          - 'iConomy.payment'
          - 'colorme.self.*'
          - 'modifyworld.*'
        inheritance:
          - 'Gast'
        worlds: []
        prefix: '&a'
        suffix: '&f'
    Gast:
        default: true
        permissions:
          - '-jobs.*'
          - '-iConomy.holdings'
        inheritance:
          - ''
        worlds: []
        prefix: '&f'
        suffix: '&f'
    Moderator:
        default: false
        permissions: []
        inheritance:
          - 'Spieler'
        worlds: []
        prefix: '&1'
        suffix: '&f'
```

What do I do wrong? I had PermissionsEx several times running correctly...!?
