### ISSUE TITLE
PEX Problems!

### ISSUE THREAD

**Issue by Speqtacles** [PEXPlugins/PermissionsEx#773]
I've got PEX installed but when I go into my server it does not put my friend into the default group and it does not give me all permissions, please help?

``` yaml
groups:
  Owner:
    default: false
    prefix: '&4'
    permissions:
    - '*'
    options:
      rank: '0'
  Administrator:
    default: false
    prefix: '&c'
    inheritance:
    - Moderator
    permissions:
    options:
      rank: '100'
  Moderator:
    default: false
    prefix: '&1'
    inheritance:
    - VIP
    permissions:
    options:
      rank: '200'
  VIP:
    default: false
    prefix: '&9'
    inheritance:
    - Builder
    permissions:
    options:
      rank: '300'
  Builder:
    default: false
    prefix: '&b'
    inheritance:
    - Guest
    permissions:
    options:
      rank: '400'
  Guest:
    default: true
    permissions:
    options:
      rank: '500'

  users:
         Speqs:
               group:
               - Owner
```
