### ISSUE TITLE
PEX refuses to start up

### ISSUE THREAD

**Issue by opdelta** [PEXPlugins/PermissionsEx#783]
Hello, I recently installed PermissionsEX, and when I wanted to start the plugin, I got this error:

12.06 14:10:11 [Server] INFO Preparing start region for level 2 (Seed: 640834560002196079)
12.06 14:10:10 [Server] INFO Preparing spawn area: 0%
12.06 14:10:10 [Server] INFO Preparing start region for level 1 (Seed: 640834560002196079)
12.06 14:10:09 [Server] INFO Preparing spawn area: 29%
12.06 14:10:09 [Multicraft] Skipped 25 lines due to rate limit (30/s)
12.06 14:10:08 [Server] INFO in "<string>", line 40, column 1:
12.06 14:10:08 [Server] INFO found character    '\t' that cannot start any token
12.06 14:10:08 [Server] INFO Caused by: while scanning for the next token
12.06 14:10:08 [Server] INFO ... 12 more
12.06 14:10:08 [Server] INFO at ru.tehkode.permissions.backends.FileBackend.reload(FileBackend.java:232)
12.06 14:10:08 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:105)
12.06 14:10:08 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:138)
12.06 14:10:08 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
12.06 14:10:08 [Server] INFO ^
12.06 14:10:08 [Server] INFO in "<string>", line 40, column 1:
12.06 14:10:08 [Server] INFO found character    '\t' that cannot start any token
12.06 14:10:08 [Server] INFO Caused by: org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token
12.06 14:10:08 [Server] INFO at net.minecraft.server.v1_5_R3.ThreadServerApplication.run(SourceFile:573)
12.06 14:10:08 [Server] INFO at net.minecraft.server.v1_5_R3.MinecraftServer.run(MinecraftServer.java:382)
12.06 14:10:08 [Server] INFO at net.minecraft.server.v1_5_R3.DedicatedServer.init(DedicatedServer.java:106)
12.06 14:10:08 [Server] INFO at net.minecraft.server.v1_5_R3.DedicatedPlayerList.<init>(SourceFile:11)
12.06 14:10:08 [Server] INFO at net.minecraft.server.v1_5_R3.PlayerList.<init>(PlayerList.java:55)
12.06 14:10:08 [Server] INFO at org.bukkit.craftbukkit.v1_5_R3.CraftServer.<init>(CraftServer.java:217)
12.06 14:10:08 [Server] INFO at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins(CraftServer.java:244)
12.06 14:10:08 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.onLoad(PermissionsEx.java:83)
12.06 14:10:08 [Server] INFO at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:55)
12.06 14:10:08 [Server] INFO at ru.tehkode.permissions.PermissionManager.initBackend(PermissionManager.java:492)
12.06 14:10:08 [Server] INFO at ru.tehkode.permissions.PermissionManager.setBackend(PermissionManager.java:427)
12.06 14:10:08 [Server] INFO at ru.tehkode.permissions.backends.FileBackend.initialize(FileBackend.java:84)
12.06 14:10:08 [Server] INFO at ru.tehkode.permissions.backends.FileBackend.reload(FileBackend.java:249)
12.06 14:10:08 [Server] INFO java.lang.IllegalStateException: Error loading permissions file
12.06 14:10:08 [Server] SEVERE Error occurred with PermissionsEx! Please post it to https://github.com/PEXPlugins/PermissionsEx/issues/new?title=&body=%23%23%23+Description+%23%23%23%0A%0A%5BInsert+description+of+issue+here%5D%0A%23%23%23+What+PEX+Saw+%23%23%23%0A%0A**Reason%3A**+While+setting+backend%0A%0A**Stacktrace%3A**%0A%60%60%60%0Ajava.lang.IllegalStateException%3A+Error+loading+permissions+file%0A%09at+ru.tehkode.permissions.backends.FileBackend.reload%28FileBackend.java%3A249%29%0A%09at+ru.tehkode.permissions.backends.FileBackend.initialize%28FileBackend.java%3A84%29%0A%09at+ru.tehkode.permissions.PermissionManager.setBackend%28PermissionManager.java%3A427%29%0A%09at+ru.tehkode.permissions.PermissionManager.initBackend%28PermissionManager.java%3A492%29%0A%09at+ru.tehkode.permissions.PermissionManager.%3Cinit%3E%28PermissionManager.java%3A55%29%0A%09at+ru.tehkode.permissions.bukkit.PermissionsEx.onLoad%28PermissionsEx.java%3A83%29%0A%09at+org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugins%28CraftServer.java%3A244%29%0A%09at+org.bukkit.craftbukkit.v1_5_R3.CraftServer.%3Cinit%3E%28CraftServer.java%3A217%29%0A%09at+net.minecraft.server.v1_5_R3.PlayerList.%3Cinit%3E%28PlayerList.java%3A55%29%0A%09at+net.minecraft.server.v1_5_R3.DedicatedPlayerList.%3Cinit%3E%28SourceFile%3A11%29%0A%09at+net.minecraft.server.v1_5_R3.DedicatedServer.init%28DedicatedServer.java%3A106%29%0A%09at+net.minecraft.server.v1_5_R3.MinecraftServer.run%28MinecraftServer.java%3A382%29%0A%09at+net.minecraft.server.v1_5_R3.ThreadServerApplication.run%28SourceFile%3A573%29%0ACaused+by%3A+org.bukkit.configuration.InvalidConfigurationException%3A+while+scanning+for+the+next+token%0Afound+character+%09%27%5Ct%27+that+cannot+start+any+token%0A+in+%22%3Cstring%3E%22%2C+line+40%2C+column+1%3A%0A++++%09%09%09%0A++++%5E%0A%0A%09at+org.bukkit.configuration.file.YamlConfiguration.loadFromString%28YamlConfiguration.java%3A55%29%0A%09at+org.bukkit.configuration.file.FileConfiguration.load%28FileConfiguration.java%3A138%29%0A%09at+org.bukkit.configuration.file.FileConfiguration.load%28FileConfiguration.java%3A105%29%0A%09at+ru.tehkode.permissions.backends.FileBackend.reload%28FileBackend.java%3A232%29%0A%09...+12+more%0ACaused+by%3A+while+scanning+for+the+next+token%0Afound+character+%09%27%5Ct%27+that+cannot+start+any+token%0A+in+%22%3Cstring%3E%22%2C+line+40%2C+column+1%3A%0A++++%09%09%09%0A++++%5E%0A%0A%09at+org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens%28ScannerImpl.java%3A358%29%0A%09at+org.yaml.snakeyaml.scanner.ScannerImpl.checkToken%28ScannerImpl.java%3A179%29%0A%09at+org.yaml.snakeyaml.parser.ParserImpl%24ParseBlockMappingKey.produce%28ParserImpl.java%3A563%29%0A%09at+org.yaml.snakeyaml.parser.ParserImpl.peekEvent%28ParserImpl.java%3A161%29%0A%09at+org.yaml.snakeyaml.parser.ParserImpl.checkEvent%28ParserImpl.java%3A146%29%0A%09at+org.yaml.snakeyaml.composer.Composer.composeMappingNode%28Composer.java%3A230%29%0A%09at+org.yaml.snakeyaml.composer.Composer.composeNode%28Composer.java%3A160%29%0A%09at+org.yaml.snakeyaml.composer.Composer.composeMappingNode%28Composer.java%3A237%29%0A%09at+org.yaml.snakeyaml.composer.Composer.composeNode%28Composer.java%3A160%29%0A%09at+org.yaml.snakeyaml.composer.Composer.composeMappingNode%28Composer.java%3A237%29%0A%09at+org.yaml.snakeyaml.composer.Composer.composeNode%28Composer.java%3A160%29%0A%09at+org.yaml.snakeyaml.composer.Composer.composeMappingNode%28Composer.java%3A237%29%0A%09at+org.yaml.snakeyaml.composer.Composer.composeNode%28Composer.java%3A160%29%0A%09at+org.yaml.snakeyaml.composer.Composer.composeDocument%28Composer.java%3A123%29%0A%09at+org.yaml.snakeyaml.composer.Composer.getSingleNode%28Composer.java%3A106%29%0A%09at+org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData%28BaseConstructor.java%3A121%29%0A%09at+org.yaml.snakeyaml.Yaml.loadFromReader%28Yaml.java%3A480%29%0A%09at+org.yaml.snakeyaml.Yaml.load%28Yaml.java%3A399%29%0A%09at+org.bukkit.configuration.file.YamlConfiguration.loadFromString%28YamlConfiguration.java%3A53%29%0A%09...+15+more%0A%60%60%60%0A%23%23%23+PEX+configuration+%23%23%23%0A%60%60%60yaml%0Apermissions%3A%0A++backend%3A+file%0A++backends%3A%0A++++file%3A%0A++++++file%3A+permissions.yml%0A++superperms%3A+%7B%7D%0A%60%60%60%0A%23%23%23+Permissions+database+%23%23%23%0A%60%60%60yaml%0Agroups%3A%0A++++Default%3A%0A++++++++default%3A+true%0A++++++++permissions%3A%0A++++++++-+essentials.afk%0A++++++++-+essentials.balance%0A++++++++-+essentials.balance.others%0A++++++++-+essentials.balancetop%0A++++++++-+essentials.chat.color%0A++++++++-+essentials.chat.shout%0A++++++++-+essentials.chat.question%0A++++++++-+essentials.home%0A++++++++-+essentials.mail%0A++++++++-+essentials.mail.send%0A++++++++-+essentials.msg%0A++++++++-+essentials.pay%0A++++++++-+essentials.ping%0A++++++++-+essentials.sethome%0A++++++++-+essentials.signs.use.*%0A++++++++-+essentials.signs.create.disposal%0A++++++++-+essentials.signs.create.mail%0A++++++++-+essentials.signs.create.protection%0A++++++++-+essentials.signs.create.trade%0A++++++++-+essentials.signs.break.disposal%0A++++++++-+essentials.signs.break.mail%0A++++++++-+essentials.signs.break.protection%0A++++++++-+essentials.signs.break.trade%0A++++++++-+essentials.suicide%0A++++++++-+essentials.time%0A++++++++-+essentials.tpa%0A++++++++-+essentials.tpaccept%0A++++++++-+essentials.tpahere%0A++++++++-+essentials.tpdeny%0A++++++++-+essentials.warp%0A++++++++-+essentials.worth%0A++++++++prefix%3A+%27%262%27%0A++++++++options%3A%0A++++++++++++build%3A+true%0A++++++++++++rank%3A+%271000%27%0A%09%09%09%0A++++Officer%3A%0A++++++++permissions%3A%0A++++++++-+essentials.afk%0A++++++++-+essentials.balance%0A++++++++-+essentials.balance.others%0A++++++++-+essentials.balancetop%0A++++++++-+essentials.chat.color%0A++++++++-+essentials.chat.shout%0A++++++++-+essentials.chat.question%0A++++++++-+essentials.home%0A++++++++-+essentials.mail%0A++++++++-+essentials.mail.send%0A++++++++-+essentials.msg%0A++++++++-+essentials.pay%0A++++++++-+essentials.ping%0A++++++++-+essentials.sethome%0A++++++++-+essentials.signs.use.*%0A++++++++-+essentials.signs.create.disposal%0A++++++++-+essentials.signs.create.mail%0A++++++++-+essentials.signs.create.protection%0A++++++++-+essentials.signs.create.trade%0A++++++++-+essentials.signs.break.disposal%0A++++++++-+essentials.signs.break.mail%0A++++++++-+essentials.signs.break.protection%0A++++++++-+essentials.signs.break.trade%0A++++++++-+essentials.suicide%0A++++++++-+essentials.time%0A++++++++-+essentials.tpa%0A++++++++-+essentials.tpaccept%0A++++++++-+essentials.tpahere%0A++++++++-+essentials.tpdeny%0A++++++++-+essentials.warp%0A++++++++-+essentials.worth%0A++++++++-+essentials.warp.list%0A++++++++-+essentials.sethome.bed%0A++++++++-+essentials.home.multiple.2%0A++++++++-+essentials.tptoggle%0A++++++++prefix%3A+%27%261Officer%26f+%27%0A++++++++options%3A%0A++++++++++++build%3A+true%0A++++++++++++rank%3A+%27900%27%0A++++Moderator%3A%0A++++++++permissions%3A%0A++++++++-+essentials.ban%0A++++++++-+essentials.ban.notify%0A++++++++-+essentials.banip%0A++++++++-+essentials.broadcast%0A++++++++-+essentials.clearinventory%0A++++++++-+essentials.delwarp%0A++++++++-+essentials.eco.loan%0A++++++++-+essentials.ext%0A++++++++-+essentials.getpos%0A++++++++-+essentials.helpop.recieve%0A++++++++-+essentials.home.others%0A++++++++-+essentials.invsee%0A++++++++-+essentials.jails%0A++++++++-+essentials.jump%0A++++++++-+essentials.kick%0A++++++++-+essentials.kick.notify%0A++++++++-+essentials.kill%0A++++++++-+essentials.mute%0A++++++++-+essentials.nick.others%0A++++++++-+essentials.realname%0A++++++++-+essentials.setwarp%0A++++++++-+essentials.signs.create.*%0A++++++++-+essentials.signs.break.*%0A++++++++-+essentials.spawner%0A++++++++-+essentials.thunder%0A++++++++-+essentials.time%0A++++++++-+essentials.time.set%0A++++++++-+essentials.protect.alerts%0A++++++++-+essentials.protect.admin%0A++++++++-+essentials.protect.ownerinfo%0A++++++++-+essentials.ptime%0A++++++++-+essentials.ptime.others%0A++++++++-+essentials.togglejail%0A++++++++-+essentials.top%0A++++++++-+essentials.tp%0A++++++++-+essentials.tphere%0A++++++++-+essentials.tppos%0A++++++++-+essentials.tptoggle%0A++++++++-+essentials.unban%0A++++++++-+essentials.unbanip%0A++++++++-+essentials.weather%0A++++++++-+essentials.whois%0A++++++++-+essentials.world%0A++++++++-+permissions.user.promote.default%0A++++++++-+permissions.user.demote.default%0A++++++++-+permissions.manage.membership%0A++++++++inheritance%3A%0A++++++++-+builder%0A++++++++prefix%3A+%27%265%27%0A++++++++options%3A%0A++++++++++++build%3A+true%0A++++++++++++rank%3A+%27200%27%0A++++Admin%3A%0A++++++++permissions%3A%0A++++++++-+-essentials.backup%0A++++++++-+-essentials.essentials%0A++++++++-+-essentials.setspawn%0A++++++++-+-essentials.reloadall%0A++++++++-+essentials.*%0A++++++++-+permissions.manage.users%0A++++++++-+permissions.manage.users.permissions%0A++++++++-+permissions.manage.users.permissions.timed%0A++++++++inheritance%3A%0A++++++++-+moderator%0A++++++++prefix%3A+%27%26c%27%0A++++++++options%3A%0A++++++++++++build%3A+true%0A++++++++++++rank%3A+%27100%27%0A++++Owner%3A%0A++++++++permissions%3A%0A++++++++-+%27*%27%0A++++++++inheritance%3A%0A++++++++-+admin%0A++++++++prefix%3A+%27%264%27%0A++++++++options%3A%0A++++++++++++build%3A+true%0A++++++++++++rank%3A+%270%27%60%60%60%0A§r. Full error:
12.06 14:10:08 [Server] INFO Preparing level "world"
12.06 14:10:08 [Multicraft] Skipped 8 lines due to rate limit (30/s)
12.06 14:10:07 [Server] INFO Loading Factions v1.8.2
12.06 14:10:07 [Server] INFO Loading EssentialsAntiBuild vPre2.11.1.2
12.06 14:10:07 [Server] INFO Loading Enjin Minecraft Plugin v2.4.5
12.06 14:10:07 [Server] INFO Loading EssentialsSpawn vPre2.11.1.2
12.06 14:10:07 [Server] INFO Loading EssentialsProtect vPre2.11.1.2
12.06 14:10:07 [Server] INFO Loading ChatManager v1.19.1
12.06 14:10:07 [Server] INFO Loading Essentials vPre2.11.1.2
12.06 14:10:07 [Server] INFO Loading WorldGuard v5.7.4
12.06 14:10:07 [Server] INFO ^
12.06 14:10:07 [Server] INFO in "<string>", line 40, column 1:
12.06 14:10:07 [Server] INFO found character    '\t' that cannot start any token
12.06 14:10:07 [Server] INFO while scanning for the next token
12.06 14:10:07 [Server] WARNING Error loading permissions file:
12.06 14:10:07 [Server] INFO Initializing file backend
12.06 14:10:07 [Server] INFO Loading PermissionsEx v1.19.6

If my permissions.yml file could help there you go:

``` yaml
groups:
    Default:
        default: true
        permissions:
        - essentials.afk
        - essentials.balance
        - essentials.balance.others
        - essentials.balancetop
        - essentials.chat.color
        - essentials.chat.shout
        - essentials.chat.question
        - essentials.home
        - essentials.mail
        - essentials.mail.send
        - essentials.msg
        - essentials.pay
        - essentials.ping
        - essentials.sethome
        - essentials.signs.use.*
        - essentials.signs.create.disposal
        - essentials.signs.create.mail
        - essentials.signs.create.protection
        - essentials.signs.create.trade
        - essentials.signs.break.disposal
        - essentials.signs.break.mail
        - essentials.signs.break.protection
        - essentials.signs.break.trade
        - essentials.suicide
        - essentials.time
        - essentials.tpa
        - essentials.tpaccept
        - essentials.tpahere
        - essentials.tpdeny
        - essentials.warp
        - essentials.worth
        prefix: '&2'
        options:
            build: true
            rank: '1000'

    Officer:
        permissions:
        - essentials.afk
        - essentials.balance
        - essentials.balance.others
        - essentials.balancetop
        - essentials.chat.color
        - essentials.chat.shout
        - essentials.chat.question
        - essentials.home
        - essentials.mail
        - essentials.mail.send
        - essentials.msg
        - essentials.pay
        - essentials.ping
        - essentials.sethome
        - essentials.signs.use.*
        - essentials.signs.create.disposal
        - essentials.signs.create.mail
        - essentials.signs.create.protection
        - essentials.signs.create.trade
        - essentials.signs.break.disposal
        - essentials.signs.break.mail
        - essentials.signs.break.protection
        - essentials.signs.break.trade
        - essentials.suicide
        - essentials.time
        - essentials.tpa
        - essentials.tpaccept
        - essentials.tpahere
        - essentials.tpdeny
        - essentials.warp
        - essentials.worth
        - essentials.warp.list
        - essentials.sethome.bed
        - essentials.home.multiple.2
        - essentials.tptoggle
        prefix: '&1Officer&f '
        options:
            build: true
            rank: '900'
    Moderator:
        permissions:
        - essentials.ban
        - essentials.ban.notify
        - essentials.banip
        - essentials.broadcast
        - essentials.clearinventory
        - essentials.delwarp
        - essentials.eco.loan
        - essentials.ext
        - essentials.getpos
        - essentials.helpop.recieve
        - essentials.home.others
        - essentials.invsee
        - essentials.jails
        - essentials.jump
        - essentials.kick
        - essentials.kick.notify
        - essentials.kill
        - essentials.mute
        - essentials.nick.others
        - essentials.realname
        - essentials.setwarp
        - essentials.signs.create.*
        - essentials.signs.break.*
        - essentials.spawner
        - essentials.thunder
        - essentials.time
        - essentials.time.set
        - essentials.protect.alerts
        - essentials.protect.admin
        - essentials.protect.ownerinfo
        - essentials.ptime
        - essentials.ptime.others
        - essentials.togglejail
        - essentials.top
        - essentials.tp
        - essentials.tphere
        - essentials.tppos
        - essentials.tptoggle
        - essentials.unban
        - essentials.unbanip
        - essentials.weather
        - essentials.whois
        - essentials.world
        - permissions.user.promote.default
        - permissions.user.demote.default
        - permissions.manage.membership
        inheritance:
        - builder
        prefix: '&5'
        options:
            build: true
            rank: '200'
    Admin:
        permissions:
        - -essentials.backup
        - -essentials.essentials
        - -essentials.setspawn
        - -essentials.reloadall
        - essentials.*
        - permissions.manage.users
        - permissions.manage.users.permissions
        - permissions.manage.users.permissions.timed
        inheritance:
        - moderator
        prefix: '&c'
        options:
            build: true
            rank: '100'
    Owner:
        permissions:
        - '*'
        inheritance:
        - admin
        prefix: '&4'
        options:
            build: true
            rank: '0'
```

I used Essentials's PEX sample file.
