### ISSUE TITLE
Bug de commande PermissionsEx

### ISSUE THREAD

**Issue by toto872208** [PEXPlugins/PermissionsEx#794]
``` yaml
groups:
  default:
    default: true
    permissions:
    - ChestShop.shop.use
    - creativegates.use
    - modifyworld.*
    - -bukkit.command.kill
    - creativegates.use
    - bukkit.broadcast.user
    - -bukkit.command.plugins
    - essentials.help
    - essentials.helpop
    - essentials.list
    - essentials.motd
    - essentials.rules
    - essentials.spawn
    - essentials.jail.allow.help
    - essentials.jail.allow.helpop
    - essentials.jail.allow.rules
    - essentials.afk
    - essentials.afk.auto
    - essentials.back
    - essentials.back.ondeath
    - essentials.balance
    - essentials.balance.others
    - essentials.balancetop
    - essentials.book
    - essentials.chat.color
    - essentials.chat.format
    - essentials.chat.shout
    - essentials.chat.question
    - essentials.compass
    - essentials.delhome
    - essentials.depth
    - essentials.getpos
    - essentials.hat
    - essentials.home
    - essentials.ignore
    - essentials.itemdb
    - essentials.kits.tools
    - essentials.mail
    - essentials.mail.send
    - essentials.me
    - essentials.msg
    - essentials.msg.color
    - essentials.nick
    - essentials.pay
    - essentials.ping
    - essentials.powertool
    - essentials.powertooltoggle
    - essentials.protect
    - essentials.recipe
    - essentials.seen
    - essentials.sethome
    - essentials.sethome.multiple
    - essentials.signs.use.*
    - essentials.signs.create.disposal
    - essentials.signs.create.mail
    - essentials.signs.create.protection
    - essentials.signs.create.trade
    - essentials.signs.break.disposal
    - essentials.signs.break.mail
    - essentials.signs.break.trade
    - essentials.suicide
    - essentials.time
    - essentials.tpa
    - essentials.tpahere
    - essentials.tpdeny
    - essentials.warp
    - essentials.warp.list
    - essentials.worth
    - essentials.jail.allow.mail
    - essentials.jail.allow.seen
    - factions.admin
    - factions.claim
    - factions.chat
    - factions.create
    - factions.deinvite
    - factions.description
    - factions.disband
    - factions.home
    - factions.invite
    - factions.join
    - factions.kick
    - factions.leave
    - factions.list
    - factions.open
    - factions.relation
    - factions.sethome
    - factions.show
    - factions.tag
    - factions.title
    - factions.unclaim
    - factions.unclaimall
    prefix: '&e[Citoyen] '
    options:
      rank: '900'
      build: true
  animateur:
    default: false
    permissions:
    - bukkit.command.gamemode
    inheritance:
    - default
    prefix: '&b[Animateur] '
    options:
      rank: '850'
      build: true
  moderateur:
    default: false
    permissions:
    - bukkit.command.ban
    - bukkit.command.ban.ip
    - bukkit.command.ban.player
    - bukkit.command.gamemode
    - bukkit.command.kick
    - bukkit.command.unban
    - bukkit.command.unban.ip
    - bukkit.command.unban.player
    - -essentials.spawner.enderdragon
    - essentials.afk.kickexempt
    - essentials.ban
    - essentials.ban.notify
    - essentials.banip
    - essentials.book.title
    - essentials.book.others
    - essentials.broadcast
    - essentials.chat.url
    - essentials.chat.magic
    - essentials.clearinventory
    - essentials.delwarp
    - essentials.eco.loan
    - essentials.exp.others
    - essentials.ext
    - essentials.fly
    - essentials.fly.safelogin
    - essentials.getpos
    - essentials.getpos.others
    - essentials.helpop.recieve
    - essentials.home.others
    - essentials.invsee
    - essentials.jails
    - essentials.jump
    - essentials.kick
    - essentials.kick.notify
    - essentials.kill
    - essentials.kits.*
    - essentials.msg.magic
    - essentials.mute
    - essentials.mute.notify
    - essentials.nick.color
    - essentials.nick.others
    - essentials.realname
    - essentials.seen.banreason
    - essentials.seen.extra
    - essentials.setwarp
    - essentials.signs.create.*
    - essentials.signs.break.*
    - essentials.spawner
    - essentials.spawner.*
    - essentials.thunder
    - essentials.time
    - essentials.time.set
    - essentials.protect.alerts
    - essentials.protect.admin
    - essentials.protect.ownerinfo
    - essentials.ptime
    - essentials.ptime.others
    - essentials.togglejail
    - essentials.top
    - essentials.tp
    - essentials.tp.others
    - essentials.tphere
    - essentials.tppos
    - essentials.tptoggle
    - essentials.unban
    - essentials.unbanip
    - essentials.vanish
    - essentials.vanish.effect
    - essentials.warps.*
    - essentials.weather
    - essentials.whois
    - essentials.workbench
    - essentials.world
    - essentials.worlds.*
    - essentials.jail.allow.jails
    - essentials.jail.allow.togglejail
    inheritance:
    - animateur
    prefix: '&5[Moderateur] '
    options:
      rank: '800'
      build: true
  admin:
    default: false
    permissions:
    - permissions.*
    inheritance:
    - moderateur
    prefix: '&c[Administrateur] '
    options:
      rank: '2'
      build: true
  owner:
    default: false
    permissions:
    - permissions.*
    inheritance:
    - admin
    prefix: '&4[Fondateur] '
    options:
      rank: '1'
      build: true
```

Quelqu'un pourrait-il me dire ce qui ne va pas dans mon code de programmation svp?
