### ISSUE TITLE
Ridiculous Error, tried Everything to Fix!

### ISSUE THREAD

**Issue by INeedToGetaLife** [PEXPlugins/PermissionsEx#813]
Says Error in PermissionsEx? I Dont see an error, I have been looking forever!

``` yaml
groups:
  Starter:
    default: true
    permissions:
    - essentials.kit
    - essentials.near
    - masterpromote.rank.buy.Beginner
    - sg.arena.join.*
    - sg.arena.vote
    - sg.arena.spectate
    - sg.lobby.join
    prefix: '&6Starter&7'
  Beginner:
    default: false
    permissions:
    - essentials.kit
    - essentials.kits.beginner 
    - sg.arena.join.*
    - sg.arena.vote
    - sg.arena.spectate
    - sg.lobby.join    
    - essentials.kit
    - essentials.kits.beginner
    - masterpromote.rank.buy.Amateur
    prefix: '&2Beginner&7'
  Amateur:
    default: false
    permissions:
    - essentials.kit
    - essentials.kits.amateur  
    - sg.arena.join.*
    - sg.arena.vote
    - sg.arena.spectate
    - sg.lobby.join    
    - masterpromote.rank.buy.Pro
    prefix: '&3Amateur&7'
  Pro:
    default: false
    permissions:
    - essentials.kit
    - essentials.kits.pro      
    - sg.arena.join.*
    - sg.arena.vote
    - sg.arena.spectate
    - sg.lobby.join    
    - masterpromote.rank.buy.Expert
    prefix: '&8Pro&7'
  Expert:
    default: false
    permissions:
    - essentials.kit
    - essentials.kits.expert   
    - sg.arena.join.*
    - sg.arena.vote
    - sg.arena.spectate
    - sg.lobby.join    
    - masterpromote.rank.buy.Legend
    prefix: '&bExpert&7'
  Legend:
    default: false
    permissions:
    - essentials.kit
    - sg.arena.join.*
    - sg.arena.vote
    - sg.arena.spectate
    - sg.lobby.join    
    - essentials.kits.legend
    prefix: '&dLegend&7'
```
