### ISSUE TITLE
Permissions. what is wrong?

### ISSUE THREAD

**Issue by dr4i3n** [PEXPlugins/PermissionsEx#847]
```
users:
    Knife:
        group:
        - Hrac
    TroskaGaminn:
        group:
        - Hrac
    z00ter:
        group:
        - Majitel
    Donpich:
        group:
        - Moderator
    dr4i3n:
        group:
        - Majitel
    MikyCZ:
        group: []
    XAVINATO:
        group:
        - Hl.Admin
groups:
    Hrac:
        default: true
        options: null
        prefix: '&0[&6´fHrac&0]&f '
        suffix: '&a'
        permissions:
        - modifyworld.*
        - signlift.*
        - essentials.spawn
        - essentials.portal
        - essentials.home
        - essentials.sethome
        - essentials.tpa
        - essentials.tpadeny
        - essentials.tpaccept
        - essentials.msg
        - essentials.balance
        - ChestShop.shop.buy
        - chestShop.shop.sell
        - ChestShop.shop.create
        - AuthMe.*
        - iConomy.holdings

    Hl.Admin:
        options: null
        prefix: '&6[&6Hl.Admin&6]&6 '
        suffix: '&a'
        permissions:
        - '*'
    Majitel:
        options: null
        prefix: '&4[&lMajitel&4]&6 '
        suffix: '&a'
        permissions:
        - '*'
        - iConomy.holdings
        - essentials.balance
        - modifyworld.chat
        - modifyworld.sprint
        - AuthMe.*
    Moderator:
        options: null
        prefix: '&e[&eModerator&e]&a '
        suffix: '&a'
        permissions:
        - authme.player.*
        - essentials.kit
        - essentials.balance
        - essentials.balance.others
        - essentials.balancetop
        - essentials.pay
        - essentials.sell
        - essentials.worth
        - essentials.afk
        - essentials.getpos
        - essentials.help
        - essentials.helpop
        - essentials.list
        - essentials.mail
        - essentials.mail.send
        - essentials.me
        - essentials.msg
        - essentials.near
        - essentials.rules
        - essentials.spawn
        - essentials.back
        - essentials.delhome
        - essentials.home
        - essentials.home.bed
        - essentials.sethome
        - essentials.sethome.bed
        - essentials.tpa
        - essentials.tpaccept
        - essentials.tpahere
        - essentials.tpdeny
        - essentials.warp.list
        - essentials.warps.*
        - residence.create
        - essentials.bigtree
        - essentials.feed
        - essentials.fly
        - essentials.fly.safelogin
        - essentials.god
        - essentials.hat
        - essentials.heal
        - essentials.ptime
        - essentials.pweather
        - essentials.repair.*
        - essentials.tree
        - essentials.workbench
        - essentials.book
        - essentials.book.author
        - essentials.book.title
        - essentials.compass
        - essentials.back
        - essentials.back.ondeath
        - essentials.keepxp
        - essentials.sethome.multiple
        - essentials.sethome.multiple.unlimited
        - essentials.clearinventory
        - essentials.burn
        - essentials.kick
        - essentials.kill
        - essentials.mute
        - ultraban.warn
        - ultraban.kick
        - ultraban.checkip
        - ultraban.check
        - carz.use
        - carz.upgrade
        - carz.place
        - disguisecraft.mob.*
        - disguisecraft.object.*
        - disguisecraft.player.*
        - plotme.use
        - multiverse.portal.access.Creative
        - multiverse.portal.access.Spawn
        - multiverse.portal.access.Spawn1
        - multiverse.portal.access.SkyBlock
        - multiverse.access.Creative
        - multiverse.teleport.self.Creative
        - multiverse.access.Spawn
        - multiverse.teleport.self.Spawn
        - multiverse.access.SkyBlock
        - multiverse.teleport.self.SkyBlock
        - usb.island.*
        - usb.party.*
    VIP:
        options: null
        prefix: '&0[&6VIP&0]&6 '
        suffix: '&a'
        permissions:
        - permissions.*
```
