### ISSUE TITLE
pex error

### ISSUE THREAD

**Issue by BIO620** [PEXPlugins/PermissionsEx#940]
### Description

[Insert description of issue here]
### What PEX Saw

**Reason:** Error checking isPermissionSet for DANYx16

**Stacktrace:**

```
java.util.regex.PatternSyntaxException: Illegal character range near index 11
&9&l[SUPER-MOD]
           ^
    at java.util.regex.Pattern.error(Unknown Source)
    at java.util.regex.Pattern.range(Unknown Source)
    at java.util.regex.Pattern.clazz(Unknown Source)
    at java.util.regex.Pattern.sequence(Unknown Source)
    at java.util.regex.Pattern.expr(Unknown Source)
    at java.util.regex.Pattern.compile(Unknown Source)
    at java.util.regex.Pattern.<init>(Unknown Source)
    at java.util.regex.Pattern.compile(Unknown Source)
    at ru.tehkode.permissions.RegExpMatcher.createPattern(RegExpMatcher.java:24)
    at ru.tehkode.permissions.RegExpMatcher.isMatches(RegExpMatcher.java:17)
    at ru.tehkode.permissions.PermissionEntity.isMatches(PermissionEntity.java:521)
    at ru.tehkode.permissions.PermissionEntity.getMatchingExpression(PermissionEntity.java:504)
    at ru.tehkode.permissions.PermissionEntity.getMatchingExpression(PermissionEntity.java:499)
    at ru.tehkode.permissions.PermissionUser.getMatchingExpression(PermissionUser.java:913)
    at ru.tehkode.permissions.bukkit.superperms.PermissiblePEX.isPermissionSet(PermissiblePEX.java:242)
    at org.bukkit.craftbukkit.v1_6_R2.entity.CraftHumanEntity.isPermissionSet(CraftHumanEntity.java:103)
    at com.earth2me.essentials.perm.SuperpermsHandler.hasPermission(SuperpermsHandler.java:40)
    at com.earth2me.essentials.perm.PermissionsExHandler.hasPermission(PermissionsExHandler.java:69)
    at com.earth2me.essentials.perm.PermissionsHandler.hasPermission(PermissionsHandler.java:74)
    at com.earth2me.essentials.User.isAuthorizedCheck(User.java:94)
    at com.earth2me.essentials.User.isAuthorized(User.java:76)
    at com.earth2me.essentials.EssentialsPlayerListener$2.run(EssentialsPlayerListener.java:216)
    at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
    at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:522)
    at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
    at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
    at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
    at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
```
### PEX configuration

``` yaml
permissions:
  backend: file
  backends:
    file:
      file: permissions.yml
  superperms: {}
```
### Permissions database

``` yaml
groups:
  Esclavo:
    permissions:
    - -modifyworld.items.craft.310
    - -modifyworld.items.craft.311
    - -modifyworld.items.craft.312
    - -modifyworld.items.craft.313
    - -modifyworld.blocks.destroy.56
    - -modifyworld.items.have.310
    - -modifyworld.items.have.311
    - -modifyworld.items.have.312
    - -modifyworld.items.have.313
    - -essentials.pay
    - -essentials.sell
    - essentials.home
    - essentials.sethome
    - essentials.home.bed
    - essentials.warp
    - essentials.warp.list
    - essentials.suicide
    - essentials.tpaccept
    - essentials.tpdeny
    - WelcomeBook.GetBooks
    - automessage.receive.default
    prefix: ''
    options:
      build: true
      rank: '1000'
  Noob:
    permissions:
    - essentials.list
    - essentials.clearinventory
    - disguisecraft.seer
    - essentials.worth
    - essentials.spawn
    - essentials.rules
    - essentials.motd
    - essentials.helpop
    - essentials.home
    - essentials.sethome
    - essentials.msg
    - essentials.home.bed
    - essentials.warp
    - essentials.warp.list
    - essentials.suicide
    - essentials.balance
    - essentials.balancetop
    - modifyworld.*
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpdeny
    - preciousstones.benefit.*
    - preciousstones.whitelist.*
    - essentials.kit
    - essentials.kits.tools
    - essentials.kits.comida
    - essentials.kits.pikers
    - essentials.worth
    - buttonwarp.move
    - automessage.receive.default
    - creativegates.use
    - PointShop.buy.Cmd
    - PointShop.list
    - PointShop.sign.use
    - chestcommands.use
    - essentials.signs.use.*
    - quickshop.use
    - quickshop.create.sell
    - quickshop.create.buy
    - quickshop.create.double
    - quickshop.create.changeprice
    - quickshop.find
    - craftbook.mech.chair.use
    - essentials.kits.guerrero
    - essentials.pay
    - essentials.delhome
    - MyPet.user.leash.wolf
    - MyPet.user.capturehelper
    - MyPet.user.keep.wolf
    - MyPet.user.keep.sheep
    - MyPet.user.leash.sheep
    - MyPet.user.keep.cow
    - MyPet.user.leash.cow
    - MyPet.user.keep.pig
    - MyPet.user.leash.pig
    - MyPet.user.keep.chiken
    - MyPet.user.leash.chiken
    - MyPet.user.keep.ocelot
    - MyPet.user.leash.ocelot
    - MyPet.user.extended.CanFeed
    - MyPet.user.extended.Beacon
    - MyPet.user.extended.Behavior.*
    - MyPet.custom.skilltree.default
    - MyPet.user.extended.Ride
    - MyPet.user.extended.Inventory
    - MyPet.user.extended.Equip
    - MyPet.user.extended.Control
    - MyPet.user.command.capturehelper
    - MyPet.user.command.release
    - MyPet.user.command.respawn
    - MyPet.user.command.name
    - PointShop.buy.TimePerm
    - EnderChestPlus.use
    - EnderChestPlus.normal
    - sc.slots.create
    - sc.slots.withdraw
    - sc.slots.deposit
    - sc.blackjack.create
    - sc.blackjack.withdraw
    - sc.blackjack.deposit
    - sb.use.money
    - PlayerPoints.look
    - PlayerPoints.me
    - PointShop.buy.Item
    - PointShop.buy.ItemSet
    - buttonsplus.alltypes.push
    - buttonsplus.text
    - buttonsplus.command.push
    - buttonsplus.teleport.push
    - buttonsplus.item.push
    - buttonsplus.console.push
    - buttonsplus.death.push
    - buttonsplus.heal.push
    - buttonsplus.lightning.push
    - buttonsplus.burn.push
    - crackshot.use.all
    - pvpgunplus.user
    - pvpgunplus.deagle
    - pvpgunplus.doublebarrel
    - pvpgunplus.l118a
    - pvpgunplus.law
    - pvpgunplus.m16
    - pvpgunplus.m4a1
    - pvpgunplus.spas12
    - pvpgunplus.flashbang
    - pvpgunplus.grenada
    - pvpgunplus.molotov
    - pvpgunplus.smokegrenade
    - arena.tourney.join
    - arena.join.arena
    - arena.join.skirmish
    - arena.join.colosseum
    - arena.join.battleground
    - arena.join.tourney
    - arena.join.freeforall
    - arena.join.deathmatch
    - arena.team.create
    - arena.team.join
    - arena.leave
    - sg.arena.join
    - sg.lobby.join
    - sg.arena.vote
    - sg.arena.join.*
    - sg.arena.spectate
    - Infected.shop
    - Infected.join
    - arena.class.use.*
    - usb.island.create
    - usb.island.sethome
    - usb.party.create
    - usb.party.kick
    - usb.party.makeleader
    - usb.party.join
    - usb.island.topten
    - mobarena.arenas.default
    - mobarena.use.spec
    - mobarena.use.join
    prefix: '&2[Aldeano]&7 '
    options:
      build: true
      rank: '998'
  Aprendiz:
    default: true
    permissions:
    - essentials.list
    - essentials.help
    - essentials.sethome.multiple.Aprendiz
    - TheArcher.user.Commands
    - MyPet.user.keep.zombie
    - MyPet.user.leash.zombie
    inheritance:
    - Noob
    prefix: '&9[Aprendiz]&7 '
    options:
      build: true
      rank: '990'
  Arquero:
    permissions:
    - TheArcher.user.Mine
    - TheArcher.user.EagleEye
    - TheArcher.user.Torch
    - TheArcher.user.Fire
    - TheArcher.user.Incendiary
    - MyPet.user.leash.Skeleton
    - MyPet.user.keep.Skeleton
    inheritance:
    - Aprendiz
    prefix: '&9[Arquero]&7 '
    options:
      build: true
      rank: '980'
  Hechicero:
    permissions:
    - TheArcher.user.Gatling
    - TheArcher.user.Explosive
    - TheArcher.user.Slowing
    - TheArcher.user.Poison
    - TheArcher.user.Teleport
    - MyPet.user.release
    - MyPet.user.keep.PigZombie
    - MyPet.user.leash.PigZombie
    inheritance:
    - Arquero
    prefix: '&3[Hechicero]&7 '
    options:
      build: true
      rank: '900'
  Brujo:
    permissions:
    - TheArcher.user.Gatling
    - TheArcher.user.Shotgun
    - TheArcher.user.Web
    - TheArcher.user.Dizzy
    - essentials.back.ondeath
    - essentials.afk
    - essentials.workbench
    - MyPet.user.leash.Spider
    - MyPet.user.keep.Spider
    inheritance:
    - Hechicero
    prefix: '&3[Brujo]&7 '
    options:
      build: true
      rank: '880'
  Mago:
    permissions:
    - TheArcher.user.Gatling
    - TheArcher.user.Trap
    - TheArcher.user.Thunder
    - essentials.heal
    - MyPet.user.leash.Blaze
    - MyPet.user.keep.Blaze
    inheritance:
    - Brujo
    prefix: '&b[Mago]&7 '
    options:
      build: true
      rank: '850'
  Maestro:
    permissions:
    - TheArcher.user.Gatling
    - TheArcher.user.Gravity
    inheritance:
    - Mago
    prefix: '&6&l[Maestro]&7'
    options:
      build: true
      rank: '840'
  Donador:
    permissions:
    - essentials.repair.all
    - essentials.repair
    - godPowers.heal
    - essentials.protect.pvp
    - TheArcher.user.Commands
    - craftbook.mech.chair.use
    - essentials.back
    - essentials.back.ondeath
    - essentials.chat.color
    - essentials.chat.shout
    - essentials.chat.question
    - essentials.sethome.multiple.vip
    - essentials.ignore
    - essentials.nick
    - essentials.mail
    - essentials.mail.send
    - essentials.repair.armor
    - essentials.repair.enchanted
    - essentials.heal
    - essentials.workbench
    - essentials.signs.use.*
    - essentials.hat
    - supernatural.admin.command.cure
    - essentials.joinfullserver
    - modifyworld.items.pickup.*
    inheritance:
    - Noob
    prefix: '&3[Donador]'
    options:
      build: true
      rank: '830'
  VIP:
    permissions:
    - essentials.repair.all
    - essentials.repair
    - essentials.heal
    - essentials.help
    - essentials.list
    - essentials.feed
    - godPowers.heal
    - vote.voteyes.*
    - craftbook.mech.chair.use
    - MyPet.user.leash.Skeleton
    - MyPet.user.keep.Skeleton
    - MyPet.user.leash.PigZombie
    - MyPet.user.keep.PigZombie
    - MyPet.user.leash.Pig
    - MyPet.user.keep.Pig
    - MyPet.user.leash.Creeper
    - MyPet.user.keep.Creeper
    - MyPet.user.leash.Spider
    - MyPet.user.keep.Spider
    - MyPet.user.leash.Slime
    - MyPet.user.keep.Slime
    - MyPet.user.leash.Irongolem
    - MyPet.user.keep.Irongolem
    inheritance:
    - Donador
    prefix: '&b[VIP]&7 '
    options:
      build: true
      rank: '800'
  VIP+:
    permissions:
    - essentials.bigtree
    - disguisecraft.mob.Squid
    - disguisecraft.mob.Sheep
    - disguisecraft.mob.Pigzombie
    - disguisecraft.mob.Pig
    - disguisecraft.mob.Skeleton
    - disguisecraft.mob.Enderman
    - disguisecraft.mob.Creeper
    - disguisecraft.mob.Cow
    - disguisecraft.mob.Chicken
    - disguisecraft.mob.CaveSpider
    - disguisecraft.mob.Bat
    - essentials.firework.fire
    - essentials.firework
    - essentials.repair.all
    - essentials.list
    - essentials.help
    - nametags.color.aqua
    - essentials.feed
    - craftbook.mech.chair.use
    - essentials.fly
    - essentials.sethome.multiple.vipplus
    - MyPet.user.leash.Blaze
    - MyPet.user.keep.Blaze
    - MyPet.user.leash.Enderman
    - MyPet.user.keep.Enderman
    - MyPet.user.leash.Bat
    - MyPet.user.keep.Bat
    - essentials.nick.color
    inheritance:
    - VIP
    prefix: '&b[VIP+]&7 '
    options:
      build: true
      rank: '750'
  Helper:
    permissions:
    - essentials.help
    - nametags.color.light_purple
    - essentials.list
    - mcmmo.chat.adminchat
    - vote.voteyes.*
    - hugs.cankiss
    - craftbook.mech.chair.use
    - Atiloz
    - OpTalk.chat
    - essentials.back
    - essentials.kick.notify
    - essentials.kick
    - essentials.mute
    - essentials.mute.notify
    - essentials.helpop.*
    - essentials.realname
    - essentials.afk
    - essentials.back.ondeath
    - essentials.chat.color
    - essentials.chat.shout
    - essentials.chat.question
    - essentials.depth
    - essentials.home
    - essentials.ignore
    - essentials.mail
    - essentials.mail.send
    - essentials.me
    - essentials.msg
    - essentials.pay
    - essentials.ping
    - essentials.sethome
    - essentials.suicide
    - essentials.time
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpdeny
    - essentials.realname
    - modifyworld.items.pickup.*
    inheritance:
    - Aprendiz
    prefix: '&5[Ayudante]&7 '
    options:
      build: true
      rank: '700'
  Mod:
    permissions:
    - godPowers.heal
    - jail.command.jailclear
    - nametags.color.dark_purple
    - jail.command.unjail
    - jail.command.unail
    - jail.command.jail
    - mcmmo.chat.adminchat
    - OpTalk.chat
    - essentials.helpop.*
    - essentials.tempban
    - essentials.broadcast
    - essentials.eco.loan
    - essentials.helpop.recieve
    - essentials.jails
    - essentials.jump
    - essentials.kick
    - essentials.kick.notify
    - essentials.mute
    - essentials.nick.others
    - essentials.realname
    - essentials.nick.color
    - essentials.nick.format
    - essentials.nick
    inheritance:
    - Helper
    prefix: '&5[Mod]&7 '
    options:
      build: true
      rank: '300'
  Admin:
    permissions:
    - jail.command.unjail
    - jail.command.jail
    - mcmmo.chat.adminchat
    - OpTalk.chat
    - -essentials.backup
    - -essentials.essentials
    - -essentials.setspawn
    - -essentials.reloadall
    - essentials.*
    - permissions.manage.users
    - permissions.manage.users.permissions
    - permissions.manage.users.permissions.timed
    - sg.arena.create
    - sg.arena.setspawn
    - sg.arena.resetspawns
    - sg.arena.delete
    - sg.lobby.set
    - permissions.manage.membership.Aprendiz
    - permissions.manage.membership.Helper
    - iConomy.accounts.give
    inheritance:
    - Mod
    prefix: '&c[Admin]&7 '
    options:
      build: true
      rank: '200'
  Owner:
    permissions:
    - OpTalk.*
    - nametags.color.dark_red
    - '*'
    inheritance:
    - Admin
    prefix: '&4[Owner]&7 '
    options:
      build: true
      rank: '0'
  aldeano: {}
  Platinum:
    inheritance:
    - VIP+
    permissions:
    - essentials.bigtree
    - disguisecraft.mob.*
    - essentials.firework.fire
    - essentials.firework
    - essentials.repair.all
    - godPowers.jesus
    - modifyworld.items.pickup.*
    - nametags.color.dark_gray
    - essentials.kits.platinum2
    - essentials.kits.wood
    - essentials.kits.platinum
    - essentials.list
    - essentials.help
    - godPowers.gaia
    - disguisecraft.mob.enderman
    - disguisecraft.mob.cat.*
    - disguisecraft.mob.ocelot
    - disguisecraft.mob.pigzombie
    - disguisecraft.mob.skeleton
    - disguisecraft.mob.zombie
    - godPower.gaia
    - essentials.enderchest
    - essentials.top
    prefix: '&8&l[Platinum]&3'
  ELITE:
    permissions:
    - essentials.spawner.zombie
    - essentials.spawner.blaze
    - essentials.spawner.skeleton
    - essentials.spawner.chiken
    - essentials.spawner.spider
    - essentials.spawner.cavespider
    - essentials.spawner
    - essentials.bigtree
    - essentials.firework
    - essentials.firework.
    - essentials.firework.fire
    - essentials.lightning
    - commandcooldown.lightning60
    - essentials.thor
    - godPowers.jesus
    - nametags.color.dark_blue
    - essentials.help
    - essentials.list
    - essentials.speed
    - disguisecraft.mob.*
    - godPowers.superjump
    - godPowers.godtools
    - essentials.speed.walk
    - essentials.speed.fly
    - essentials.getpos
    - essentials.tppos
    - essentials.jump
    - essentials.kits.elite
    inheritance:
    - Platinum
    prefix: '&1&l[ELITE]&3'
  arpendiz: {}
  vi+p:
    permissions:
    - essentials.repair.all
  noobie:
    permissions:
    - sg.lobby.join
    - sg.arena.vote
    - sg.arena.join.*
  ellite:
    permissions:
    - essentials.spawner
  addmin:
    permissions:
    - disguisecraft.*
users:
  xxBoWiExx:
    group:
    - Owner
    - CUENTAROBADa
    prefix: '&4&l[Owner]'
    worlds:
      facs: {}
    permissions:
    - TheArcher.user.Incendiary
    - TheArcher.user.Fire
    - TheArcher.user.Torch
    - TheArcher.user.EagleEye
    - TheArcher.user.Mine
  FearDaCaptain:
    group:
    - VIP+
    - Arquero
  ZTriff:
    group:
    - Aprendiz
  antrax:
    group:
    - Aprendiz
  sartios:
    group:
    - Aprendiz
    - Miembro
  ElmatyOMFG:
    group:
    - ELITE
  FNTCZ:
    group:
    - Admin
    - Aprendiz
    prefix: '&c[Admin]'
  DiamondSoldier:
    group:
    - Miembro
  SpecialSV:
    group:
    - Aprendiz
  Hollit:
    group:
    - Arquero
    - VIP+
    - ayudante
    prefix: '&3[VIP+]'
  integro96:
    group:
    - Donador
    - Hechicero
  perujo:
    group:
    - Miembro
  jorgel21200:
    group:
    - VIP+
    worlds:
      '30':
        group:
        - VIP+
  Facuagus:
    group:
    - Arquero
  group:
    options:
      Notsuru: Helper
      Gaustad96: Noob
    worlds:
      Helper:
        permissions:
        - SkullCompanyArg
  Notsuru:
    group:
    - Hechicero
  elfresitaa:
    group:
    - Hechicero
  Jexeld:
    group:
    - Aprendiz
  zapi:
    group:
    - Aprendiz
  Claush:
    options:
      group: Helper
    group:
    - Aprendiz
  IrvingBs:
    group: []
  thanoz:
    group:
    - CUENTAROBADa
  vicioanime10:
    group:
    - Default
    - Hechicero
  seba:
    group:
    - Hechicero
  cuttierosa:
    group:
    - Aprendiz
  frankzz:
    group:
    - Maestro
    - VIP+
    - Brujo
  Gaustad96:
    group:
    - Hechicero
    prefix: '&9&l[Super-Mod]'
    permissions:
    - Admin
    - Mod
  creeperkiller88:
    group:
    - Aprendiz
  itachi18:
    group: []
    permissions:
    - essentials.fly
    prefix: '&9&l[Super-Mod]'
  Kratos28:
    group:
    - Brujo
  Jose:
    group:
    - Mago
    - VIP+
    - VIP
  rasta17:
    group:
    - Aprendiz
  Ahre09:
    group:
    - Aprendiz
  Atiloz:
    group:
    - ELITE
    - Helper
    - Arquero
    prefix: '&1&l[ELITE]&5[A]'
  eimattz:
    group:
    - Aprendiz
  Cheynlong:
    group:
    - Hechicero
  GreenDay:
    group:
    - Hechicero
  Exze:
    group:
    - Aprendiz
  PatimbaMC:
    group:
    - Aprendiz
  Wayne:
    group: []
  zev1t:
    group:
    - Hechicero
  miinereexii:
    group:
    - Hechicero
  darkcause:
    group:
    - Aprendiz
  HACKhalo2:
    group:
    - Mod
    - Mago
    - VIP+
    prefix: '&5[Mod]'
  lucho:
    group:
    - Aprendiz
  german:
    group:
    - Hechicero
  Foogles:
    group:
    - Aprendiz
  Tooto:
    group:
    - Hechicero
  smeraldox11:
    group:
    - Aprendiz
  lMati:
    group:
    - Arquero
  FERNAND0XX007:
    group:
    - Aprendiz
  Chris:
    group:
    - Aprendiz
  Eli009:
    group:
    - VIP+
  Fierro_:
    group:
    - Aprendiz
  TheRabbitZero:
    group:
    - Arquero
  TheJospy:
    group:
    - Hechicero
    prefix: '&5[Mod]'
  fran:
    group:
    - Aprendiz
  YellowMellowMG:
    group:
    - Aprendiz
  sepita:
    group:
    - Aprendiz
  lautarolucas:
    group:
    - Hechicero
  Thuntherstorm:
    group:
    - Aprendiz
  Warrior:
    group:
    - Aprendiz
  Cthululoo:
    group:
    - Hechicero
    permissions:
    - VIP
  lean915:
    group:
    - Arquero
  tofuguy:
    group:
    - VIP+
    - Aprendiz
  Lucasanse:
    group:
    - VIP
    - Aprendiz
  Chelcolo:
    group:
    - Aprendiz
  Chevy1947:
    group:
    - Aprendiz
  xZeeikeer:
    group:
    - Aprendiz
  KnightMurderer:
    group:
    - Aprendiz
  Jaymun:
    group:
    - Aprendiz
  Ruler23:
    group:
    - Aprendiz
  xxxMATIASxxx:
    group:
    - Aprendiz
  Turiki:
    group:
    - Aprendiz
  Dormammu:
    group:
    - Aprendiz
  jann:
    group:
    - Arquero
  SparklyTea:
    group:
    - Aprendiz
  Minecraftero:
    group:
    - Arquero
  vopojtepek:
    group:
    - Aprendiz
  juliboy200:
    group:
    - Arquero
  Link:
    group:
    - Aprendiz
  chuyito:
    group:
    - Aprendiz
  hugoxx27:
    group:
    - Aprendiz
  Nelson:
    group:
    - Aprendiz
  SkullCompanyArg:
    group:
    - ELITE
    - Brujo
    prefix: '&1&l[ELITE]'
  Razgriz:
    group:
    - Aprendiz
  sthos:
    group:
    - Aprendiz
  DarkTwister:
    group:
    - Aprendiz
  GTDjulian:
    group:
    - Aprendiz
  axelema:
    group:
    - Aprendiz
  martin:
    group:
    - Aprendiz
  Fabi_pixel:
    group:
    - Aprendiz
  Megapix98:
    group:
    - Arquero
  XxTheSlashxX_12:
    group:
    - Aprendiz
  xRpMx13:
    group:
    - Aprendiz
  tingui:
    group:
    - Aprendiz
  Belp:
    group:
    - SoyExclavo
    - Aprendiz
  RamaRex:
    group:
    - VIP+
    - Hechicero
  ELRAMAMONSTRUO:
    group:
    - Aprendiz
  Rattlehead:
    group:
    - Aprendiz
  jiorGioCarttoni:
    group:
    - Aprendiz
  blackside:
    group:
    - Aprendiz
  Yusia:
    group:
    - Aprendiz
  spillbert:
    group:
    - Aprendiz
  crossfire2:
    group:
    - Hechicero
  abbylib9:
    group:
    - Aprendiz
  Calla:
    group:
    - Arquero
    - VIP
    worlds:
      '2592000':
        group:
        - VIP
  Kowix:
    group:
    - Aprendiz
  RK13:
    group:
    - Aprendiz
  Bross:
    group:
    - Arquero
  mauricio:
    group:
    - Aprendiz
  holaaas:
    group:
    - Aprendiz
  mineju:
    group: []
  EmeraldStar82:
    group:
    - Aprendiz
  DeceptivePanda:
    group:
    - Aprendiz
  Yunie:
    group:
    - Aprendiz
  knux45dx:
    group:
    - Aprendiz
  victorloz:
    group:
    - Aprendiz
  Chauuus:
    group:
    - Aprendiz
  DefektIV:
    group:
    - Aprendiz
  jotta132:
    group:
    - Aprendiz
  SeCoNoMaS:
    group:
    - Aprendiz
  octisegui123:
    group:
    - Aprendiz
  BadBoyBob:
    group:
    - Arquero
    - Default
  Shutero:
    group:
    - Arquero
  Cadasa:
    group:
    - Aprendiz
  Lynkaico:
    group:
    - Aprendiz
  crazyellis:
    group:
    - Aprendiz
  Zer0:
    group:
    - Brujo
  lucas0006:
    group:
    - Hechicero
  Raku525:
    group:
    - Aprendiz
  alienbrayn:
    group:
    - Aprendiz
  XxfacheroxX:
    group:
    - Aprendiz
  Alakazam:
    group:
    - Aprendiz
  gonzaloox:
    group:
    - Aprendiz
  kleyber:
    group:
    - Aprendiz
  Ciro:
    group:
    - Aprendiz
  max10:
    group:
    - Aprendiz
  123popodgato:
    group:
    - Arquero
  zedpenguin:
    group:
    - Aprendiz
  NecroHeaven:
    group:
    - Aprendiz
  Buttgirl:
    group:
    - Aprendiz
  day1997:
    group:
    - Aprendiz
  mariano14:
    group:
    - Hechicero
  sasukexdark:
    group:
    - Aprendiz
  Facundo:
    group:
    - Aprendiz
  minegamer267:
    group:
    - Brujo
  Thanesean0109:
    group:
    - Aprendiz
  rainbowacidink:
    group:
    - Aprendiz
  Vincentamus:
    group:
    - Aprendiz
  ezequielbari:
    group:
    - Platinum
    - VIP+
    - Hechicero
  Jose77Tron:
    group:
    - Aprendiz
  JerryKawi:
    group:
    - Aprendiz
  PUNKwithFUNK:
    group:
    - Aprendiz
  reapaninja:
    group:
    - Aprendiz
  fanta918:
    group:
    - Aprendiz
  Sebaschido08:
    group:
    - Aprendiz
  Fundador:
    group:
    - Aprendiz
  L_NK:
    group:
    - Aprendiz
  Luquuitas:
    group:
    - Arquero
  enzo1234:
    group:
    - Hechicero
    - Default
  FacuPerez:
    group:
    - Aprendiz
  lauta:
    group:
    - Aprendiz
  putardahdp:
    group:
    - Aprendiz
  Santjigh:
    group:
    - Aprendiz
  draforzx:
    group:
    - Aprendiz
  xSebaxT:
    group:
    - Aprendiz
  TaToLoKo69:
    gro
[ truncated somehow ]
```
