### ISSUE TITLE
Wrong prefix with temporary groups.

### ISSUE THREAD

**Issue by filoghost** [PEXPlugins/PermissionsEx#958]
Issue: I have this file:

``` yaml
groups:
  user:
    default: true
    prefix: '[User]'
    options:
      rank: '100'
  voter:
    prefix: '[Voter]'
    options:
      rank: '90'
  vip:
    prefix: '[Vip]'
    inheritance:
    - user
    options:
      rank: '80'
users:
  filoghost:
    group:
    - voter
    - vip
    options:
      group-voter-until: '1375971058'
```

The user filoghost is in 2 groups. Vip has a higher rank than voter, but in the chat appears "[Voter] filoghost" instead of [Vip]. If I don't give temporary permissions, link this:

```
users:
  filoghost:
    group:
    - voter
    - vip
```

the prefix is correct [Vip].
Please, could you fix this issue, or tell me how to make it work?
