### ISSUE TITLE
Double-negation in plugin.yml

### ISSUE THREAD

**Issue by turt2live** [PEXPlugins/PermissionsEx#971]
With PEX (and only PEX) if the following appears in the plugin.yml for a plugin (such as mine) then the player ends up with incorrect permissions (by default).

``` yaml
permissions:
    SomePlugin.*:
        default: false
        children:
            SomePlugin.node1: true
            SomePlugin.node2: true
            SomePlugin.node3: true
    SomePlugin.node1:
        default: true
    SomePlugin.node2:
        default: true
    SomePlugin.node3:
        default: false
```

This ticket describes a scenario where both PEX and "SomePlugin" are fresh installs.

The above is saying that "SomePlugin.node3" should never be applied to a player. But because of the explicit "default: false" on "SomePlugin.*" the player ends up GETTING "SomePlugin.node3" as well as node1 and node2. If I were to change "default: true" or to some other value on the \* node then the permissions work as expected.

What SHOULD occur is that the player ends up with "SomePlugin.node1" and "SomePlugin.node2" with "SomePlugin.node3" being false. If they were to have "SomePlugin.*" (set in the permissions.yml file) then the player should have all 3 nodes.

This means that PEX currently breaks how plugin permissions are defined.

Although PEX supports calculating permissions from XYZ.\* (meaning the SomePlugin.\* node does not need to be defined), not all permissions plugins support this feature.

In addition I, as a developer, want to restrict SomePlugin.\* to be FALSE by default, and maybe I want SomePlugin.node4 to be FALSE when SomePlugin.\* is applied. PEX cannot handle this internally without it being defined in the plugin.yml.
